playerarea_color = "Blue"
loc_discard      = {-44.57, 1.50, -21.00}
rot_discard      = {0.00, 270.00, 0.00}

function onLoad()
    update_buttons()
end -- end onLoad()

function open_bag(_, playercolor, alt_click)
    if not alt_click then
        self.Container.search(playercolor)
    elseif alt_click then
        local bag_objects = self.getObjects()
        for i = 1, #bag_objects do
            local object = self.takeObject({rotation=rot_discard})
            object.setPositionSmooth(loc_discard, false, false)
        end
    end
end -- end open_bag()


function remove_buttons(object)
    local buttons = object.getButtons()
    if #buttons > 0 then
        for k = #buttons, 1, -1 do
            if buttons[k].index ~= nil then
                object.removeButton(buttons[k].index)
            end
        end
    end
end -- end remove_buttons()


function create_search_button()
    self.createButton({
        click_function = "open_bag",
        function_owner = self,
        label          = "",
        position       = {0, 0.17, 0.70},
        rotation       = {0, 180, 0},
        width          = 450,
        height         = 145,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .2},
        hover_color    = {1, 1, 1, .4},
        tooltip        = "Left click to search Beamed Cards, Right click to dismiss all Beamed Cards.",
    })
end -- end create_search_button()


function create_counter_button(bag_count)
    self.createButton({
        click_function = "null_func",
        function_owner = self,
        label          = bag_count,
        position       = {0, 0.17, -0.35},
        width          = 225,
        height         = 225,
        font_size      = 180,
        scale          = {2.3, 2.3, 2.3},
        color          = {31/255, 136/255, 255/255, 255},
        hover_color    = {31/255, 136/255, 255/255, 255},
        font_color     = {1, 1, 1, 1},
        tooltip        = "There are " .. bag_count .. " cards beamed here.",
    })
end -- end create_counter_button()


function update_buttons()
    -- get card in bag count
    local bag_objects = self.getObjects()
    local bag_count   = #bag_objects
    -- if bag count == 1, remove buttons & recreate counter button / search button
    local buttons = self.getButtons()
    if bag_count > 0 then
        if buttons ~= nil then
            self.clearButtons()
        end
        create_search_button()
        create_counter_button(bag_count)
    elseif bag_count == 0 then
        if buttons ~= nil then
            self.clearButtons()
        end
    end
end -- end update_buttons()


function onObjectEnterContainer(container, object)
    if container == self and object.tag == "Card" then
        update_buttons()
    elseif container == self and object.tag ~= "Card" then
        broadcastToColor("Beam bags only perform their scripted functionality for single card objects. Removing non-card object.", playerarea_color, "Orange")
        local errant_object = self.takeObject()
        local position = self.getPosition()
        position.y = position.y + .76
        errant_object.setPosition(position)
        errant_object.setPositionSmooth({-21.50, 1.50, 2.47}, false, false)
    end
end -- end onObjectEnterContainer()


function onObjectLeaveContainer(container, object)
    if container == self then
        update_buttons()
    end
end -- end onObjectLeaveContainer()



function null_func()
    return nil
end -- end null_func()
