card_zone = getObjectFromGUID("7d6590")
deck_zone = getObjectFromGUID("99a16f")
suit      = "Person"
loc_place = {-7.50, 1.50, 6.00}

function onLoad()
    create_button()
end -- end onLoad()


function create_button()
    self.createButton({
        click_function = "junk_card",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will junk the above " .. suit .. " Market card, destroy any glory left on it, and replace it if possible.",
    })
end -- end create_button()


function junk_card()
    Global.call('animate_button', {button=self})
    local card        = nil
    local glory_count     = 0
    local dilithium_count = 0
    local latinum_count   = 0
    local card_found      = false
    for _, object in pairs(card_zone.getObjects()) do
        if object.getName() == "Glory Token" then
            glory_count = glory_count + 1
        end
        if object.getName() == "Dilithium Token" then
            dilithium_count = dilithium_count + 1
        end
        if object.getName() == "Latinum Token" then
            latinum_count = latinum_count + 1
        end
        if object.hasTag('suit_' .. string.lower(suit)) then
            card = object
            card_found = true
        end
    end
    if glory_count > 0 or dilithium_count > 0 or latinum_count > 0 then
        broadcastToAll("Market cards with Resource Tokens on them may only be junked via Stardate Card.", "Orange")
        return nil
    end
    if not card_found then
        broadcastToAll("No " .. suit .. " card found to Junk.", "Orange")
        return nil
    end
    card.setPositionSmooth({-12.50, 2.00, 12.00}, false, false)
    broadcastToAll(suit .. "[" .. Color.fromString("White"):toHex() .. "] Card Junked: " .. card.getName(), {191/255, 164/255, 44/255})
    Wait.time(function()
    for _, object in pairs(deck_zone.getObjects()) do
        local replacement_card = nil
        if object.tag == "Deck" then
            replacement_card = object.takeObject()
        elseif object.tag == "Card" then
            replacement_card = object
        end
        if replacement_card ~= nil then
            replacement_card.setRotation({0.00, 180.00, 0.00})
            replacement_card.setPositionSmooth(loc_place, false, false)
            broadcastToAll("[" .. Color.fromString("White"):toHex() .. "] Replacement[-] " .. suit .. "[" .. Color.fromString("White"):toHex() .. "] Card drawn: " .. replacement_card.getName() .. "[-].", {191/255, 164/255, 44/255})
        end
    end
    end, 1)
end -- end junk_card()
