card_zone = getObjectFromGUID("7d6590")
deck_zone = getObjectFromGUID("99a16f")
suit      = "Person"
loc_place = {-7.50, 1.50, 6.00}

function onLoad()
    create_button()
end -- end onLoad()


function create_button()
    self.createButton({
        click_function = "gain_card",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will gain the above " .. suit .. " Market card to discard, take any glory left on it, and replace it if possible.\n\nIf vs. a solo bot, right clicking this button will perform the 'Gain' operation for the bot. (same as Gain To Discard)",
    })
end -- end create_button()


function gain_card(_, playercolor, alt_click)
    Global.call('animate_button', {button=self})
    if playercolor == "Blue" or playercolor == "Red" then
        local solo_check        = (playercolor == "Blue" and getObjectFromGUID("1a78a6").getGMNotes() or getObjectFromGUID("23bed4").getGMNotes())
        local is_solo           = solo_check == "solo"   and true or false
        if alt_click and is_solo then
            if playercolor     == "Blue" then
                playercolor     = "Red"
            elseif playercolor == "Red" then
                playercolor     = "Blue"
            end
        elseif alt_click and not is_solo then
            alt_click = false
        end
        local loc_gain          = (playercolor == "Blue" and {-44.50, 1.50, -21.00}) or playercolor == "Red" and {44.50, 1.50, 21.00}
        local rot_gain          = (playercolor == "Blue" and {0.00, 270.00, 0.00}) or playercolor == "Red" and {0.00, 90.00, 0.00}
        if alt_click and is_solo then
            rot_gain            = (playercolor == "Red"  and {0.00, 270.00, 0.00}) or playercolor == "Blue" and {0.00, 90.00, 0.00}
        end
        local counter           = (playercolor == "Blue" and getObjectFromGUID("d96ce2") or getObjectFromGUID("9a5066"))
        local card              = nil
        local glory_count       = 0
        local dilithium_count   = 0
        local latinum_count     = 0
        local card_found        = false
        for _, object in pairs(card_zone.getObjects()) do
            if object.hasTag('suit_' .. string.lower(suit)) then
                card = object
                object.setRotation(rot_gain)
                object.setPositionSmooth(loc_gain, false, false)
                card_found = true
            end
            if object.getName() == "Glory Token" then
                object.destruct()
                glory_count      = glory_count + 1
            end
            if object.getName() == "Dilithium Token" then
                object.destruct()
                dilithium_count  = dilithium_count + 1
            end
            if object.getName() == "Latinum Token" then
                object.destruct()
                latinum_count    = latinum_count + 1
            end
        end
        if not card_found then
            return nil
        end
        local glory_counter          = getObjectFromGUID(playercolor == "Blue" and "d96ce2" or "9a5066")
        local dil_counter            = getObjectFromGUID(playercolor == "Blue" and "a3ec59" or "f40879")
        local lat_counter            = getObjectFromGUID(playercolor == "Blue" and "39e892" or "c2bac2")
        local captain_zone           = getObjectFromGUID(playercolor == "Blue" and "75465f" or "75c041")
        local captain_pad            = getObjectFromGUID(playercolor == "Blue" and "997491" or "28a24b")
        for _, object in pairs(captain_zone.getObjects()) do
            if string.find(object.getName(), "Crew Board") and object ~= captain_pad then
                captain_card_name    = object.getName()
            end
        end
        local captain_name           = nil
        local split_name             = {}
        if captain_card_name        ~= nil then
            for str in string.gmatch(captain_card_name,  "%S+") do
                table.insert(split_name, str)
            end
        end
        captain_name = split_name[1]
        if glory_count > 0 and dilithium_count == 0 and latinum_count == 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. " Glory: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. " Glory: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. glory_count .. " Glory: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_glory = glory_counter.getVar('val')
            glory_counter.call('setValue', current_glory + glory_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_glory", "text",  current_glory + glory_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_glory", "text",  current_glory + glory_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_glory", "text",  current_glory + glory_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_glory", "text",  current_glory + glory_count)
            end
        elseif glory_count > 0 and dilithium_count > 0 and latinum_count == 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. " Glory and " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. ", along with " .. glory_count .. " Glory and " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. glory_count .. ", along with " .. glory_count .. " Glory and " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_glory = glory_counter.getVar('val')
            local current_dil   = dil_counter.getVar('val')
            glory_counter.call('setValue', current_glory + glory_count)
            dil_counter.call('setValue', current_dil + dilithium_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_glory", "text",  current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_hum_dilithium", "text", current_dil + dilithium_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_glory", "text",  current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_and_dilithium", "text", current_dil + dilithium_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_glory", "text",  current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_rom_dilithium", "text", current_dil + dilithium_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_kli_dilithium", "text", current_dil + dilithium_count)
            end
        elseif glory_count > 0 and dilithium_count == 0 and latinum_count > 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. " Glory and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. ", along with " .. glory_count .. " Glory and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. glory_count .. ", along with " .. glory_count .. ", along with " .. glory_count .. " Glory and " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_glory = glory_counter.getVar('val')
            local current_lat   = lat_counter.getVar('val')
            glory_counter.call('setValue', current_glory + glory_count)
            lat_counter.call('setValue', current_lat + latinum_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_hum_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_and_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_rom_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_kli_latinum", "text", current_lat + latinum_count)
            end
        elseif glory_count > 0 and dilithium_count > 0 and latinum_count > 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. " Glory, " .. dilithium_count .. " Dilithium, and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. glory_count .. " Glory, " .. dilithium_count .. " Dilithium, and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. glory_count .. " Glory, " .. dilithium_count .. " Dilithium, and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_glory = glory_counter.getVar('val')
            local current_dil   = dil_counter.getVar('val')
            local current_lat   = lat_counter.getVar('val')
            glory_counter.call('setValue', current_glory + glory_count)
            dil_counter.call('setValue', current_dil + dilithium_count)
            lat_counter.call('setValue', current_lat + latinum_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_hum_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_hum_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_and_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_and_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_rom_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_rom_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_glory", "text", current_glory + glory_count)
                UI.setAttribute(string.lower(playercolor) .. "_kli_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_kli_latinum", "text", current_lat + latinum_count)
            end
        elseif glory_count == 0 and dilithium_count > 0 and latinum_count == 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. dilithium_count .. " Dilithium: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_dil   = dil_counter.getVar('val')
            dilithium_counter.call('setValue', current_dil + dilithium_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_dilithium", "text", current_dil + dilithium_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_dilithium", "text", current_dil + dilithium_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_dilithium", "text", current_dil + dilithium_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_dilithium", "text", current_dil + dilithium_count)
            end
        elseif glory_count == 0 and dilithium_count > 0 and latinum_count > 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. dilithium_count .. " Dilithium and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. dilithium_count .. " Dilithium and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. dilithium_count .. " Dilithium and " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_dil = dil_counter.getVar('val')
            local current_lat   = lat_counter.getVar('val')
            dil_counter.call('setValue', current_dil + dilithium_count)
            lat_counter.call('setValue', current_lat + latinum_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_hum_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_and_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_rom_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_dilithium", "text", current_dil + dilithium_count)
                UI.setAttribute(string.lower(playercolor) .. "_kli_latinum", "text", current_lat + latinum_count)
            end
        elseif glory_count == 0 and dilithium_count == 0 and latinum_count > 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard, along with " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card, along with " .. latinum_count .. " Latinum: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
            local current_lat   = lat_counter.getVar('val')
            lat_counter.call('setValue', current_lat + latinum_count)
            if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
                UI.setAttribute(string.lower(playercolor) .. "_hum_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Shran" then
                UI.setAttribute(string.lower(playercolor) .. "_and_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Sela" then
                UI.setAttribute(string.lower(playercolor) .. "_rom_latinum", "text", current_lat + latinum_count)
            elseif captain_name == "Koloth" then
                UI.setAttribute(string.lower(playercolor) .. "_kli_latinum", "text", current_lat + latinum_count)
            end
        elseif glory_count == 0 and dilithium_count == 0 and latinum_count == 0 then
            if Player[playercolor].steam_name ~= nil then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
            else
                local player_str = "Player"
                if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                if player_str == "Player" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card to Discard: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                elseif player_str == "Bot" then
                    broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has gained[-] Person[" .. Color.fromString("White"):toHex() .. "] Card: " .. card.getName() .. "[-]", {191/255, 164/255, 44/255})
                end
            end
        end
        Wait.time(function()
        for _, object in pairs(deck_zone.getObjects()) do
            local replacement_card = nil
            if object.tag == "Deck" then
                replacement_card = object.takeObject()
            elseif object.tag == "Card" then
                replacement_card = object
            end
            if replacement_card ~= nil then
                replacement_card.setRotation({0.00, 180.00, 0.00})
                replacement_card.setPositionSmooth(loc_place, false, false)
                broadcastToAll("[" .. Color.fromString("White"):toHex() .. "] Replacement[-] " .. suit .. "[" .. Color.fromString("White"):toHex() .. "] Card drawn: " .. replacement_card.getName() .. "[-]", {191/255, 164/255, 44/255})
            end
        end
        end, 1)
    end
end -- end gain_card()
