

function onLoad()
    create_button()
end -- end onLoad()


function create_button()
    self.createButton({
        click_function = "refresh_glory",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will refresh the glory after a new stardate card is revealed.",
    })
end -- end create_button()


function run_refresh(parms)
    local playercolor = parms.playercolor
    refresh_glory(_, playercolor, _)
end -- end run_refresh()


function refresh_glory(_, playercolor, _)
    Global.call('animate_button', {button=self})
    local zone = getObjectFromGUID("338aa7")
    -- first check to make sure drop area isn't already populated
    local glory_found = false
    for _, object in pairs(zone.getObjects()) do
        if object.getName() == "Glory Token" then
            glory_found = true
        end
    end
    if glory_found then
        broadcastToAll("Refresh Glory Button only works while Stardate card is out of glory.", playercolor)
        return nil
    end
    local card_name = nil
    for _, object in pairs(getObjectFromGUID("090f7a").getObjects()) do
        if object.tag == "Deck" then
            local cards_in_deck = object.getObjects()
            card_name = cards_in_deck[#cards_in_deck].name
        elseif object.tag == "Card" then
            card_name = object.getName()
        end
    end
    -- determine glory count to refresh per card name
    local glory_count = nil
    if card_name     == "2-Player Stardate 1" then
        glory_count   = 5
    elseif card_name == "2-Player Stardate 2" then
        glory_count   = 7
    elseif card_name == "2-Player Stardate 3" then
        glory_count   = 7
    elseif card_name == "2-Player Stardate 4" then
        glory_count   = 6
    elseif card_name == "2-Player Stardate 5" then
        glory_count   = 5
    elseif card_name == "Solo Cadet Practice 1" then
        glory_count   = 5
    elseif card_name == "Solo Cadet Practice 2" then
        glory_count   = 5
    elseif card_name == "Solo vs. Ensign Bot Stardate 1" then
        glory_count   = 6
    elseif card_name == "Solo vs. Ensign Bot Stardate 2" then
        glory_count   = 7
    elseif card_name == "Solo vs. Ensign Bot Stardate 3" then
        glory_count   = 7
    elseif card_name == "Solo vs. Ensign Bot Stardate 4" then
        glory_count   = 6
    elseif card_name == "Solo vs. Ensign Bot Stardate 5" then
        glory_count   = 5
    elseif card_name == "Solo vs. Lieutenant Bot Stardate 1" then
        glory_count   = 5
    elseif card_name == "Solo vs. Lieutenant Bot Stardate 2" then
        glory_count   = 7
    elseif card_name == "Solo vs. Lieutenant Bot Stardate 3" then
        glory_count   = 7
    elseif card_name == "Solo vs. Lieutenant Bot Stardate 4" then
        glory_count   = 6
    elseif card_name == "Solo vs. Lieutenant Bot Stardate 5" then
        glory_count   = 5
    elseif card_name == "Solo vs. Commander Bot Stardate 1" then
        glory_count   = 5
    elseif card_name == "Solo vs. Commander Bot Stardate 2" then
        glory_count   = 7
    elseif card_name == "Solo vs. Commander Bot Stardate 3" then
        glory_count   = 7
    elseif card_name == "Solo vs. Commander Bot Stardate 4" then
        glory_count   = 6
    elseif card_name == "Solo vs. Commander Bot Stardate 5" then
        glory_count   = 5
    elseif card_name == "Solo vs. Captain Bot Stardate 1" then
        glory_count   = 5
    elseif card_name == "Solo vs. Captain Bot Stardate 2" then
        glory_count   = 6
    elseif card_name == "Solo vs. Captain Bot Stardate 3" then
        glory_count   = 7
    elseif card_name == "Solo vs. Captain Bot Stardate 4" then
        glory_count   = 6
    elseif card_name == "Solo vs. Captain Bot Stardate 5" then
        glory_count   = 5
    elseif card_name == "Solo vs. Admiral Bot Stardate 1" then
        glory_count   = 5
    elseif card_name == "Solo vs. Admiral Bot Stardate 2" then
        glory_count   = 5
    elseif card_name == "Solo vs. Admiral Bot Stardate 3" then
        glory_count   = 6
    elseif card_name == "Solo vs. Admiral Bot Stardate 4" then
        glory_count   = 6
    elseif card_name == "Solo vs. Admiral Bot Stardate 5" then
        glory_count   = 5
    end
    local bag  = getObjectFromGUID("263bae")
    local locs = {
        {-11.00, 0.85, 4.00},
        {-12.50, 0.85, 4.00},
        {-14.00, 0.85, 4.00},
        {-11.00, 0.85, 5.50},
        {-12.50, 0.85, 5.50},
        {-14.00, 0.85, 5.50},
        {-15.50, 0.85, 4.75},
    }
    if glory_count then
        for i = 1, glory_count do
            local token = bag.takeObject()
            token.setRotation({0.00, 180.00, 180.00})
            token.setPositionSmooth(locs[i], false, false)
            token.interactable = false
        end
        broadcastToAll(glory_count .. " Glory has been refreshed for: " .. card_name, "Green")
    else
        return
    end
end -- end refresh_glory()
