playerarea_color   = "Red"
replace_drop_loc   = {0.00, 2.00, -7.00}
location_checkzone = getObjectFromGUID("65beaa")

function onLoad()
    create_button()
end -- end onLoad()


function create_button()
    self.createButton({
        click_function = "control_location",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will control this location, return/dismiss away teams and ships, and replace the location if possible. It does not check to make sure a control is allowed before doing so.",
    })
end -- end create_button()


function control_location_remote(args)
    playercolor = args.playercolor
    control_location(_, playercolor, _)
end -- end control_location_remote()


function control_location(_, playercolor, _)
    Global.call('animate_button', {button=self})
    local is_solo          = false
    if getObjectFromGUID("1a78a6").getGMNotes() == "solo" then
        is_solo            = true
    end
    local location_zone    = getObjectFromGUID("65beaa")
    local drop_rotation    = playerarea_color == "Blue" and {0.00, 270.00, 0.00} or {0.00, 90.00, 0.00}
    local oppose_rotation  = playerarea_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00}
    if is_solo then
        drop_rotation      = playerarea_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00}
    end
    local oppose_rotation  = playerarea_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00}
    local oppose_color     = playerarea_color == "Blue" and "Red" or "Blue"
    local away_team_drop   = playerarea_color == "Blue" and {-28.75, 2.00, 6.30} or {28.75, 2.00, -6.30}
    local oppose_team_drop = playerarea_color == "Blue" and {28.75, 2.00, -6.30} or {-28.75, 2.00, 6.30}
    local location_drop    = playerarea_color == "Blue" and {-21.50, 1.00, 2.47} or {21.50, 1.00, -2.47}
    local check_zone       = playerarea_color == "Blue" and getObjectFromGUID("eaec24") or getObjectFromGUID("817308")
    local oppose_zone      = playerarea_color == "Blue" and getObjectFromGUID("817308") or getObjectFromGUID("eaec24")
    local oppose_count     = 0
    for _, object in pairs(check_zone.getObjects()) do
        -- return away teams
        if object.hasTag('away_' .. string.lower(playerarea_color)) then
            object.setRotation(drop_rotation)
            object.setPositionSmooth(away_team_drop, false, false)
        -- return ships
        elseif object.hasTag('snap_ship') then
            getObjectFromGUID("82424c").call('dismiss_ship', {ship=object})
        end
    end
    for _, object in pairs(oppose_zone.getObjects()) do
        -- return opposing away teams
        if object.hasTag('away_' .. string.lower(oppose_color)) then
            object.setRotation(oppose_rotation)
            object.setPositionSmooth(oppose_team_drop, false, false)
            oppose_count = oppose_count + 1
        -- return opposing ships to cards
        elseif object.hasTag('snap_ship') then
            local ship       = object
            oppose_count     = oppose_count + 1
            if ship ~= nil then
                getObjectFromGUID("82424c").call("dismiss_ship", {ship=ship})
            else
                broadcastToColor("Deployed ship card for " .. ship_name .. " was not found! Dismiss ship manually.", oppose_color, "Orange")
            end
        end
    end
    -- take controlled location
    local controlled_location  = nil
    local replacement_location = nil
    local location_zone  = getObjectFromGUID(playerarea_color == "Blue" and "2c336e" or "77d0cb")
    local location_slots = {false, false, false, false, false, false, false}
    local placement      = playerarea_color == "Blue" and {
        {-30.00, 0.96, 2.46},
        {-30.00, 0.96, -1.46},
        {-30.00, 0.96, -5.37},
        {-30.00, 0.96, -9.29},
        {-30.00, 0.96, -13.21},
        {-30.00, 0.96, -17.13},
        {-30.00, 0.96, -21.04},
    } or
    {
        {30.00, 0.96, -2.46},
        {30.00, 0.96, 1.46},
        {30.00, 0.96, 5.37},
        {30.00, 0.96, 9.29},
        {30.00, 0.96, 13.21},
        {30.00, 0.96, 17.13},
        {30.00, 0.96, 21.04},
    }
    for i = 1, 7 do
        for _, object in pairs(location_zone.getObjects()) do
            if object.tag == "Card" then
                local position = object.getPosition()
                if (position.z > 1.96 and position.z < 2.96) or (position.z < -1.96 and position.z > -2.96) then
                    location_slots[1] = true
                elseif (position.z > -1.96 and position.z < -0.96) or (position.z < 1.96 and position.z > 0.96) then
                    location_slots[2] = true
                elseif (position.z > -5.87 and position.z < -4.87) or (position.z < 5.87 and position.z > 4.87) then
                    location_slots[3] = true
                elseif (position.z >  -9.79 and position.z < -8.79) or (position.z < 9.79 and position.z > 8.79) then
                    location_slots[4] = true
                elseif (position.z > -13.71 and position.z < -12.71) or (position.z < 13.71 and position.z > 12.71) then
                    location_slots[5] = true
                elseif (position.z > -17.63 and position.z < -16.63) or (position.z < 17.63 and position.z > 16.63) then
                    location_slots[6] = true
                elseif (position.z > -21.54 and position.z < -20.54) or (position.z < 21.54 and position.z > 20.54) then
                    location_slots[7] = true
                end
            end
        end
    end
    local next_free_location_slot = 0
    for i = 1, 7 do
        if location_slots[i] == false then
            next_free_location_slot = i
            break
        end
    end
    if next_free_location_slot ~= 0 then
        location_drop = placement[next_free_location_slot]
    end
    for _, object in pairs(location_checkzone.getObjects()) do
        if object.tag == "Card" then
            object.setRotation(drop_rotation)
            object.setPositionSmooth(location_drop, false, false)
            controlled_location = object.getName()
        end
    end
    -- replace location
    local location_deck        = nil
    local new_location         = nil
    local replacement_location = nil
    for _, object in pairs(getObjectFromGUID("97d9f0").getObjects()) do
        if object.tag == "Deck" then
            new_location = object.takeObject({rotation={0.00, 180.00, 0.00}})
            new_location.setPositionSmooth(replace_drop_loc, false, false)
            replacement_location = new_location.getName()
        elseif object.tag == "Card" then
            object.setRotation({0.00, 180.00, 0.00})
            object.setPositionSmooth(replace_drop_loc, false, false)
            replacement_location = object.getName()
        end
    end
    -- broadcast
    if controlled_location ~= nil and replacement_location ~= nil then
        if Player["Red"].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString("Red"):toHex() .. "]" .. Player["Red"].steam_name .. "[-] has taken control of " .. controlled_location .. ", which has been replaced in the Neutral Zone with " .. replacement_location .. ".", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Red" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString("Red"):toHex() .. "]" .. "Red" .. " " .. player_str .. "[-] has taken control of " .. controlled_location .. ", which has been replaced in the Neutral Zone with " .. replacement_location .. ".", "White")
        end
    elseif controlled_location ~= nil and replacement_location == nil then
        if Player["Red"].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString("Red"):toHex() .. "]" .. Player["Red"].steam_name .. "[-] has taken control of " .. controlled_location .. ", there are no remaining locations to replace it with.", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Red" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString("Red"):toHex() .. "]" .. "Red" .. " " .. player_str .. "[-] has taken control of " .. controlled_location .. ", there are no remaining locations to replace it with.", "White")
        end
    end
    local check_if_cadet = false
    for _, object in pairs(getObjectFromGUID("090f7a").getObjects()) do
        if object.getName() == "Solo Cadet Practice Deck" or object.getName() == "Solo Cadet Practice 2" then
            check_if_cadet = true
        end
    end
    if oppose_count > 0 and not check_if_cadet then
        local consolation_counter = getObjectFromGUID(playerarea_color == "Blue" and "9a5066" or "d96ce2")
        Wait.time(function()
        local oppose_color = playerarea_color == "Blue" and "Red" or "Blue"
        if Player[oppose_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(oppose_color):toHex() .. "]" .. Player[oppose_color].steam_name .. "[-] takes " .. oppose_count .. " Glory, 1 for every dismissed ship or returned away team!.", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString(oppose_color):toHex() .. "]" .. oppose_color .. " " .. player_str .. "[-] takes " .. oppose_count .. " Glory, 1 for every dismissed ship or returned away team!", "White")
        end
        local glory_on_stardate_count = 0
        for _, object in pairs(getObjectFromGUID("338aa7").getObjects()) do
            if object.getName() == "Glory Token" then
                glory_on_stardate_count = glory_on_stardate_count + 1
            end
        end
        if glory_on_stardate_count >= oppose_count and oppose_count > 0 then
            for i = 1, oppose_count do
                local wait_timer = 0
                if i == 2 and oppose_count > 1 then
                    wait_timer = .25
                elseif i == 3 and oppose_count > 2 then
                    wait_timer = .50
                elseif i == 4 and oppose_count > 3 then
                    wait_timer = .75
                elseif i == 5 and oppose_count > 4 then
                    wait_timer = 1.00
                elseif i == 6 and oppose_count > 5 then
                    wait_timer = 1.25
                elseif i == 7 and oppose_count > 6 then
                    wait_timer = 1.50
                end
                Wait.time(function()
                consolation_counter.call('add_glory')
                end, wait_timer)
            end
        elseif glory_on_stardate_count < oppose_count then
            for i = 1, glory_on_stardate_count do
                local wait_timer = 0
                if i == 2 then
                    wait_timer = .25
                elseif i == 3 then
                    wait_timer = .50
                elseif i == 4 then
                    wait_timer = .75
                elseif i == 5 then
                    wait_timer = 1.00
                elseif i == 6 then
                    wait_timer = 1.25
                elseif i == 7 then
                    wait_timer = 1.50
                end
                Wait.time(function()
                consolation_counter.call('add_glory')
                if i == glory_on_stardate_count then
                    broadcastToAll("Pausing Glory Allocation to refresh Stardate Card.", "Yellow")
                end
                end, wait_timer)
            end
            local diff_count = oppose_count - glory_on_stardate_count
            Wait.time(function()
            for i = 1, diff_count do
                local wait_timer = 0
                if i == 2 then
                    wait_timer = .25
                elseif i == 3 then
                    wait_timer = .50
                elseif i == 4 then
                    wait_timer = .75
                elseif i == 5 then
                    wait_timer = 1.00
                elseif i == 6 then
                    wait_timer = 1.25
                elseif i == 7 then
                    wait_timer = 1.50
                end
                Wait.time(function()
                consolation_counter.call('add_glory')
                end, wait_timer)
            end
            end, 3)
        end
        end, 1)
    end
end -- end control_location()
