playerarea_color = "Blue"

function onLoad()
    create_button()
end -- end onLoad()

function create_button()
    self.createButton({
        click_function = "report_cleanup",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will report all currently in play Clean-Up Step cards for the " .. playerarea_color .. " player.\n\nRight clicking will momentarily highlight Clean-Up Step cards in play without broadcasting.",
    })
end -- end create_button()


function report_cleanup(_, _, alt_click)
    -- make alt_click just highlight the cards
    Global.call('animate_button', {button=self})
    local check_zones = playerarea_color == "Blue" and {
        getObjectFromGUID("a9ca57"),
        getObjectFromGUID("2c336e"),
        getObjectFromGUID("fc7f21"),
        getObjectFromGUID("e54fe3"),
    } or
    {
        getObjectFromGUID("818a7e"),
        getObjectFromGUID("77d0cb"),
        getObjectFromGUID("5103b2"),
        getObjectFromGUID("586a2e"),
    }
    local match_cards = {}
    for i = 1, 4 do
        for _, object in pairs(check_zones[i].getObjects()) do
            if object.hasTag('cleanup') then
                object.highlightOn(playerarea_color)
                table.insert(match_cards, object)
                Wait.time(function() object.highlightOff() end, 5)
            end
        end
    end
    if not alt_click and #match_cards > 0 then
        if Player[playerarea_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. Player[playerarea_color].steam_name .. "[-] - Current in play Clean-Up Step Cards:", "White")
        else
            broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. " Player[-] - Current in play Clean-Up Step Cards:", "White")
        end
        for i = 1, #match_cards do
            broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]* [-] " .. match_cards[i].getName(), "White")
        end
    end
end -- end report_cleanup()
