playerarea_color = "Blue"
token_bag        = getObjectFromGUID("2b6501")
token_rot        = {0.00, 120.00, 0.00}

function onLoad()
    create_button()
end -- end onLoad()

function create_button()
    self.createButton({
        click_function = "pull_action_token",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 480,
        height         = 480,
        scale          = {2.1, 2.1, 2.1},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Click to summon an extra action token. The summoned action token will be destroyed on Refresh For End Turn button click.",
    })
end -- end create_button()


function pull_action_token()
    Global.call('animate_button', {button=self})
    local drop_loc = self.getPosition()
    drop_loc.y     = 6.00
    local token = token_bag.takeObject({rotation=token_rot})
    token.setPosition(drop_loc)
    if Player[playerarea_color].steam_name ~= nil then
        broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. Player[playerarea_color].steam_name .. "[-] has generated +1 Extra Action Token. ", "White")
    else
        broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. " Player[-] has generated +1 Extra Action Token. ", "White")
    end
end -- end pull_action_token()
