function onLoad()
    self.setGMNotes('enabled')
    self.createButton({
        click_function = "disable_promo",
        function_owner = self,
        label          = "✔",
        position       = {3.40, 1.01, 0.0},
        width          = 350,
        height         = 350,
        font_size      = 300,
        font_color     = {49/255, 76/255, 95/255, 1},
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, 1},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Click and uncheck this button to exclude promotional cards during game setup.",
    })
end -- end onLoad()


function remove_buttons(object)
    local buttons = object.getButtons()
    if #buttons > 0 then
        for k = #buttons, 1, -1 do
            if buttons[k].index ~= nil then
                object.removeButton(buttons[k].index)
            end
        end
    end
end -- end remove_buttons()


function enable_promo()
    self.setGMNotes('enabled')
    self.clearButtons()
    self.createButton({
        click_function = "disable_promo",
        function_owner = self,
        label          = "✔",
        position       = {3.40, 1.01, 0.0},
        width          = 350,
        height         = 350,
        font_size      = 300,
        font_color     = {49/255, 76/255, 95/255, 1},
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, 1},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Click and uncheck this button to exclude promotional cards during game setup.",
    })
end -- end enable_promo()


function disable_promo()
    self.setGMNotes('disabled')
    self.clearButtons()
    self.createButton({
        click_function = "enable_promo",
        function_owner = self,
        label          = "",
        position       = {3.40, 1.01, 0.0},
        width          = 350,
        height         = 350,
        font_size      = 300,
        font_color     = {49/255, 76/255, 95/255, 1},
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, 1},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Click and check this button to include promotional cards during game setup.",
    })
end -- end disable_promo()
