card_zone = getObjectFromGUID("13c103")
suit      = "Incident"

function onLoad()
    create_button()
end -- end onLoad()

function create_button()
    self.createButton({
        click_function = "take_card",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will take an Incident. \n\nIf vs. a solo bot, right clicking this button will take an Incident for the bot.",
    })
end -- end create_button()


function take_card(_, playercolor, alt_click)
    Global.call('animate_button', {button=self})
    if playercolor == "Blue" or playercolor == "Red" then
        local solo_check  = (playercolor == "Blue" and getObjectFromGUID("1a78a6").getGMNotes() or getObjectFromGUID("23bed4").getGMNotes())
        local is_solo     = solo_check == "solo" and true or false
        if alt_click and is_solo then
            if playercolor == "Blue" then
                playercolor = "Red"
            elseif playercolor == "Red" then
                playercolor = "Blue"
            end
        elseif alt_click and not is_solo then
            alt_click = false
        end
        local loc_take    = {}
        local rot_take    = {}
        if not alt_click then
            loc_take    = (playercolor == "Blue" and {-54.00, 3.00, 0.00}) or playercolor == "Red" and {54.00, 3.00, 0.00}
            rot_take    = (playercolor == "Blue" and {0.00, 270.00, 0.00}) or playercolor == "Red" and {0.00, 90.00, 0.00}
        else
            rot_take    = (playercolor == "Blue" and {0.00, 90.00, 180.00}) or playercolor == "Red" and {0.00, 270.00, 180.00}
            loc_take    = (playercolor == "Blue" and {-44.50, 3.00, 7.00}) or playercolor == "Red" and {44.50, 3.00, -7.00}
        end
        local card        = nil
        local card_found  = false
        for _, object in pairs(card_zone.getObjects()) do
            if object.hasTag('suit_' .. string.lower(suit)) then
                if object.tag == "Deck" then
                    card = object.takeObject()
                elseif object.tag == "Card" then
                    card = object
                end
                card.setRotation(rot_take)
                card.setPositionSmooth(loc_take, false, false)
                card_found = true
            end
        end
        if Player[playercolor].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. Player[playercolor].steam_name .. "[-][" .. Color.fromString("White"):toHex() .. "] has taken an[-] Incident[" .. Color.fromString("White"):toHex() .. "].", "Red")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            if player_str == "Player" then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Player[-][" .. Color.fromString("White"):toHex() .. "] has taken an[-] Incident[" .. Color.fromString("White"):toHex() .. "].", "Red")
            elseif player_str == "Bot" then
                broadcastToAll("[" .. Color.fromString(playercolor):toHex() .. "]" .. playercolor .. " Bot[-][" .. Color.fromString("White"):toHex() .. "] has taken an[-] Incident[" .. Color.fromString("White"):toHex() .. "].", "Red")
            end
        end
        if not card_found then
            broadcastToAll("Burn initiated!", "Red")
            return nil
        end
        card_found = false
        for _, object in pairs(card_zone.getObjects()) do
            if object.hasTag('suit_' .. string.lower(suit)) then
                card_found = true
            end
        end
        if not card_found then
            broadcastToAll("Burn initiated!", "Red")
        end
    end
end -- end junk_card()
