playerarea_color = "Red"

function onLoad()
    create_button()
end -- end onLoad()

function create_button()
    self.createButton({
        click_function = "discard_hand",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, -0.01},
        width          = 865,
        height         = 435,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .3},
        hover_color    = {1, 1, 1, .6},
        tooltip        = "Clicking this button will discard all cards in hand. (Usually used on turn end)",
    })
end -- end create_button()


function discard_hand()
    Global.call('animate_button', {button=self})
    getObjectFromGUID("ab8b38").call('discard_hand', {color=playerarea_color})
end -- end discard_hand()
