function onLoad()
    self.createButton({
        click_function = "open_bag",
        function_owner = self,
        label          = "",
        position       = {0, 0.17, 0.02},
        rotation       = {0, 180, 0},
        width          = 450,
        height         = 450,
        scale          = {2.3, 2.3, 2.3},
        color          = {1, 1, 1, .0},
        hover_color    = {1, 1, 1, .2},
        tooltip        = "Click to search Captain's Log.",
    })
end -- end onLoad()


function open_bag(_, playercolor, _)
    self.Container.search(playercolor)
end -- end open_bag()


function create_counter_button(bag_count)
    self.createButton({
        click_function = "open_bag",
        function_owner = self,
        label          = bag_count,
        position       = {0.45, 0.17, 0.45},
        width          = 125,
        height         = 125,
        font_size      = 90,
        scale          = {2.3, 2.3, 2.3},
        color          = {31/255, 136/255, 255/255, 255},
        hover_color    = {31/255, 136/255, 255/255, 255},
        font_color     = {1, 1, 1, 1},
        tooltip        = "There are " .. bag_count .. " cards logged here.",
    })
end -- end create_counter_button()


function update_buttons()
    -- get card in bag count
    local bag_objects = self.getObjects()
    local bag_count   = #bag_objects
    -- if bag count == 1, remove buttons & recreate counter button / search button
    local buttons = self.getButtons()
    if bag_count > 0 then
        if buttons ~= nil then
            self.clearButtons()
        end
        create_counter_button(bag_count)
    elseif bag_count == 0 then
        if buttons ~= nil then
            self.clearButtons()
        end
    end
end -- end update_buttons()


function onObjectEnterContainer(container,  object)
    if container == self and object.tag == "Card" then
        update_buttons()
    elseif container == self and object.tag ~= "Card" then
        broadcastToColor("Captian's Log only perform it's scripted functionality for single card objects. Removing non-card object.", "Blue", "Orange")
        local errant_object = self.takeObject()
        local position = self.getPosition()
        position.y = position.y + .76
        errant_object.setPosition(position)
        errant_object.setPositionSmooth({-21.50, 1.50, 2.47}, false, false)
    end
end -- end onObjectEnterContainer()


function onObjectLeaveContainer(container, object)
    if container == self then
        update_buttons()
    end
end -- end onObjectLeaveContainer()
