MIN_VALUE = 0
MAX_VALUE = 999
player_color = "Blue"

function onload(saved_data)
    val = 0
    if saved_data ~= "" then
        local loaded_data = JSON.decode(saved_data)
        if loaded_data ~= nil then
            val = loaded_data[1]
        end
    end
    create_all()
end -- end function onload()


function update_save()
    local data_to_save = {val}
    saved_data = JSON.encode(data_to_save)
    self.script_state = saved_data
end -- end function update_save()


function create_all()
    h_color = {31/255, 136/255, 255/255, .4}
    f_color = {1, 1, 1, 255}
    self.createButton({
        label          = tostring(val),
        click_function = "add_subtract",
        function_owner = self,
        position       = {0.00, -0.01, -.80},
        height         = 1000,
        width          = 1000,
        font_size      = 1100,
        scale          = {x=.36, y=.36, z=.36},
        font_color     = f_color,
        hover_color    = h_color,
        color          = {31/255, 136/255, 255/255, 255}
    })
end -- end function create_all()

function remove_all()
      self.removeButton(0)
end -- end function remove_all()

function reload_all()
      remove_all()
      create_all()
      update_save()
end -- end function reload_all()

function add_subtract(_obj, _color, alt_click)
    mod = alt_click and -1 or 1
    new_value = math.min(math.max(val + mod, MIN_VALUE), MAX_VALUE)
    if val ~= new_value then
        val = new_value
        update_val()
        update_save()
    end
    local captain_zone           = getObjectFromGUID("75465f")
    local captain_pad            = getObjectFromGUID("997491")
    for _, object in pairs(captain_zone.getObjects()) do
        if string.find(object.getName(), "Crew Board") and object ~= captain_pad then
            captain_card_name    = object.getName()
        end
    end
    local captain_name           = nil
    local split_name             = {}
    if captain_card_name        ~= nil then
        for str in string.gmatch(captain_card_name,  "%S+") do
            table.insert(split_name, str)
        end
    end
    captain_name = split_name[1]
    if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
        UI.setAttribute(string.lower(player_color) .. "_hum_dilithium", "text", val)
    elseif captain_name == "Shran" then
        UI.setAttribute(string.lower(player_color) .. "_and_dilithium", "text", val)
    elseif captain_name == "Sela" then
        UI.setAttribute(string.lower(player_color) .. "_rom_dilithium", "text", val)
    elseif captain_name == "Koloth" then
        UI.setAttribute(string.lower(player_color) .. "_kli_dilithium", "text", val)
    end
    if alt_click then
        if Player[player_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(player_color):toHex() .. "]" .. Player[player_color].steam_name .. "[-] has removed -1 Dilithium from their counter.", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString(player_color):toHex() .. "]" .. player_color .. " " .. player_str .. "[-] has removed -1 Dilithium from their counter.", "White")
        end
    else
        if Player[player_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(player_color):toHex() .. "]" .. Player[player_color].steam_name .. "[-] has gained +1 Dilithium to their counter.", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString(player_color):toHex() .. "]" .. player_color .. " " .. player_str .. "[-] has gained +1 Dilithium to their counter.", "White")
        end
    end
end -- end function add_subtract()

function subtract()
new_value = math.min(math.max(val -1, MIN_VALUE), MAX_VALUE)
if val ~= new_value then
    val = new_value
    update_val()
    update_save()
end
end -- end function subtract()

function update_val()
  self.editButton({
      index = 0,
      label = tostring(val),
  })
end -- end function update_val()

function set_val(value)
  val = value
  update_val()
  update_save()
end -- send function set_val()

function reset_val()
  val = 0
  update_val()
  update_save()
end -- end function set_val()




function increase()
  add_subtract(_, _, false)
end -- end increase()

function decrease()
  add_subtract(_, _, true)
end -- end decrease()
