MIN_VALUE = 0
MAX_VALUE = 999

function onload(saved_data)
    val = 0
    if saved_data ~= "" then
        local loaded_data = JSON.decode(saved_data)
        if loaded_data ~= nil then
            val = loaded_data[1]
        end
    end
end -- end function onload()


function update_save()
    local data_to_save = {val}
    saved_data = JSON.encode(data_to_save)
    self.script_state = saved_data
end -- end function update_save()


function create_all(args)
    local color        = args.color
    local h_color      = args.h_color
    local f_color      = {1, 1, 1, 255}
    self.createButton({
        label          = tostring(val),
        click_function = "add_subtract",
        function_owner = self,
        position       = {0.00, -0.09, -4.00},
        height         = 1000,
        width          = 1000,
        font_size      = 1100,
        scale          = {x=1.8, y=1.8, z=1.8},
        font_color     = f_color,
        hover_color    = h_color,
        color          = color,
        tooltip        = "Stardate Card Glory Count\n\nThis counter should usually be automatic, but it may also be used to manually adjust the Stardate Card Glory count if required. Left click to increment, Right click to decrement.\n(Glory on Stardate Card is not interactable, players should use 'Add Resource' buttons or their Glory counters to manipulate Stardate Glory!)"
    })
end -- end function create_all()


function remove_all()
    self.removeButton(0)
end -- end function remove_all()


function reload_all()
    remove_all()
    create_all()
    update_save()
end -- end function reload_all()

function add_subtract(_obj, _color, alt_click)
    mod = alt_click and -1 or 1
    new_value = math.min(math.max(val + mod, MIN_VALUE), MAX_VALUE)

    -- if adding, pull glory from bag and place at some spot
    -- if removing, grab first glory found in zone and return to bag
    if not alt_click then
        local new_token = getObjectFromGUID("263bae").takeObject()
        new_token.interactable = false
        new_token.setPositionSmooth({-11.00, 4.00, 5.50}, false, false)
    else
        for _, object in pairs(getObjectFromGUID("338aa7").getObjects()) do
            if object.getName() == "Glory Token" then
                getObjectFromGUID("263bae").putObject(object)
                return
            end
        end
    end
end -- end function add_subtract()

function subtract()
  new_value = math.min(math.max(val -1, MIN_VALUE), MAX_VALUE)
  if val ~= new_value then
      val = new_value
      update_val()
      update_save()
  end
end -- end function subtract()

function update_val()
    self.editButton({
        index = 0,
        label = tostring(val),
    })
end -- end function update_val()

function set_val(value)
    val = value
    update_val()
    update_save()
end -- send function set_val()

function reset_val()
    val = 0
    update_val()
    update_save()
end -- end function set_val()

-- need to check for glory token entering or leaving zone, update
function onObjectEnterZone(zone, enter_object)
    if zone == getObjectFromGUID("338aa7") and enter_object.getName() == "Glory Token" then
        local glory_count = 0
        for _, object in pairs(getObjectFromGUID("338aa7").getObjects()) do
            if object.getName() == "Glory Token" then
                glory_count = glory_count + 1
            end
        end
        set_val(glory_count)
    end
end -- end onObjectEnterZone()

function onObjectLeaveZone(zone, enter_object)
    if zone == getObjectFromGUID("338aa7") and enter_object.getName() == "Glory Token" then
        local glory_count = 0
        for _, object in pairs(getObjectFromGUID("338aa7").getObjects()) do
            if object.getName() == "Glory Token" then
                glory_count = glory_count + 1
            end
        end
        set_val(glory_count)
    end
end -- end onObjectLeaveZone()
