function onObjectEnterContainer(bag, object)
    if bag == self and object.getName() == "Glory Token" then
        local counter     = getObjectFromGUID("9a5066")
        local current_val = counter.getVar('val')
        counter.call('set_val', current_val + 1)
        local captain_zone           = getObjectFromGUID("75c041")
        local captain_pad            = getObjectFromGUID("28a24b")
        for _, object in pairs(captain_zone.getObjects()) do
            if string.find(object.getName(), "Crew Board") and object ~= captain_pad then
                captain_card_name    = object.getName()
            end
        end
        local captain_name           = nil
        local split_name             = {}
        if captain_card_name        ~= nil then
            for str in string.gmatch(captain_card_name,  "%S+") do
                table.insert(split_name, str)
            end
        end
        captain_name = split_name[1]
        if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
            UI.setAttribute("red_hum_glory", "text", current_val + 1)
        elseif captain_name == "Shran" then
            UI.setAttribute("red_and_glory", "text", current_val + 1)
        elseif captain_name == "Sela" then
            UI.setAttribute("red_rom_glory", "text", current_val + 1)
        elseif captain_name == "Koloth" then
            UI.setAttribute("red_kli_glory", "text", current_val + 1)
        end
    end
end -- end onObjectEnterContainer()
