MIN_VALUE = 0
MAX_VALUE = 999

function onload(saved_data)
    val = 0
    if saved_data ~= "" then
        local loaded_data = JSON.decode(saved_data)
        if loaded_data ~= nil then
            val = loaded_data[1]
        end
    end
end -- end function onload()


function update_save()
    local data_to_save = {val}
    saved_data = JSON.encode(data_to_save)
    self.script_state = saved_data
end -- end function update_save()


function onObjectEnterZone(zone, enter_object)
    if enter_object == self and (zone == getObjectFromGUID("a9ca57") or zone == getObjectFromGUID("818a7e")) then
        local is_solo = false
        if zone == getObjectFromGUID("a9ca57") and getObjectFromGUID("23bed4").getGMNotes() == "solo" or
        zone == getObjectFromGUID("818a7e") and getObjectFromGUID("1a78a6").getGMNotes() == "solo" then
            is_solo = true
        end
        if not is_solo then
            create_all()
            create_recrystal_button()
        end
    end
end -- end onObjectEnterZone()


function onObjectLeaveZone(zone, leave_object)
    if leave_object == self and (zone == getObjectFromGUID("a9ca57") or zone == getObjectFromGUID("818a7e")) then
        self.clearButtons()
        remove_recrystal_button()
    end
end



function create_all()
    local color   = nil
    local h_color = nil
    local f_color = {1, 1, 1, 255}
    for _, object in pairs(getObjectFromGUID("a9ca57").getObjects()) do
        if object == self then
            color   = {31/255, 136/255, 255/255, .6}
            h_color = {31/255, 136/255, 255/255, .4}
        end
    end
    for _, object in pairs(getObjectFromGUID("818a7e").getObjects()) do
        if object == self then
            color   = {219/255, 26/255, 24/255, .6}
            h_color = {219/255, 26/255, 24/255, .4}
        end
    end
    if color == nil then
        color   = "White"
        h_color = "White"
        f_color = "Black"
    end
    self.createButton({
        label          = tostring(val),
        click_function = "add_subtract",
        function_owner = self,
        position       = {0.70, 0.30, -1.15},
        rotation       = {0.00, 0.00, 0.00},
        height         = 350,
        width          = 350,
        font_size      = 300,
        scale          = {x=1.0, y=1.0, z=1.0},
        font_color     = f_color,
        hover_color    = h_color,
        color          = color
    })
end -- end function create_all()

function remove_all()
      self.removeButton(0)
end -- end function remove_all()

function reload_all()
      remove_all()
      create_all()
      update_save()
end -- end function reload_all()

function add_subtract(_obj, _color, alt_click)
    local p_color = nil
    for _, object in pairs(getObjectFromGUID("a9ca57").getObjects()) do
        if object == self then
            p_color = "Blue"
        end
    end
    for _, object in pairs(getObjectFromGUID("818a7e").getObjects()) do
        if object == self then
            p_color = "Red"
        end
    end
    if color == nil then
        p_color = "White"
    end
    mod = alt_click and -1 or 1
    new_value = math.min(math.max(val + mod, MIN_VALUE), MAX_VALUE)
    if val ~= new_value then
        val = new_value
        update_val()
        update_save()
    end
    if alt_click then
        if Player[p_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(p_color):toHex() .. "]" .. Player[p_color].steam_name .. "[-] has removed -1 Inert Dilithium from their Card.", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(p_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString(p_color):toHex() .. "]" .. p_color .. " Burnham " .. player_str .. "[-] has removed -1 Inert Dilithium from their Card.", "White")
        end
    else
        if Player[p_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(p_color):toHex() .. "]" .. Player[p_color].steam_name .. "[-] has gained +1 Inert Dilithium to their Card.", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(p_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString(p_color):toHex() .. "]" .. p_color .. " Burnham " .. player_str .. "[-] has gained +1 Inert Dilithium to their Card.", "White")
        end
    end
end -- end function add_subtract()

function subtract()
  new_value = math.min(math.max(val -1, MIN_VALUE), MAX_VALUE)
  if val ~= new_value then
      val = new_value
      update_val()
      update_save()
  end
end -- end function subtract()

function update_val()
    self.editButton({
        index = 0,
        label = tostring(val),
    })
end -- end function update_val()

function set_val(value)
    val = value
    update_val()
    update_save()
end -- send function set_val()

function reset_val()
    val = 0
    update_val()
    update_save()
end -- end function set_val()

function increase()
    add_subtract(_, _, false)
end -- end increase()

function decrease()
    add_subtract(_, _, true)
end -- end decrease()


function create_recrystal_button()
    self.UI.show('recrystallize')
end -- end create_deploy_button()


function remove_recrystal_button()
    self.UI.hide('recrystallize')
end -- end remove_deploy_button()


function recrystallize()
    local color   = nil
    local counter = nil
    for _, object in pairs(getObjectFromGUID("a9ca57").getObjects()) do
        if object == self then
            color   = "Blue"
            counter = getObjectFromGUID("a3ec59")
        end
    end
    for _, object in pairs(getObjectFromGUID("818a7e").getObjects()) do
        if object == self then
            color   = "Red"
            counter = getObjectFromGUID("f40879")
        end
    end
    if color == nil then
        return nil
    end
    if val == 0 then
        broadcastToColor("No Inert Dilithium is available to Recrystallize.", color, "Orange")
        return nil
    end
    decrease()
    local counter_val = counter.getVar('val')
    counter.call('set_val', counter_val + 1)
    UI.setAttribute(string.lower(color) .. "_hum_dilithium", "text", counter_val + 1)
    if Player[color].steam_name ~= nil then
        broadcastToAll("[" .. Color.fromString(color):toHex() .. "]" .. Player[color].steam_name .. "[-] has Recrystallized +1 Dilithium.", "White")
    else
        broadcastToAll("[" .. Color.fromString(color):toHex() .. "]" .. color .. " Burnham[-] has Recrystallized +1 Dilithium.", "White")
    end
end -- end recrystallize()
