-- -- **** XML HELPERS ****

-- function close_ui_blue()
--     UI.hide("blue_andorian_panel")
--     UI.hide("blue_klingon_panel")
--     UI.hide("blue_romulan_panel")
--     UI.hide("blue_starfleet_panel")
--     UI.hide("ui_hide_blue")
--     UI.hide("ui_show_blue")
--     UI.hide("bot_controls")
-- end
-- function close_ui_red()
--     UI.hide("red_andorian_panel")
--     UI.hide("red_klingon_panel")
--     UI.hide("red_romulan_panel")
--     UI.hide("red_starfleet_panel")
--     UI.hide("ui_hide_red")
--     UI.hide("ui_show_red")
--     UI.hide("bot_controls")
-- end


-- function hide_ui_blue()
--     UI.hide("blue_andorian_panel")
--     UI.hide("blue_klingon_panel")
--     UI.hide("blue_romulan_panel")
--     UI.hide("blue_starfleet_panel")
--     UI.hide("ui_hide_blue")
--     UI.hide("bot_controls")
--     UI.setAttribute("ui_show_blue", "active", "True")
-- end
-- function hide_ui_red()
--     UI.hide("red_andorian_panel")
--     UI.hide("red_klingon_panel")
--     UI.hide("red_romulan_panel")
--     UI.hide("red_starfleet_panel")
--     UI.hide("ui_hide_red")
--     UI.hide("bot_controls")
--     UI.setAttribute("ui_show_red", "active", "True")
-- end


-- function show_ui_blue()
--     local captain_zone           = getObjectFromGUID("75465f")
--     local captain_pad            = getObjectFromGUID("997491")
--     for _, object in pairs(captain_zone.getObjects()) do
--         if string.find(object.getName(), "Crew Board") and object ~= captain_pad then
--             captain_card_name    = object.getName()
--         end
--     end
--     local captain_name           = nil
--     local split_name             = {}
--     if captain_card_name        ~= nil then
--         for str in string.gmatch(captain_card_name,  "%S+") do
--             table.insert(split_name, str)
--         end
--     end
--     captain_name = split_name[1]
--     if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
--         UI.setAttribute("blue_starfleet_panel", "active", "true")
--     elseif captain_name == "Shran" then
--         UI.setAttribute("blue_andorian_panel", "active", "true")
--     elseif captain_name == "Sela" then
--         UI.setAttribute("blue_romulan_panel", "active", "true")
--     elseif captain_name == "Koloth" then
--         UI.setAttribute("blue_klingon_panel", "active", "true")
--     end
--     UI.hide("ui_show_blue")
--     UI.show("ui_hide_blue")
--     if getObjectFromGUID("1a78a6").getGMNotes() == "solo" then
--         UI.show("bot_controls")
--     end
-- end
-- function show_ui_red()
--     local captain_zone           = getObjectFromGUID("75c041")
--     local captain_pad            = getObjectFromGUID("28a24b")
--     for _, object in pairs(captain_zone.getObjects()) do
--         if string.find(object.getName(), "Crew Board") and object ~= captain_pad then
--             captain_card_name    = object.getName()
--         end
--     end
--     local captain_name           = nil
--     local split_name             = {}
--     if captain_card_name        ~= nil then
--         for str in string.gmatch(captain_card_name,  "%S+") do
--             table.insert(split_name, str)
--         end
--     end
--     captain_name = split_name[1]
--     if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
--         UI.setAttribute("red_starfleet_panel", "active", "true")
--     elseif captain_name == "Shran" then
--         UI.setAttribute("red_andorian_panel", "active", "true")
--     elseif captain_name == "Sela" then
--         UI.setAttribute("red_romulan_panel", "active", "true")
--     elseif captain_name == "Koloth" then
--         UI.setAttribute("red_klingon_panel", "active", "true")
--     end
--     UI.hide("ui_show_red")
--     UI.show("ui_hide_red")
--     if getObjectFromGUID("23bed4").getGMNotes() == "solo" then
--         UI.show("bot_controls")
--     end
-- end


-- function broadcast_playerturn()
--     broadcastToAll("This button is currently inactive, it is simply a reminder that it is your turn. Use the 'Add Resource' buttons in the market row to place a resource and end your turn.", "Orange")
--     return
-- end









-- **** SOLO HELPER FUNCTIONS ****

-- function bot_deck_draw(args)
--     local bot_color, _ = get_colors()
--     local deal_count = args.deal_count
--     local bot_deck = get_bot_deck()
--     local deal_rotation = bot_color == "Blue" and {0, 90, 180} or {0, 270, 180}
--     local deal_locations = bot_color == "Blue" and {
--         {-44.50, 0.96, 2.80}, {-44.50, 0.96, -1.07}, {-44.50, 0.96, -4.98},
--         {-44.50, 0.96, -8.90}, {-44.50, 0.96, -12.82},
--     } or {
--         {44.50, 0.96, -2.80}, {44.50, 0.96, 1.07}, {44.50, 0.96, 4.98},
--         {44.50, 0.96, 8.90}, {44.50, 0.96, 12.82},
--     }

--     local deck_count = bot_deck and (bot_deck.tag == "Deck" and #bot_deck.getObjects() or 1) or 0
--     local to_draw_now = math.min(deal_count, deck_count)

--     -- Draw as many as possible from the current deck
--     for i = 1, to_draw_now do
--         local card
--         if bot_deck.tag == "Deck" then
--             card = bot_deck.takeObject({rotation = deal_rotation})
--         else
--             card = bot_deck
--             bot_deck = nil
--         end
--         card.setPositionSmooth(deal_locations[i], false, false)
--     end

--     local remaining = deal_count - to_draw_now

--     if remaining > 0 then
--         -- Disable UI while refreshing
--         UI.setAttribute("bot_controls", "active", "false")
--         Wait.time(function()
--             bot_deck_refresh(to_draw_now + 1, remaining, deal_rotation, deal_locations, deal_count)
--         end, 0.5)
--     else
--         broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] has dealt itself " .. deal_count .. " facedown cards.", "White")
--     end
-- end


-- function bot_deck_discard()
--     UI.hide('bot_discard')

--     local function show_ui_delayed()
--         Wait.time(function() UI.show('bot_discard') end, 1)
--     end

--     local bot_color, _    = get_colors()
--     local discard_zone    = getObjectFromGUID(bot_color == "Blue" and "fbfe84" or "b72553")
--     local discard_pad     = getObjectFromGUID(bot_color == "Blue" and "3accb4" or "34adac")
--     local draw_zone       = getObjectFromGUID(bot_color == "Blue" and "58f8ce" or "5e07a8")
--     local supplement_zone = getObjectFromGUID(bot_color == "Blue" and "30a2e2" or "b75338")
--     local discard_card    = nil
--     local draw_deck       = nil

--     for _, obj in pairs(draw_zone.getObjects()) do
--         if obj.tag == "Deck" then
--             draw_deck = obj
--             break
--         end
--         if obj.tag == "Card" then
--             draw_deck = obj
--             break
--         end
--     end

--     if draw_deck then
--         local deck_count = 0
--         if draw_deck.tag == "Deck" then
--             deck_count = #draw_deck.getObjects()
--         else
--             deck_count = 1
--         end

--         if deck_count > 1 then
--             discard_card = draw_deck.takeObject()
--         else
--             for _, obj in pairs(draw_zone.getObjects()) do
--                 if obj.tag == "Card" then
--                     discard_card = obj
--                     break
--                 end
--             end
--         end

--         if discard_card then
--             discard_card.setRotation(bot_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00})
--             discard_card.setPositionSmooth(bot_color == "Blue" and {-44.57, 1.50, -21.00} or {44.57, 1.50, 21.00}, false, false)
--             broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] has discarded a card off the top of its deck: " .. discard_card.getName(), "White")
--         end

--         show_ui_delayed()

--     else
--         discard_pad.call('refresh_draw_deck', {deal_count=0, alt_click=true})

--         Wait.time(function()
--         local supplement_deck = nil
--         for _, obj in ipairs(supplement_zone.getObjects()) do
--             if obj.tag == "Deck" then
--                 supplement_deck = obj
--                 break
--             elseif obj.tag == "Card" then
--                 discard_card = obj
--                 break
--             end
--         end

--         if supplement_deck then
--             discard_card = supplement_deck.takeObject()
--         elseif not discard_card then
--             discard_card = get_bot_deck().takeObject()
--         end

--         if discard_card then
--             discard_card.setRotation(bot_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00})
--             discard_card.setPositionSmooth(bot_color == "Blue" and {-44.57, 1.50, -21.00} or {44.57, 1.50, 21.00}, false, false)
--             broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] has discarded a card off the top of its deck: " .. discard_card.getName(), "White")
--         end

--         show_ui_delayed()
--         end, 0.5)
--     end
-- end -- end bot_deck_discard()


-- function bot_discard_three()
--     UI.hide('bot_discard_x3')

--     local bot_color, _    = get_colors()
--     local discard_zone    = getObjectFromGUID(bot_color == "Blue" and "fbfe84" or "b72553")
--     local discard_pad     = getObjectFromGUID(bot_color == "Blue" and "3accb4" or "34adac")
--     local draw_zone       = getObjectFromGUID(bot_color == "Blue" and "58f8ce" or "5e07a8")
--     local supplement_zone = getObjectFromGUID(bot_color == "Blue" and "30a2e2" or "b75338")
--     local discard_card    = nil
--     local draw_deck       = nil

--     local discard_count = 0

--     local function show_ui_delayed()
--         Wait.time(function()
--         UI.show('bot_discard_x3')
--         end, 1)
--     end

--     local function discard_single_card()
--         local discard_card = nil
--         for _, obj in pairs(draw_zone.getObjects()) do
--             if obj.type == "Deck" then
--                 discard_card = obj.takeObject()
--                 break
--             elseif obj.type == "Card" then
--                 discard_card = obj
--                 break
--             end
--         end
--         if discard_card ~= nil then
--             discard_card.setRotation(bot_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00})
--             discard_card.setPositionSmooth(bot_color == "Blue" and {-44.57, 1.50, -21.00} or {44.57, 1.50, 21.00}, false, false)
--             broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] has discarded a card: " .. discard_card.getName(), "White")
--         end
--     end

--     local function refresh_and_discard_from_supplemental(callback)
--         Wait.time(function()
--         local checkzone  = getObjectFromGUID(bot_color == "Blue" and "fbfe84" or "b72553")
--         local draw_loc   = {44.50, 1.20, -7.00}
--         local deck       = nil
--         local deck_found = false
--         local is_solo    = getObjectFromGUID(bot_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo"
--         local rotation   = is_solo and {0.00, 270.00, 180.00} or {0.00, 90.00, 180.00}

--         for _, object in pairs(checkzone.getObjects()) do
--             if object.tag == "Deck" or object.tag == "Card" then
--                 deck = object
--                 deck_found = true
--                 deck.setName('Draw Deck')
--                 deck.setRotationSmooth(rotation, false, false)
--                 Wait.time(function()
--                 deck.shuffle()
--                 deck.setPositionSmooth(draw_loc, false, false)
--                 end, 0.5)
--             end
--         end

--         Wait.time(function()
--         local supplement_deck = nil
--         for _, obj in ipairs(supplement_zone.getObjects()) do
--             if obj.type == "Deck" then
--                 supplement_deck = obj
--                 break
--             elseif obj.type == "Card" then
--                 discard_card = obj
--                 break
--             end
--         end

--         if supplement_deck then
--             discard_card = supplement_deck.takeObject()
--         elseif not discard_card then
--             discard_card = get_bot_deck().takeObject()
--         end

--         if discard_card then
--             discard_card.setRotation(bot_color == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00})
--             discard_card.setPositionSmooth(bot_color == "Blue" and {-44.57, 1.50, -21.00} or {44.57, 1.50, 21.00}, false, false)
--             broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] has discarded a card from Supplemental Deck: " .. discard_card.getName(), "White")
--         end

--         discard_count = discard_count + 1
--         if discard_count < 3 then
--             Wait.time(discard_loop, 1)
--         else
--             show_ui_delayed()
--         end
--         end, 0.5)
--         end, 1)
--     end

--     function discard_loop()
--         local draw_deck_empty = true
--         for _, obj in pairs(draw_zone.getObjects()) do
--             if obj.type == "Deck" or obj.type == "Card" then
--                 draw_deck_empty = false
--                 break
--             end
--         end

--         if draw_deck_empty then
--             refresh_and_discard_from_supplemental()
--         else
--             discard_single_card()
--             discard_count = discard_count + 1
--             if discard_count < 3 then
--                 Wait.time(discard_loop, 1)
--             else
--                 show_ui_delayed()
--             end
--         end
--     end

--     discard_loop()
-- end -- end bot_discard_three()


-- function bot_deck_refresh(next_slot, remaining_deal_count, deal_rotation, deal_locations, deal_count)
--     local bot_color, _ = get_colors()
--     local discard_pad = getObjectFromGUID(bot_color == "Blue" and "3accb4" or "34adac")
--     discard_pad.call('refresh_draw_deck', {deal_count=remaining_deal_count, alt_click=true})

--     Wait.time(function()
--     local supplement_zone = getObjectFromGUID(bot_color == "Blue" and "30a2e2" or "b75338")
--     local supplement_deck = nil

--     if supplement_zone then
--         for _, obj in ipairs(supplement_zone.getObjects()) do
--             if obj.tag == "Deck" or obj.tag == "Card" then
--                 supplement_deck = obj
--                 break
--             end
--         end
--     end

--     if supplement_deck then
--         local card
--         if supplement_deck.tag == "Deck" then
--             card = supplement_deck.takeObject({rotation = deal_rotation})
--         else
--             card = supplement_deck
--         end
--         card.setPositionSmooth(deal_locations[next_slot], false, false)
--         next_slot = next_slot + 1
--         remaining_deal_count = remaining_deal_count - 1
--     end
--     end, 0.5)

--     Wait.time(function()
--     local bot_deck = get_bot_deck()

--     if bot_deck then
--         if bot_deck.tag == "Card" then
--             bot_deck.setRotation(deal_rotation)
--             bot_deck.setPositionSmooth(deal_locations[next_slot], false, false)
--             remaining_deal_count = remaining_deal_count - 1
--             next_slot = next_slot + 1
--         elseif bot_deck.tag == "Deck" then
--             local deck_count = #bot_deck.getObjects()
--             local to_draw = math.min(deck_count, remaining_deal_count)
--             for i = 0, to_draw - 1 do
--                 local card = bot_deck.takeObject({rotation = deal_rotation})
--                 card.setPositionSmooth(deal_locations[next_slot + i], false, false)
--             end
--             next_slot = next_slot + to_draw
--             remaining_deal_count = remaining_deal_count - to_draw
--         end

--         if remaining_deal_count > 0 then
--             Wait.time(function()
--             bot_deck_refresh(next_slot, remaining_deal_count, deal_rotation, deal_locations, deal_count)
--             end, 0.5)
--         else
--             broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] has finished dealing " .. deal_count .. " facedown cards.", "White")
--             UI.setAttribute("bot_controls", "active", "true")
--         end
--     else
--         broadcastToAll("[" .. Color.fromString(bot_color):toHex() .. "]Bot[-] attempted to refresh its deck, but the refreshed draw deck is empty.", "White")
--         UI.setAttribute("bot_controls", "active", "true")
--     end
--     end, 1)
-- end








function get_mvp(args)
    local token_ignore = args.token_ignore
    local type         = args.type -- "Bot", "Human"
    local cards        = args.cards
end -- end get_mvp()
