-- object based scripting to handle collision trigger of ship actions

function onCollisionEnter(info)
  if info.collision_object.hasTag('suit_ship') then
    local enterObj = info.collision_object
    local zones = enterObj.getZones()
    for _, zone in pairs(zones) do
      if zone.getName() == "Zone Deploy Ship" or zone.getName() == "Zone Deploy Location" then
        if enterObj.hasTag('suit_ship') then
          if enterObj.hasTag('trait_cloak') and not enterObj.type == "Card" then
            enterObj.highlightOn("Purple")
            enterObj.setDescription('Cloaked')
          end
          local bagShipFigures = Global.call("getObjectbyName", "Ship Figurine Bag")
          bagShipFigures.call("deploy_ship_via_pad", {value=enterObj.getGUID()})
          enterObj.call('create_dismiss_button')
        end
      end
    end
  end
end


function onObjectLeaveZone(zone, leaveObj)
  local playerColor = self.getGMNotes()
  if zone.getName() == "Zone Deploy Ship" or zone.getName() == "Zone Deploy Location" then
    if leaveObj.hasTag('suit_ship') then
      leaveObj.call('remove_dismiss_button', {playerarea_color=playerarea_color})
    end
  end
end
