-- object based scripting to handle collision trigger of ship actions
-- Red Ship Deployment Pad is owner object

function onCollisionEnter(info)
  if info.collision_object.hasTag('suit_ship') then
    local enterObj = info.collision_object
    local zones = enterObj.getZones()
    for _, zone in pairs(zones) do
      if zone.getName() == "Zone Deploy Ship" or zone.getName() == "Zone Deploy Location" then
        if enterObj.hasTag('suit_ship') then
          if enterObj.hasTag('trait_cloak') and not enterObj.type == "Card" then
            enterObj.highlightOn("Purple")
            enterObj.setDescription('Cloaked')
          end
          local bagShipFigures = Global.call("getObjectbyName", "Ship Figurine Bag")
          Global.call("deployShipViaPad", enterObj.getGUID())
          Global.call('createDismissButton', enterObj)
        end
      end
    end
  end
end


function onObjectLeaveZone(zone, leaveObj)
  local playerColor = self.getGMNotes()
  if (zone == getObjectbyNameAndNotes("Zone Deploy Ship", playerColor) or
     zone == getObjectbyNameAndNotes("Zone Deploy Location", playerColor)) and
     leaveObj.hasTag('suit_ship') then
    Global.call("removeDismissButton", leaveObj)
  end
end


function getObjectbyNameAndNotes(objName, objNotes)
  for _, object in pairs(getObjects()) do
    if object.getName() == objName and object.getGMNotes() == objNotes then
      return object
    end
  end
  return nil
end
