MIN_VALUE        = 0
MAX_VALUE        = 15
tracker          = getObjectFromGUID("67d015")
zone             = getObjectFromGUID("75465f")
playerarea_color = "Blue"
track_type       = "Research"
track_color      = {21/255, 151/255, 196/255}
h_color          = {32/255, 59/255, 88/255, .4}
color            = {32/255, 59/255, 88/255, 255}
f_color          = {1, 1, 1, 255}


function onload(saved_data)
    val = 0
    if saved_data ~= "" then
        local loaded_data = JSON.decode(saved_data)
        if loaded_data ~= nil then
            val = loaded_data[1]
        end
    end
    create_all()
end -- end function onload()


function update_save()
    local data_to_save = {val}
    saved_data = JSON.encode(data_to_save)
    self.script_state = saved_data
end -- end function update_save()


function create_all()
    self.createButton({
        label          = tostring(val),
        click_function = "add_subtract",
        function_owner = self,
        position       = {0.00, 0.01, 2.75},
        height         = 1000,
        width          = 1000,
        font_size      = 1100,
        scale          = {x=1.00, y=1.00, z=1.00},
        font_color     = f_color,
        hover_color    = h_color,
        color          = color
    })
end -- end function create_all()

function remove_all()
      self.removeButton(0)
end -- end function remove_all()

function reload_all()
      remove_all()
      create_all()
      update_save()
end -- end function reload_all()

function add_subtract(_obj, _color, alt_click)
    mod = alt_click and -1 or 1
    original_value = val
    new_value      = math.min(math.max(val + mod, MIN_VALUE), MAX_VALUE)
    if val ~= new_value then
        val = new_value
        update_val()
        update_save()
    end
    for _, object in pairs(zone.getObjects()) do
        if object              == tracker then
            local position      = tracker.getPosition()
            local x_position    = tracker.getGMNotes()
            local is_solo       = getObjectFromGUID("23bed4").getGMNotes()
            local cube_moving   = false
            if is_solo         == "solo" then
                if not alt_click and original_value ~= 15 then
                    position.z  = position.z + 0.77
                    cube_moving = true

                elseif alt_click and original_value ~= 0 then
                    position.z  = position.z - 0.77
                    cube_moving = true
                end
            else
                if not alt_click and original_value ~= 15 then
                    position.z  = position.z - 0.77
                    cube_moving = true
                elseif alt_click and original_value ~= 0 then
                    position.z  = position.z + 0.77
                    cube_moving = true
                end
            end
            if is_solo         ~= "solo" then
                if x_position      == "top" and cube_moving then
                    position.x      = position.x - 0.26
                    tracker.setGMNotes('bottom')
                elseif x_position  == "bottom" and cube_moving then
                    position.x      = position.x + 0.26
                    tracker.setGMNotes('top')
                end
            else
                if x_position      == "top" and cube_moving then
                    position.x      = position.x + 0.26
                    tracker.setGMNotes('bottom')
                elseif x_position  == "bottom" and cube_moving then
                    position.x      = position.x - 0.26
                    tracker.setGMNotes('top')
                end
            end
            if cube_moving then
                if not alt_click then
                    if Player[playerarea_color].steam_name ~= nil then
                        broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. Player[playerarea_color].steam_name .. "[-] has gained +1 " .. track_type .. ".", "White")
                    else
                        local player_str = "Player"
                        if getObjectFromGUID(playerarea_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                        broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. " Player[-] has gained +1 " .. track_type .. ".", "White")
                    end
                else
                    if Player[playerarea_color].steam_name ~= nil then
                        broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. Player[playerarea_color].steam_name .. "[-] has removed -1 " .. track_type .. ".", "White")
                    else
                        local player_str = "Player"
                        if getObjectFromGUID(playerarea_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
                        broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. " Player[-] has removed -1 " .. track_type .. ".", "White")
                    end
                end
            end
            tracker.setPosition(position)
        end
    end
    local captain_zone           = getObjectFromGUID("75465f")
    local captain_pad            = getObjectFromGUID("997491")
    for _, object in pairs(captain_zone.getObjects()) do
        if string.find(object.getName(), "Crew Board") and object ~= captain_pad then
            captain_card_name    = object.getName()
        end
    end
    local captain_name           = nil
    local split_name             = {}
    if captain_card_name        ~= nil then
        for str in string.gmatch(captain_card_name,  "%S+") do
            table.insert(split_name, str)
        end
    end
    captain_name = split_name[1]
    if captain_name == "Burnham" or captain_name == "Picard" or captain_name == "Sisko" then
        UI.setAttribute("blue_hum_research", "text", val)
    elseif captain_name == "Shran" then
        UI.setAttribute("blue_and_research", "text", val)
    elseif captain_name == "Sela" then
        UI.setAttribute("blue_rom_research", "text", val)
    elseif captain_name == "Koloth" then
        UI.setAttribute("blue_kli_research", "text", val)
    end
end -- end function add_subtract()

function subtract()
    new_value = math.min(math.max(val -1, MIN_VALUE), MAX_VALUE)
    if val ~= new_value then
        val = new_value
        update_val()
        update_save()
    end
end -- end function subtract()

function update_val()
    self.editButton({
        index = 0,
        label = tostring(val),
    })
end -- end function update_val()

function setValue(value)
    val = value
    update_val()
    update_save()
end -- send function setValue()

function resetValue()
    val = 0
    update_val()
    update_save()
end -- end function setValue()

function increase()
    add_subtract(_, _, false)
end -- end increase()

function decrease()
    add_subtract(_, _, true)
end -- end decrease()
