function onLoad()

    button_difficulty_guids = {"480492", "1a31d8", "e421a1", "378de4", "6d9c4c", "3b7e7c"}
    button_difficulty_zone  = getObjectFromGUID("596317")
    color                   = {31/255, 136/255, 255, 255}
    hover_color             = {31/255, 136/255, 255, .8}
    highlight_color         = {31/255, 136/255, 255, .8}
    hover_highlight_color   = {31/255, 136/255, 255, .6}
    playerarea_color        = "Blue"
    main_zone                = getObjectFromGUID("75465f")
    diff_zone                = getObjectFromGUID("596317")

    local solo_enabled = self.getGMNotes()
    if solo_enabled == "disabled" then
        self.createButton({
            click_function = "enable_solo",
            function_owner = self,
            label          = "",
            position       = {0, 0.36, 0.4},
            rotation       = {0, 180, 0},
            width          = 250,
            height         = 250,
            scale          = {2.3, 2.3, 2.3},
            color          = color,
            hover_color    = hover_color,
            tooltip        = "Click this button to enable solo play, setting up whichever selected captain for the solo bot in the " .. playerarea_color .. " area.",
        })
    elseif solo_enabled == "enabled" then
        -- create disable solo button
        self.createButton({
            click_function = "disable_solo",
            function_owner = self,
            label          = "✔",
            position       = {0, 0.36, 0.4},
            width          = 250,
            height         = 250,
            font_size      = 200,
            font_color     = {1, 1, 1, 1},
            scale          = {2.3, 2.3, 2.3},
            color          = color,
            hover_color    = hover_color,
            tooltip        = "Click this button to disable solo play, setting up whichever selected captain for a human player in the " .. playerarea_color .. " playerarea.",
        })
        -- show bot difficulty button objects
        for i = 1, 6 do
            local button = getObjectFromGUID(button_difficulty_guids[i])
            button.setGMNotes('disabled')
            local pos    = button.getPosition()
            -- visible: 0.95, hidden: -2
            pos.y = 0.95
            button.setPosition(pos)
            -- create buttons on bot difficulty button objects
            local button_name  = button.getName()
            local split_name   = {}
            for str in string.gmatch(button_name,  "%S+") do
                table.insert(split_name, str)
            end
            local difficulty = split_name[3]
            button.createButton({
                click_function = "enable_" .. difficulty .. "_difficulty",
                function_owner = self,
                label          = "",
                position       = {-0.01, 0.36, 0.00},
                rotation       = {0, 180, 0},
                width          = 490,
                height         = 375,
                scale          = {2, 2, 2},
                color          = {1, 1, 1, .0},
                hover_color    = {1, 1, 1, .3},
                tooltip        = playerarea_color .. " side will be set up for " .. difficulty .. " solo bot difficulty.",
            })
        end
    end
end -- end onLoad()


function remove_buttons(object)
    local buttons = object.getButtons()
    if #buttons > 0 then
        for k = #buttons, 1, -1 do
            object.removeButton(buttons[k].index)
        end
    end
end -- end remove_buttons()


function enable_solo()
    self.setGMNotes('enabled')
    -- broadcast that difficulty must be selected before captain
    broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. "[-] side will be set up for the solo bot.", "White")
    -- show bot difficulty button objects
    for i = 1, 6 do
        local button = getObjectFromGUID(button_difficulty_guids[i])
        local pos    = button.getPosition()
        -- visible: 0.95, hidden: -2
        pos.y = 0.95
        button.setPosition(pos)
        -- create buttons on bot difficulty button objects
        local button_name  = button.getName()
        local split_name   = {}
        for str in string.gmatch(button_name,  "%S+") do
            table.insert(split_name, str)
        end
        local difficulty = split_name[3]
        button.createButton({
            click_function = "enable_" .. difficulty .. "_difficulty",
            function_owner = self,
            label          = "",
            position       = {-0.01, 0.36, 0.00},
            rotation       = {0, 180, 0},
            width          = 490,
            height         = 375,
            scale          = {2, 2, 2},
            color          = {1, 1, 1, .0},
            hover_color    = {1, 1, 1, .3},
            tooltip        = playerarea_color .. " side will be set up for " .. difficulty .. " solo bot difficulty.",
        })
    end
    -- flip captain buttons
    for _, object in pairs(main_zone.getObjects()) do
        if object.hasTag('button_faction_setup') then
            object.setRotation(self == getObjectFromGUID("9e82e7") and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00})
        end
    end
    -- remove button on self
    self.clearButtons()
    -- create disable solo button
    self.createButton({
        click_function = "disable_solo",
        function_owner = self,
        label          = "✔",
        position       = {0, 0.36, 0.4},
        width          = 250,
        height         = 250,
        font_size      = 200,
        font_color     = {1, 1, 1, 1},
        scale          = {2.3, 2.3, 2.3},
        color          = color,
        hover_color    = hover_color,
        tooltip        = "Click this button to disable solo play, setting up whichever selected captain for a human player in the " .. playerarea_color .. " playerarea.",
    })
end -- end enable_solo()


function disable_solo()
    self.setGMNotes('disabled')
    broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. "[-] side will be set up for a human player.", "White")
    -- hide bot difficulty buttons
    for i = 1, 6 do
        local button = getObjectFromGUID(button_difficulty_guids[i])
        button.setGMNotes('disabled')
        local pos    = button.getPosition()
        -- visible: 0.95, hidden: -2
        pos.y = -2
        button.setPosition(pos)
        -- remove buttons on button objects while hidden
        remove_buttons(button)
    end
    -- flip captain buttons
    for _, object in pairs(main_zone.getObjects()) do
        if object.hasTag('button_faction_setup') then
            object.setRotation(self == getObjectFromGUID("9e82e7") and {0.00, 270.00, 0.00} or {0.00, 90.00, 0.00})
        end
    end
    -- remove button on self
    self.clearButtons()
    -- create enable solo button
    self.createButton({
        click_function = "enable_solo",
        function_owner = self,
        label          = "",
        position       = {0, 0.36, 0.4},
        rotation       = {0, 180, 0},
        width          = 250,
        height         = 250,
        scale          = {2.3, 2.3, 2.3},
        color          = color,
        hover_color    = hover_color,
        tooltip        = "Click this button to enable solo play, setting up whichever selected captain for the solo bot in the " .. playerarea_color .. " area.",
    })
end -- end disable_solo()




function enable_difficulty(difficulty)
    -- broadcast
    local difficulty_color_hex = nil
    if difficulty == "Ensign" or difficulty == "Captain" then
        difficulty_color_hex = "E58515"
    elseif difficulty == "Lieutenant" then
        difficulty_color_hex = "71AA75"
    elseif difficulty == "Commander" then
        difficulty_color_hex = "C6CAA5"
    elseif difficulty == "Admiral" then
        difficulty_color_hex = "AD1D14"
    end
    if difficulty_color_hex ~= nil then
        local player_color_hex = Color.fromString(playerarea_color):toHex()
        broadcastToAll("[" .. player_color_hex .. "]" .. playerarea_color .. " Bot[-] difficulty selected: [" .. difficulty_color_hex .. "]" .. difficulty .. "[-]", "White")
    end
    -- remove buttons, refresh
    for i = 1, 6 do
        object = getObjectFromGUID(button_difficulty_guids[i])
        remove_buttons(object)
        if object.getName() == "Button Solo " .. difficulty .. " " .. playerarea_color then
            object.setGMNotes("enabled")
            object.createButton({
                click_function = "disable_" .. difficulty .. "_difficulty",
                function_owner = self,
                label          = "",
                position       = {-0.01, 0.36, 0.00},
                rotation       = {0, 180, 0},
                width          = 490,
                height         = 375,
                scale          = {2, 2, 2},
                color          = highlight_color,
                hover_color    = hover_highlight_color,
                tooltip        = "Disable " .. difficulty .. " solo bot difficulty.",
            })
        else
            object.setGMNotes("disabled")
            local button_name  = object.getName()
            local split_name   = {}
            for str in string.gmatch(button_name,  "%S+") do
                table.insert(split_name, str)
            end
            local disable_difficulty = split_name[3]
            object.createButton({
                click_function = "enable_" .. disable_difficulty .. "_difficulty",
                function_owner = self,
                label          = "",
                position       = {-0.01, 0.36, 0.00},
                rotation       = {0, 180, 0},
                width          = 490,
                height         = 375,
                scale          = {2, 2, 2},
                color          = {1, 1, 1, .0},
                hover_color    = {1, 1, 1, .3},
                tooltip        = playerarea_color .. " side will be set up for " .. disable_difficulty .. " solo bot difficulty.",
            })
        end
    end
end -- end enable_difficulty()


function disable_difficulty(difficulty, button)
    -- broadcast
    local difficulty_color_hex = nil
    if difficulty == "Ensign" or difficulty == "Captain" then
        difficulty_color_hex = "E58515"
    elseif difficulty == "Lieutenant" then
        difficulty_color_hex = "71AA75"
    elseif difficulty == "Commander" then
        difficulty_color_hex = "C6CAA5"
    elseif difficulty == "Admiral" then
        difficulty_color_hex = "AD1D14"
    end
    if difficulty_color_hex ~= nil then
        local player_color_hex = Color.fromString(playerarea_color):toHex()
        broadcastToAll("[" .. player_color_hex .. "]" .. playerarea_color .. " Bot[-] difficulty de-selected: [" .. difficulty_color_hex .. "]" .. difficulty .. "[-]", "White")
    end
    -- remove buttons, refresh
    remove_buttons(button)
    button.setGMNotes("disabled")
    local button_name  = button.getName()
    local split_name   = {}
    for str in string.gmatch(button_name,  "%S+") do
        table.insert(split_name, str)
    end
    local disable_difficulty = split_name[3]
    button.createButton({
        click_function = "enable_" .. disable_difficulty .. "_difficulty",
        function_owner = self,
        label          = "",
        position       = {-0.01, 0.36, 0.00},
        rotation       = {0, 180, 0},
        width          = 490,
        height         = 375,
        scale          = {2, 2, 2},
        color          = {1, 1, 1, .0},
        hover_color    = {1, 1, 1, .3},
        tooltip        = playerarea_color .. " side will be set up for " .. disable_difficulty .. " solo bot difficulty.",
    })
end -- end disable_difficulty()


function enable_Cadet_difficulty(button, _, _)
    -- broadcast
    broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. "[-] side will be set up for Cadet practice mode.", "White")
    -- destroy playerarea buttons
    local checkzones = {main_zone, diff_zone}
    for i = 1, 2 do
        for _, object in pairs(checkzones[i].getObjects()) do
            if object.hasTag('button_faction_setup') or object.hasTag('button_solo_setup') then
                object.destruct()
            end
        end
    end
    -- deploy cadet stardate cards
    getObjectFromGUID("24c81c").setPositionSmooth({-12.50, 1.50, 0.00}, false, false)
    local glory_locs = {
        {-11.00, 0.85, 4.00},
        {-12.50, 0.85, 4.00},
        {-14.00, 0.85, 4.00},
        {-11.00, 0.85, 5.50},
        {-12.50, 0.85, 5.50},
    }
    for i = 1, 5 do
        local glory_token = getObjectFromGUID("263bae").takeObject()
        glory_token.setPositionSmooth(glory_locs[i], false, false)
    end
    -- check if last playerarea to be set up, if so, clean up unused captain decks objects etc
    local solo_check = getObjectFromGUID("0bad8b")
    if solo_check == nil then
        Wait.time(function()
        local zones = {getObjectFromGUID("a1c39b"), getObjectFromGUID("20818f")}
        for i = 1, 2 do
            for _, object in pairs(zones[i].getObjects()) do
                if object.hasTag('cleanup_target') then
                    getObjectFromGUID("f6e30d").putObject(object)
                end
            end
        end
        getObjectFromGUID("04c44a").setState(1)
        getObjectFromGUID("6e517a").setState(1)
        end, 3)
    end
    Global.call('show_stardate_glory_counter', {stardate_type="cadet"})
end -- enable_Cadet_difficulty()

function enable_Ensign_difficulty(button, _, _)
    local difficulty = "Ensign"
    enable_difficulty(difficulty)
end -- enable_Ensign_difficulty()

function enable_Lieutenant_difficulty(button, _, _)
    local difficulty = "Lieutenant"
    enable_difficulty(difficulty)
end -- enable_Lieutenant_difficulty()

function enable_Commander_difficulty(button, _, _)
    local difficulty = "Commander"
    enable_difficulty(difficulty)
end -- enable_Commander_difficulty()

function enable_Captain_difficulty(button, _, _)
    local difficulty = "Captain"
    enable_difficulty(difficulty)
end -- enable_Captain_difficulty()

function enable_Admiral_difficulty(button, _, _)
    local difficulty = "Admiral"
    enable_difficulty(difficulty)
end -- enable_Admiral_difficulty()


function disable_Ensign_difficulty(button, _, _)
    local difficulty = "Ensign"
    disable_difficulty(difficulty, button)
end -- disable_Ensign_difficulty()

function disable_Lieutenant_difficulty(button, _, _)
    local difficulty = "Lieutenant"
    disable_difficulty(difficulty, button)
end -- disable_Lieutenant_difficulty()

function disable_Commander_difficulty(button, _, _)
    local difficulty = "Commander"
    disable_difficulty(difficulty, button)
end -- disable_Commander_difficulty()

function disable_Captain_difficulty(button, _, _)
    local difficulty = "Captain"
    disable_difficulty(difficulty, button)
end -- disable_Captain_difficulty()

function disable_Admiral_difficulty(button, _, _)
    local difficulty = "Admiral"
    disable_difficulty(difficulty, button)
end -- disable_Admiral_difficulty()
