function get_playerarea_color(card)
    local playerarea_color = nil
    local blue_zones       = {getObjectFromGUID("2c336e"), getObjectFromGUID("fc7f21")}
    local red_zones        = {getObjectFromGUID("77d0cb"), getObjectFromGUID("5103b2")}
    for i = 1, 2 do
        for _, object in pairs(blue_zones[i].getObjects()) do
            if card == object then
                playerarea_color = "Blue"
            end
        end
        for _, object in pairs(red_zones[i].getObjects()) do
            if card == object then
                playerarea_color = "Red"
            end
        end
    end
    return playerarea_color
end -- get_playerearea_color()


function create_deploy_button(params)
    local card             = params.card
    local ship_name        = card.getName()
    local playerarea_color = get_playerarea_color(card)
    card.UI.show('deploy_ship_button_' .. string.lower(playerarea_color))
end -- end create_deploy_button()


function remove_deploy_button(params)
    local card             = params.card
    local playerarea_color = params.playerarea_color
    card.UI.hide('deploy_ship_button_' .. string.lower(playerarea_color))
end -- end remove_deploy_button()


function create_dismiss_button(params)
    local card             = params.card
    local ship_name        = card.getName()
    local playerarea_color = get_playerarea_color(card)
    card.UI.show('dismiss_ship_button_' .. string.lower(playerarea_color))
end -- end create_deploy_button()


function remove_dismiss_button(params)
    local card             = params.card
    local playerarea_color = params.playerarea_color
    card.UI.hide('dismiss_ship_button_' .. string.lower(playerarea_color))
end -- end remove_deploy_button()


function deploy_ship_via_pad(args)
    local value = args.value
    deploy_ship(_, value, _)
end

function deploy_ship(_, value, _)
    local ship_card        = getObjectFromGUID(value)
    local ship_in_bag      = true
    local card_rotation    = ship_card.getRotation()
    if card_rotation.y < 271 and card_rotation.y > 269 then
        card_rotation.y = 90
    elseif card_rotation.y < 91 and card_rotation.y > 89 then
        card_rotation.y = 270
    end
    local card_position    = ship_card.getPosition()
    local found_ship       = nil
    local playerarea_color = get_playerarea_color(ship_card)

    local is_solo          = nil
    if playerarea_color   == "Blue" and getObjectFromGUID("23bed4").getGMNotes() == "solo" or
    playerarea_color      == "Red" and getObjectFromGUID("1a78a6").getGMNotes() == "solo" then
        card_position.x = card_position.x + (playerarea_color == "Blue" and -1.50 or 1.50)
    else
        card_position.x = card_position.x + (playerarea_color == "Blue" and 1.50 or -1.50)
    end
    local self_objects = self.getObjects()
    for _, bag_object in pairs(self_objects) do
        if bag_object.name == ship_card.getName() then
            found_ship = self.takeObject({index=bag_object.index})
            break
        end
    end
    if found_ship == nil then
        local dock_objects = getObjectFromGUID(playerarea_color == "Blue" and "b5c141" or "f047fb").getObjects()
        for _, dock_object in pairs(dock_objects) do
            if dock_object.name == ship_card.getName() then
                found_ship = getObjectFromGUID(playerarea_color == "Blue" and "b5c141" or "f047fb").takeObject({index=dock_object.index})
                break
            end
        end
    end
    -- if playerarea_color == nil or found_ship == nil then
    --     broadcastToAll("Unable to determine where ship card is, please deploy ship manually.", "Orange")
    -- end
    -- if found_ship == nil and playerarea_color ~= nil then
    --     broadcastToColor("Unable to determine where ship figurine is, please deploy ship manually.", playerarea_color, "Orange")
    -- end
    if found_ship ~= nil and playerarea_color ~= nil then
        if Player[playerarea_color].steam_name ~= nil then
            broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. Player[playerarea_color].steam_name .. "[-] has deployed " .. found_ship.getName() .. ".", "White")
        else
            local player_str = "Player"
            if getObjectFromGUID(player_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
            broadcastToAll("[" .. Color.fromString(playerarea_color):toHex() .. "]" .. playerarea_color .. " " .. player_str .. "[-] has deployed " .. found_ship.getName() .. ".", "White")
        end
        found_ship.setRotation(card_rotation)
        card_position.y = 1.25
        found_ship.setPositionSmooth(card_position, false, false)
        local blue_zones     = {getObjectFromGUID("2c336e"), getObjectFromGUID("fc7f21")}
        local red_zones      = {getObjectFromGUID("77d0cb"), getObjectFromGUID("5103b2")}
        if ship_card.hasTag('trait_cloak') then
            found_ship.setDescription('Cloaked')
            found_ship.highlightOn("Purple")
            found_ship.setColorTint(playerarea_color)
        elseif not ship_card.hasTag('trait_cloak') and playerarea_color ~= nil then
            found_ship.setDescription("")
            found_ship.highlightOn(playerarea_color)
            found_ship.setColorTint(playerarea_color)
        end
    end
end -- end deploy_ship()


function dismiss_ship_from_card(_, value, _)
    local ship_card = getObjectFromGUID(value)
    local ship_name = ship_card.getName()
    local ship      = nil
    for _, object in pairs(getObjects()) do
        if object.getName() == ship_name and object.hasTag('snap_ship') then
            ship    = object
        end
    end
    if ship ~= nil then
        dismiss_ship({ship=ship})
    else
        broadcastToAll("Ship is not found in play, please dismiss ship manually.", "Orange")
    end
end -- end dismiss_ship_from_card()

function dismiss_ship(args)
    local ship           = args.ship
    local ship_name      = ship.getName()
    local beam_bag_guids = {
        ship_blue        = {"f3ac62", "acf736", "f8fc03", "5807b2", "d57c5c", "9d0439", "ff0165"},
        location_blue    = {"26a5c6", "ca88c0", "40b578", "eeadbe", "7a7548", "397e6d", "ce11ad"},
        ship_red         = {"95dff1", "30048e", "910a26", "9e394f", "392caa", "c32b20", "b5d6f9"},
        location_red     = {"7f4770", "577602", "82a5c5", "4f12e8", "351f79", "efdbd0", "cf1df7"},
    }
    -- check if ship_card is in play on table
    local ship_card      = nil
    for _, object in pairs(getObjects()) do
        if object.getName() == ship_name and object.tag == "Card" then ship_card = object end
    end
    if ship_card == nil then
        broadcastToAll("Ship card not found for dismissed ship: " .. ship_name .. ", Please perform dismiss actions manually!", "Orange")
        return nil
    end
    local playerarea_color = get_playerarea_color(ship_card)
    ship_card.call('remove_deploy_button', {playerarea_color=playerarea_color})
    -- get position of ship card, determine owner_color, row & slot # from it
    local card_pos       = ship_card.getPosition()
    local owner_color    = nil
    local row            = nil -- "ship_blue", "location_blue", "ship_red", "location_red"
    local slot           = nil -- 1-7
    if card_pos.x > -39.50 and card_pos.x < -37.50 then
        owner_color      = "Blue"
        row              = "ship_blue"
    elseif card_pos.x > -31.00 and card_pos.x < -29.00 then
        owner_color      = "Blue"
        row              = "location_blue"
    elseif card_pos.x < 39.50 and card_pos.x > 37.50 then
        owner_color      = "Red"
        row              = "ship_red"
    elseif card_pos.x < 31.00 and card_pos.x > 29.00 then
        owner_color      = "Red"
        row              = "location_red"
    end
    -- determine beam bag
    if (card_pos.z > 1.47 and card_pos.z < 3.47) or (card_pos.z < -1.47 and card_pos.z > -3.47) then
        slot = 1
    elseif (card_pos.z > -2.45 and card_pos.z < -0.45) or (card_pos.z < 2.45 and card_pos.z > 0.45) then
        slot = 2
    elseif (card_pos.z > -6.36 and card_pos.z < -4.36) or (card_pos.z < 6.36 and card_pos.z > 4.36) then
        slot = 3
    elseif (card_pos.z > -10.28 and card_pos.z < -8.28) or (card_pos.z < 10.28 and card_pos.z > 8.28) then
        slot = 4
    elseif (card_pos.z > -14.20 and card_pos.z < -12.20) or (card_pos.z < 14.20 and card_pos.z > 12.20) then
        slot = 5
    elseif (card_pos.z > -18.12 and card_pos.z < -16.12) or (card_pos.z < 18.12 and card_pos.z > 16.12) then
        slot = 6
    elseif (card_pos.z > -22.00 and card_pos.z < -20.00) or (card_pos.z < 22.00 and card_pos.z > 20.00) then
        slot = 7
    end
    -- send ship figure to space dock bag (remove this functionality when calling this in control location buttons)
    getObjectFromGUID(owner_color == "Blue" and "b5c141" or "f047fb").putObject(ship)
    -- broadcast
    if Player[owner_color].steam_name ~= nil then
        broadcastToAll("[" .. Color.fromString(owner_color):toHex() .. "]" .. Player[owner_color].steam_name .. "[-] has dismissed " .. ship_card.getName() .. ".", "White")
    else
        local player_str = "Player"
        if getObjectFromGUID(owner_color == "Blue" and "23bed4" or "1a78a6").getGMNotes() == "solo" then player_str = "Bot" end
        broadcastToAll("[" .. Color.fromString(owner_color):toHex() .. "]" .. owner_color .. " " .. player_str .. "[-] has dismissed " .. ship_card.getName() .. ".", "White")
    end
    -- send ship card to discard
    local ship_card_rot = owner_color == "Blue" and {0.00, 270.00, 0.00} or {0.00, 90.00, 0.00}
    local discard_pos   = owner_color == "Blue" and {-44.57, 1.50, -21.00} or {44.57, 1.50, 21.00}
    if owner_color == "Blue" and getObjectFromGUID("1a78a6").getGMNotes() == "solo" then
        ship_card_rot = {0.00, 90.00, 0.00}
    end
    if owner_color == "Red" and getObjectFromGUID("23bed4").getGMNotes() == "solo" then
        ship_card_rot = {0.00, 270.00, 0.00}
    end
    ship_card.setPositionSmooth(discard_pos, false, false)
    -- trigger beam bag cleanout button
    if (owner_color == "Blue" and getObjectFromGUID("23bed4").getGMNotes() ~= "solo") or
    (owner_color == "Red" and getObjectFromGUID("1a78a6").getGMNotes() ~= "solo") then
        local beam_bag = getObjectFromGUID(beam_bag_guids[row][slot])
        local bag_objects = beam_bag.getObjects()
        for i = 1, #bag_objects do
            local object = beam_bag.takeObject({rotation=ship_card_rot})
            object.setPositionSmooth(discard_pos, false, false)
        end
    end
end -- end dismiss_ship()
