ship_bag = getObjectFromGUID("82424c")


function create_deploy_button()
    ship_bag.call('create_deploy_button', {card=self})
end -- end create_deploy_button()


function remove_deploy_button(params)
    playerarea_color = params.playerarea_color
    ship_bag.call('remove_deploy_button', {card=self, playerarea_color=playerarea_color})
end -- end remove_deploy_button()


function create_dismiss_button()
    ship_bag.call('create_dismiss_button', {card=self})
end -- end create_deploy_button()


function remove_dismiss_button(params)
    playerarea_color = params.playerarea_color
    ship_bag.call('remove_dismiss_button', {card=self, playerarea_color=playerarea_color})
end -- end remove_deploy_button()
