-- handles functionality related to captain area non counter, non beambag/log buttons
-- report buttons, discard hand, space dock, +1 action
-- counter stuff is instead in Counters.ttlsua (and injected onto the object scope)
-- beam bag & log stuff is instead in BeamedBags.ttslua




function initButtonReportResupply(buttonObj)
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "reportResupply",
    function_owner = self,
    label          = "",
    position       = {0, 0.36, -0.01},
    width          = 865,
    height         = 435,
    scale          = {2.3, 2.3, 2.3},
    color          = {1, 1, 1, .3},
    hover_color    = {1, 1, 1, .6},
    tooltip        = "Clicking this button will report all currently in play Resupply Step cards for the " .. playerarea_color .. " player.\n\nRight clicking will momentarily highlight Resupply Step cards in play without broadcasting.",
  })
end








function reportResupply(buttonObj, _, altClick)
  -- handles report of currently in play Resupply cards
  -- alt click will simply highlight, not broadcast
  -- "in play" meaning card within ship deploy, location deploy, captain, or duty officer zones

  local playerColor = buttonObj.getGMNotes()

  -- animate button
  animateButton(buttonObj)

  -- check in play areas
  local checkZones = {
    getObjectbyNameAndNotes("Zone Deploy Ship", playerColor),
    getObjectbyNameAndNotes("Zone Deploy Location", playerColor),
    getObjectbyNameAndNotes("Zone Captain", playerColor),
    getObjectbyNameAndNotes("Zone Duty Officer", playerColor),
  }
  

end