-- contains functions related to the Market buttons & actions



function initButtonTakeIncident(buttonObj)
  local tooltip = string.format("Clicking this button will take an Incident. \n\n[b][%s]***[-][/b]\nIf vs. a solo bot, right clicking this button will take an Incident for the bot.", Color.fromString("Orange"):toHex())
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "takeIncident",
    function_owner = self,
    label          = "",
    position       = { 0, 0.36, -0.01 },
    width          = 865,
    height         = 435,
    scale          = { 2.3, 2.3, 2.3 },
    color          = { 1, 1, 1, .3 },
    hover_color    = { 1, 1, 1, .6 },
    tooltip        = tooltip,
  })
end







function takeIncident(buttonObj, clickerColor, altClick)
  -- handles the Incident Take button functionality

  animateButton(buttonObj)

  if clickerColor ~= "Blue" and clickerColor ~= "Red" then
    return
  end

  local playerColor
  if not altClick then
    playerColor = clickerColor
  elseif altClick then
    playerColor = clickerColor == "Blue" and "Red" or "Blue"
  end

  local isBot = checkPlayerColorIsBot(playerColor)

  if altClick and not isBot then
    altClick = false
    playerColor = clickerColor
  end

  local locTake
  local rotTake

  if not altClick then
    locTake = playerColor == "Blue" and { -54.00, 3.00, 0.00 } or { 54.00, 3.00, 0.00 }
    rotTake = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  else
    rotTake = playerColor == "Blue" and { 0.00, 90.00, 180.00 } or { 0.00, 270.00, 180.00 }
    locTake = playerColor == "Blue" and { -44.50, 3.00, 7.00 } or { 44.50, 3.00, -7.00 }
  end

  local card = nil
  local cardFound = false
  local incidentCheckZone = getObjectbyName("Zone Incident")
  for _, zoneObj in pairs(incidentCheckZone.getObjects()) do
    if zoneObj.hasTag("suit_incident") then
      if zoneObj.tag == "Deck" then
        card = zoneObj.takeObject()
      elseif zoneObj.tag == "Card" then
        card = zoneObj
      end

      card.setRotation(rotTake)
      card.setPositionSmooth(locTake, false, true)
      cardFound = true
      break
    end
  end

  -- broadcast
  local playerStr = getPlayerStr(playerColor)
  local broadcastStr = string.format("%s has taken an Incident.", playerStr)
  broadcastToAll(broadcastStr, "White")

  if not cardFound then
    broadcastToAll("Burn initiated!", "Orange")
    return nil
  end

  Wait.time(function()

    cardFound = false

    for _, zoneObj in pairs(incidentCheckZone.getObjects()) do
      if zoneObj.hasTag("suit_incident") then
        cardFound = true
        break
      end
    end

    if not cardFound then
      broadcastToAll("Burn initiated!", "Orange")
    end

  end, 1)
end