-- contains functions related to the Neutral Zone actions



function initButtonControlNZLocation(buttonObj)
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "controlNZLocation",
    function_owner = self,
    label          = "",
    position       = {0, 0.36, -0.01},
    width          = 865,
    height         = 435,
    scale          = {2.3, 2.3, 2.3},
    color          = {1, 1, 1, .3},
    hover_color    = {1, 1, 1, .6},
    tooltip        = "Clicking this button will control this location, return/dismiss away teams and ships, and replace the location if possible.\n\n[b]*[/b] It [b]does not[/b] check to make sure a control is allowed before doing so.",
  })
end


-- wrapper to handle all of the actions related to the control of a NZ location
function controlNZLocation(buttonObj, _, _)
  -- collect required info
  local playerColor = buttonObj.getGMNotes()
  local otherPlayerColor = playerColor == "Blue" and "Red" or "Blue"
  local buttonArea = (buttonObj.getName():find("Top") and "Top") or
                     (buttonObj.getName():find("Middle") and "Middle") or
                     (buttonObj.getName():find("Bottom") and "Bottom")
  local isBot = checkPlayerColorIsBot(playerColor)

  -- animate button
  animateButton(buttonObj)

  -- return playerColor away teams and ships
  returnPlayerNZObjects(buttonArea, playerColor, isBot)

  -- take controlled location, place to next free slot on playerColor location pad
  local controlledLocation = takeControlledLocation(buttonArea, playerColor, isBot)

  -- verify a controlled location was actually taken before proceeding
  if controlledLocation ~= nil then

    Wait.time(function()

      -- replace taken location
      local replacementLocation = replaceTakenLocation(buttonArea, playerColor, isBot)

      -- handle return & giving glory for otherPlayerColor ships & ATs
      local opposeCount = returnOtherPlayerNZObjects(buttonArea, otherPlayerColor, isBot)

      -- broadcast
      local playerStr = getPlayerStr(playerColor)
      local broadcastStr = ""
      if replacementLocation ~= nil then
        broadcastStr = string.format("%s has taken control of %s, which has been replaced with %s.", playerStr, controlledLocation, replacementLocation)
      else
        broadcastStr = string.format("%s has taken control of %s, which was not replaced.", playerStr, controlledLocation)
      end
      broadcastToAll(broadcastStr, "White")

      local controlText = getControlText(controlledLocation)
      if controlText ~= nil and not isBot then
        local controlStr = string.format("%s Control Effect: %s", controlledLocation, controlText)
        Wait.time(function()

          broadcastToAll(controlStr, "White")

        end, 0.5)
      end

    end, 0.5)
  else
    return
  end
end


function returnPlayerNZObjects(buttonArea, playerColor, isBot)
  -- handles return of playerColor away teams and ships

  local rotReturn = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posATReturn = playerColor == "Blue" and { -28.75, 2.00, 6.30 } or { 28.75, 2.00, -6.30 }
  local checkZone = getObjectbyNameAndNotes("Zone NZ Player " .. buttonArea, playerColor)
  for _, zoneObj in pairs(checkZone.getObjects()) do
    -- return away teams
    if zoneObj.hasTag('away_' .. string.lower(playerColor)) then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posATReturn, false, true)

    -- return ships
    elseif zoneObj.hasTag('snap_ship') then

      -- account for R.I.S. Talvath
      if zoneObj.getName() == "R.I.S. Talvath" and not checkPlayerColorIsBot(playerColor) then

        local cardObj = getObjectbyNameAndType("R.I.S. Talvath", "Card")
        local cardPos = cardObj.getPosition()
        local dilithiumOnTalvathCount = 0
        local isBurnham = getCaptainName(playerColor) == "Burnham"
        local hasInertDilithium = false
        if isBurnham then
          for _, dutyZoneObj in pairs(getObjectbyNameAndNotes("Zone Duty Officer", playerColor).getObjects()) do
            if dutyZoneObj.getName() == "Inert Dilithium" then
              hasInertDilithium = true
              break
            end
          end
        end

        for _, object in pairs(getObjects()) do
          if object.getName() == "Dilithium Token" then

            local objPos = object.getPosition()
            local xDistance = math.abs(objPos.x - cardPos.x)
            local zDistance = math.abs(objPos.z - cardPos.z)

            if xDistance <= 3.5 and zDistance <= 1.75 then
              dilithiumOnTalvathCount = dilithiumOnTalvathCount + 1
              if not (isBurnham and hasInertDilithium) then
                object.destruct()
              end
            end
          end
        end

        local playerStr = getPlayerStr(playerColor)
        local gloryCounter = getObjectbyName("Glory Counter " .. playerColor)
        gloryCounter.call("pullStardateGlory", playerColor)

        if not (isBurnham and hasInertDilithium) then
          local counter = getObjectbyName("Dilithium Counter " .. playerColor)

          if counter then
            local oldVal = counter.getVar("val")
            local newVal = oldVal + dilithiumOnTalvathCount
            counter.call("setValue", newVal)

            local broadcastStr = string.format("%s - R.I.S. Talvath Dismissed during Control Step, gained 1 Glory, and %d Dilithium from card. (%d > %d)", playerStr, dilithiumOnTalvathCount, oldVal, newVal)
            Wait.time(function() broadcastToAll(broadcastStr, "White") end, 2)
          end

        elseif (isBurnham and hasInertDilithium) then
          local broadcastStr = string.format("%s - R.I.S. Talvath Dismissed during Control Step, gained 1 Glory. Place remaining %d Dilithium to Inert Dilithium.", playerStr, dilithiumOnTalvathCount)
          broadcastToAll(broadcastStr, "White")
        end
      end

      local shipObj = zoneObj
      local cardObj = getObjectbyNameAndType(shipObj.getName(), "Card")
      dismissShip(cardObj, shipObj)
    end
  end
end


function returnOtherPlayerNZObjects(buttonArea, otherPlayerColor, isBot)
  -- handle return & giving glory for otherPlayerColor ships & ATs

  local rotReturn = otherPlayerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = otherPlayerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posATReturn = otherPlayerColor == "Blue" and { -28.75, 2.00, 6.30 } or { 28.75, 2.00, -6.30 }
  local opposeCheckZone = getObjectbyNameAndNotes("Zone NZ Player " .. buttonArea, otherPlayerColor)
  local opposeCount = 0
  for _, zoneObj in pairs(opposeCheckZone.getObjects()) do

    -- return opposing away teams
    if zoneObj.hasTag('away_' .. string.lower(otherPlayerColor)) then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posATReturn, false, true)
      opposeCount = opposeCount + 1

    -- dismiss ships
    elseif zoneObj.hasTag('snap_ship') then

      -- account for R.I.S. Talvath
      local cardObj
      if zoneObj.getName() == "R.I.S. Talvath" and not checkPlayerColorIsBot(otherPlayerColor) then

        cardObj = getObjectbyNameAndType("R.I.S. Talvath", "Card")
        local cardPos = cardObj.getPosition()
        local dilithiumOnTalvathCount = 0
        local isBurnham = getCaptainName(otherPlayerColor) == "Burnham"
        local hasInertDilithium = false
        if isBurnham then
          for _, dutyZoneObj in pairs(getObjectbyNameAndNotes("Zone Duty Officer", otherPlayerColor).getObjects()) do
            if dutyZoneObj.getName() == "Inert Dilithium" then
              hasInertDilithium = true
              break
            end
          end
        end
        local playerStr = getPlayerStr(otherPlayerColor)
        local gloryCounter = getObjectbyName("Glory Counter " .. otherPlayerColor)
        gloryCounter.call("pullStardateGlory", otherPlayerColor)

        for _, object in pairs(getObjects()) do
          if object.getName() == "Dilithium Token" then

            local objPos = object.getPosition()
            local xDistance = math.abs(objPos.x - cardPos.x)
            local zDistance = math.abs(objPos.z - cardPos.z)

            if xDistance <= 3.5 and zDistance <= 1.75 then
              dilithiumOnTalvathCount = dilithiumOnTalvathCount + 1
              if not (isBurnham and hasInertDilithium) then
                object.destruct()
              end
            end
          end
        end

        if not (isBurnham and hasInertDilithium) then
          local counter = getObjectbyName("Dilithium Counter " .. otherPlayerColor)

          if counter then
            local oldVal = counter.getVar("val")
            local newVal = oldVal + dilithiumOnTalvathCount
            counter.call("setValue", newVal)

            local broadcastStr = string.format("%s - R.I.S. Talvath Dismissed during Control Step, gained 1 Glory, and %d Dilithium from card. (%d > %d)", playerStr, dilithiumOnTalvathCount, oldVal, newVal)
            Wait.time(function() broadcastToAll(broadcastStr, "White") end, 2)
          end

        elseif (isBurnham and hasInertDilithium) then
          local broadcastStr = string.format("%s - R.I.S. Talvath Dismissed during Control Step, gained 1 Glory. Place remaining %d Dilithium to Inert Dilithium.", playerStr, dilithiumOnTalvathCount)
          broadcastToAll(broadcastStr, "White")
        end
      end

      local shipObj = zoneObj
      cardObj = getObjectbyNameAndType(shipObj.getName(), "Card")

      dismissShip(cardObj, shipObj)
      opposeCount = opposeCount + 1
    end
  end

  -- handle the glory for the return of ATs and ships
  local isCadet = checkIsCadet()
  if opposeCount > 0 and not isCadet then
    local gloryCounter = getObjectbyName("Glory Counter " .. otherPlayerColor)

    -- Get current count of glory on stardate card
    local gloryOnStardateCount = 0
    local gloryCheckZone = getObjectbyName("Zone Stardate Glory")

    for _, object in pairs(gloryCheckZone.getObjects()) do
      if object.getName() == "Glory Token" then
        gloryOnStardateCount = gloryOnStardateCount + 1
      end
    end

    -- Calculate this synchronously, before any Wait.time()
    local diffCount = math.max(opposeCount - gloryOnStardateCount, 0)

    Wait.time(function()

      local playerStr = getPlayerStr(otherPlayerColor)
      local broadcastStr = string.format(
        "%s takes %s Glory, 1 for every dismissed ship or returned away team!.",
        playerStr,
        opposeCount
      )
      broadcastToAll(broadcastStr, "White")

      if gloryOnStardateCount >= opposeCount then
        for i = 1, opposeCount do
          local waitTimer = (i - 1) * 0.25

          Wait.time(function()
            gloryCounter.call('increaseValue')
          end, waitTimer)
        end

      else
        for i = 1, gloryOnStardateCount do
          local waitTimer = (i - 1) * 0.25

          Wait.time(function()
            gloryCounter.call('increaseValue')

            if i == gloryOnStardateCount then
              broadcastToAll(
                "Pausing Glory Allocation to refresh Stardate Card.",
                "Yellow"
              )
            end
          end, waitTimer)
        end

        Wait.time(function()
          for i = 1, diffCount do
            local waitTimer = (i - 1) * 0.25

            Wait.time(function()
              gloryCounter.call('increaseValue')
            end, waitTimer)
          end
        end, 3)
      end

    end, 1)
  end
  return opposeCount
end


function takeControlledLocation(buttonArea, playerColor, isBot)
  -- handles the taking of a controlled location, and the detection of the next free location slot position to place it
  -- returns either the found & placed NZ location card (for broadcast in wrapper), or, nil

  local controlledLocation = nil
  local nzCheckZone = getObjectbyName("Zone NZ Location " .. buttonArea)
  local locationCheckZone = getObjectbyNameAndNotes("Zone Deploy Location", playerColor)
  local rotReturn = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posSlots = playerColor == "Blue" and {
  { -30.00, 0.96,  2.46 },
  { -30.00, 0.96, -1.46 },
  { -30.00, 0.96, -5.37 },
  { -30.00, 0.96, -9.29 },
  { -30.00, 0.96, -13.21 },
  { -30.00, 0.96, -17.13 },
  { -30.00, 0.96, -21.04 },
} or {
  { 30.00, 0.96, -2.46 },
  { 30.00, 0.96,  1.46 },
  { 30.00, 0.96,  5.37 },
  { 30.00, 0.96,  9.29 },
  { 30.00, 0.96, 13.21 },
  { 30.00, 0.96, 17.13 },
  { 30.00, 0.96, 21.04 },
}

local locationSlots = {}

for i = 1, 7 do
  locationSlots[i] = false
end

for _, zoneObj in pairs(locationCheckZone.getObjects()) do
  if zoneObj.tag == "Card" then
    local pos = zoneObj.getPosition()

    for i, slot in ipairs(posSlots) do
      if math.abs(pos.z - slot[3]) < 0.5 then
        locationSlots[i] = true
        break
      end
    end
  end
end

local nextFreeSlot = 0

for i = 1, 7 do
  if not locationSlots[i] then
    nextFreeSlot = i
    break
  end
end

  -- overwrite posSlot default if nextFreeSlot is determined
  local posSlot = 7
  if nextFreeSlot ~= 0 then
    posSlot = posSlots[nextFreeSlot]
  end

  -- position card to slot
  for _, zoneObj in pairs(nzCheckZone.getObjects()) do
    if zoneObj.tag == "Card" then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posSlot, false, true)
      controlledLocation = zoneObj.getName()
    end
  end

  return controlledLocation
end


function replaceTakenLocation(buttonArea, playerColor, isBot)
  -- handles the replacement of a new location after a controlled location is taken
  -- returns either replacement card object (for wrapper broadcast), or, nil

  local rotReplacement = { 0.00, 180.00, 0.00 }
  local posNZs = {
    ["Top"]    = { 0.00, 2.00, -7.00 },
    ["Middle"] = { 0.00, 2.00, -14.00 },
    ["Bottom"] = { 0.00, 2.00, -21.00 },
  }
  local posReplacement = posNZs[buttonArea]

  local deckCheckZone = getObjectbyName("Zone Advanced Locations")
  local replacementCard = nil
  for _, zoneObj in pairs(deckCheckZone.getObjects()) do
    if zoneObj.type == "Deck" then
      replacementCard = zoneObj.takeObject()
      replacementCard.setRotation(rotReplacement)
      replacementCard.setPositionSmooth(posReplacement, false, true)

    elseif zoneObj.tag == "Card" then
      replacementCard = zoneObj
      replacementCard.setRotation(rotReplacement)
      replacementCard.setPositionSmooth(posReplacement, false, false)
    end
  end
  local replacementCardName = replacementCard ~= nil and replacementCard.getName() or nil
  return replacementCardName
end


function getControlText(cardName)
  -- simply returns the relevent control action text per Location
  local controlActions = {
    -- in order of periodic's database

    -- picard
    ["Farpoint Station"] = "Gain 1 Research.",
    ["Daystrom Institute"] = "You may scan for a Synthetic.",
    ["Starbase 74"] = "Find a Person. You may discard a different card to free play the found card.",

    -- shran
    ["Andoria"] = "If you have an Away Team here, draw a card. If you have 3+ total Away Teams on 1 or more controlled Location, draw a card.",
    ["Weytahn"] = "You may free play a Cargo or a Ship.",
    ["Coridan"] = "You may discard 2 cards to gain 2 Dilithium and 2 Latinum.",

    -- koloth
    ["Qo'nos"] = "Gain 1 Influence.",
    ["Rura Penthe"] = "Gain 2 Dilithium.",
    ["Boreth"] = "Find any card and free play it.",

    -- sisko
    ["The Wormhole"] = "Look at the top 3 Locations and put them on the top and/or the bottom of their deck in any order.",
    ["Starbase 375"] = "You may find a Ship.",

    -- sela
    ["Remus"] = string.format("[%s](Attack)[-] Force your opponent to discard a card.", Color.fromString("Red"):toHex()),
    ["Romulus"] = "You may free play a Ship.",

    -- burnham
    ["Ni'Var"] = "You may find [i]Inspire[/i] OR scan for an Ambassador.",
    ["Earth"] = "You may gain a Person.",
    ["Theta Zeta"] = "Recrystallize all Dilithium. Log [i]Inert Dilithium[-] (from play). Gain 4 Glory.",

    -- georgiou
    ["Vulcan Science Academy"] = "You may gain a Person. If the gained card is Vulcan, gain 2 Dilithium. If the gained card is Scientist, gain 1 Glory. If the gained card has both traits, gain both rewards.",
    ["Kaminar"] = "Find a Kelpian. If the found card is a Person, you may promote them to Duty Officer.",
    ["Binary Stars Comms Relay"] = "Up to three times: log a Starfleet from your hand to scan for a Klingon.",

    -- soval
    ["Paan Mokar"] = "You may free play a Cargo/Ship.",
    ["Mount Seleya"] = "Draw a card for each Vulcan in your Log.",

    -- kirk
    ["Vulcan"] = "You may find a Vulcan. You may draw [i]Utilize[/i] from your Discard pile. You may free play an Incident.",
    ["Automated Repair Station"] = "You may beam a Person here to scan 1 of Ship.",

    -- rebner
    ["Pakled Planet"] = "Find a Helmet, except in your Reserve deck.",
    ["Karzill VI"] = "You may free play a Ship.",

    -- khan
    ["Vacated Regula I"] = "You may take an Incident to mark one trait of a card in the Junk pile.",
    ["Mutara Nebula"] = "No effect.",

    -- pike
    ["Rigel VII"] = "Draw a card. You may beam a card here from your hand or Discard pile.",

    -- riker
    ["Starbase 25"] = "You may exhaust the [i]U.S.S. Titan[/i] to gain 1 Influence. You may spend 1 Dilithium to send an Away Team here.",
    ["Nepenthe"] = "You may scan for a Synthetic.",

    -- freeman
    ["Douglas Station"] = "You may gain a Person. You may log a card from your hand or Discard pile.",
    ["The Farm"] = "You may free play an Incident.",

    -- Base commons
    ["Amargosa Observatory"] = "You may gain a Person. If it is Scientist/Engineer gain 1 Glory.",
    ["Ancient Relay Station"] = "You may put a card on the top of your deck and spend an action to enlist a Development.",
    ["Archer IV"] = "No effect.",
    ["Betazed"] = "Gain 2 Latinum.",
    ["Corvan II"] = "No effect.",
    ["Delta Vega"] = "No effect.",
    ["Dozaria"] = "Gain 3 Dilithium.",
    ["Indri VIII"] = " Gain an Action.",
    ["Risa"] = "Find up to 3 Persons, except in your Reserve deck, and beam them here.",
    ["Tulgana IV"] = "You may junk up to 2 cards from the Market.",
    ["Ba'ku"] = "You may beam any number of Person here from your hand or Discard pile.",
    ["Deep Space K-7"] = "No effect.",
    ["Derna"] = "You may spend 2 Dilithium to scan for either Weapon or Doctor. Draw a card.",
    ["Freecloud"] = "You may spend 1 Latinum to scan for Business.",
    ["Kelvas Docks"] = "No effect.",
    ["Memory Alpha"] = "You may log a card. You may duplicate a play operation of a Person / Cargo / Ally / Directive from your Log.",
    ["Regula I"] = "ou may find a Scientist OR you may spend 3 Dilithium to scan for Scientist.",
    ["Solum"] = "Take an Incident and put it on the bottom of your Draw deck.",
    ["Verex III"] = "Gain 1 Glory.",
    ["Xahea"] = "No effect.",

    -- TBG commons
    ["Argus Array"] = "No effect.",
    ["Cold Station 12"] = "You may beam a card from your hand or Discard pile here.",
    ["Denaxi Depot"] = "You may discard a card to send an Away Team here. If the discarded card is Business, gain 2 Latinum.",
    ["Tahal-Meeroj"] = "You may enlist a Reserve. Draw 2 cards.",
    ["Azati Prime"] = "You may put a card on the top of your deck to gain a Cargo/Ship. If the gained card is Weapon, gain 2 Glory.",
    ["Babel One"] = "No effect.",
    ["Khitomer"] = "You may free play a Starfleet.",
    ["Tanuga IV"] = "You may spend 3 Dilithium to scan for either a Scientist or a Weapon.",
    ["Tellar Prime"] = "No effect.",

    -- second contact locations
    ["Krulmuth-B"] = "You may take an Incident to scan for an Orion.",
    ["Orion"] = "You may spend 1 latinum to gain a Ship from the top of the deck, and free play it, if able.",
  }
  return controlActions[cardName]
end