-- contains functions related to the Neutral Zone actions


playerarea_color   = "Blue"
replace_drop_loc   = {0.00, 2.00, -7.00}
location_checkzone = getObjectFromGUID("65beaa")


function initButtonControlNZLocation(buttonObj)
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "controlNZLocation",
    function_owner = self,
    label          = "",
    position       = {0, 0.36, -0.01},
    width          = 865,
    height         = 435,
    scale          = {2.3, 2.3, 2.3},
    color          = {1, 1, 1, .3},
    hover_color    = {1, 1, 1, .6},
    tooltip        = "Clicking this button will control this location, return/dismiss away teams and ships, and replace the location if possible.\n\n[b]*[/b] It [b]does not[/b] check to make sure a control is allowed before doing so.",
  })
end


-- wrapper to handle all of the actions related to the control of a NZ location
function controlNZLocation(buttonObj, _, _)
  -- collect required info
  local playerColor = buttonObj.getGMNotes()
  local otherPlayerColor = playerColor == "Blue" and "Red" or "Blue"
  local buttonArea = (buttonObj.getName():find("Top") and "Top") or
                     (buttonObj.getName():find("Middle") and "Middle") or
                     (buttonObj.getName():find("Bottom") and "Bottom")
  local isBot = checkPlayerColorIsBot(playerColor)

  -- animate button
  animateButton(buttonObj)

  -- return playerColor away teams and ships
  returnPlayerNZObjects(buttonArea, playerColor, isBot)

  -- take controlled location, place to next free slot on playerColor location pad
  local controlledLocation = takeControlledLocation(buttonArea, playerColor, isBot)

  -- verify a controlled location was actually taken before proceeding
  if controlledLocation ~= nil then

    Wait.time(function()

      -- replace taken location
      local replacementLocation = replaceTakenLocation(buttonArea, playerColor, isBot)

      -- handle return & giving glory for otherPlayerColor ships & ATs
      local opposeCount = returnOtherPlayerNZObjects(buttonArea, otherPlayerColor, isBot)

      -- broadcast
      local playerStr = getPlayerStr(playerColor)
      local broadcastStr = ""
      if replacementLocation ~= nil then
        broadcastStr = string.format("%s has taken control of %s, which has been replaced with %s.", playerStr, controlledLocation, replacementLocation)
      else
        broadcastStr = string.format("%s has taken control of %s, which was not replaced.", playerStr, controlledLocation)
      end
      broadcastToAll(broadcastStr, "White")

    end, 0.5)
  else
    return
  end
end


function returnPlayerNZObjects(buttonArea, playerColor, isBot)
  -- handles return of playerColor away teams and ships

  local rotReturn = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posATReturn = playerColor == "Blue" and { -28.75, 2.00, 6.30 } or { 28.75, 2.00, -6.30 }
  local checkZone = getObjectbyNameAndNotes("Zone NZ Player " .. buttonArea, playerColor)
  for _, zoneObj in pairs(checkZone.getObjects()) do
    -- return away teams
    if zoneObj.hasTag('away_' .. string.lower(playerColor)) then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posATReturn, false, true)

    -- return ships
    elseif zoneObj.hasTag('snap_ship') then
      local shipObj = zoneObj
      local cardObj = getObjectbyNameAndType(shipObj.getName(), "Card")
      dismissShip(cardObj, shipObj)
    end
  end
end


function returnOtherPlayerNZObjects(buttonArea, otherPlayerColor, isBot)
  -- handle return & giving glory for otherPlayerColor ships & ATs

  local rotReturn = otherPlayerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = otherPlayerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posATReturn = otherPlayerColor == "Blue" and { -28.75, 2.00, 6.30 } or { 28.75, 2.00, -6.30 }
  local opposeCheckZone = getObjectbyNameAndNotes("Zone NZ Player " .. buttonArea, otherPlayerColor)
  local opposeCount = 0
  for _, zoneObj in pairs(opposeCheckZone.getObjects()) do

    -- return opposing away teams
    if zoneObj.hasTag('away_' .. string.lower(otherPlayerColor)) then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posATReturn, false, true)
      opposeCount = opposeCount + 1

    -- dismiss ships
    elseif zoneObj.hasTag('snap_ship') then
      local shipObj = zoneObj
      local cardObj = getObjectbyNameAndType(shipObj.getName(), "Card")
      dismissShip(cardObj, shipObj)
      opposeCount = opposeCount + 1
    end
  end

  -- handle the glory for the return of ATs and ships
  local isCadet = checkIsCadet()
  if opposeCount > 0 and not isCadet then
    local gloryCounter = getObjectbyName("Glory Counter " .. otherPlayerColor)

    -- Get current count of glory on stardate card
    local gloryOnStardateCount = 0
    local gloryCheckZone = getObjectbyName("Zone Stardate Glory")

    for _, object in pairs(gloryCheckZone.getObjects()) do
      if object.getName() == "Glory Token" then
        gloryOnStardateCount = gloryOnStardateCount + 1
      end
    end

    -- Calculate this synchronously, before any Wait.time()
    local diffCount = math.max(opposeCount - gloryOnStardateCount, 0)

    Wait.time(function()

      local playerStr = getPlayerStr(otherPlayerColor)
      local broadcastStr = string.format(
        "%s takes %s Glory, 1 for every dismissed ship or returned away team!.",
        playerStr,
        opposeCount
      )
      broadcastToAll(broadcastStr, "White")

      if gloryOnStardateCount >= opposeCount then
        for i = 1, opposeCount do
          local waitTimer = (i - 1) * 0.25

          Wait.time(function()
            gloryCounter.call('increaseValue')
          end, waitTimer)
        end

      else
        for i = 1, gloryOnStardateCount do
          local waitTimer = (i - 1) * 0.25

          Wait.time(function()
            gloryCounter.call('increaseValue')

            if i == gloryOnStardateCount then
              broadcastToAll(
                "Pausing Glory Allocation to refresh Stardate Card.",
                "Yellow"
              )
            end
          end, waitTimer)
        end

        Wait.time(function()
          for i = 1, diffCount do
            local waitTimer = (i - 1) * 0.25

            Wait.time(function()
              gloryCounter.call('increaseValue')
            end, waitTimer)
          end
        end, 3)
      end

    end, 1)
  end
  return opposeCount
end


function takeControlledLocation(buttonArea, playerColor, isBot)
  -- handles the taking of a controlled location, and the detection of the next free location slot position to place it
  -- returns either the found & placed NZ location card (for broadcast in wrapper), or, nil

  local controlledLocation = nil
  local replacementLocation = nil
  local nzCheckZone = getObjectbyName("Zone NZ Location " .. buttonArea)
  local locationCheckZone = getObjectbyNameAndNotes("Zone Deploy Location", playerColor)
  local rotReturn = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posSlots = playerColor == "Blue" and {
  { -30.00, 0.96,  2.46 },
  { -30.00, 0.96, -1.46 },
  { -30.00, 0.96, -5.37 },
  { -30.00, 0.96, -9.29 },
  { -30.00, 0.96, -13.21 },
  { -30.00, 0.96, -17.13 },
  { -30.00, 0.96, -21.04 },
} or {
  { 30.00, 0.96, -2.46 },
  { 30.00, 0.96,  1.46 },
  { 30.00, 0.96,  5.37 },
  { 30.00, 0.96,  9.29 },
  { 30.00, 0.96, 13.21 },
  { 30.00, 0.96, 17.13 },
  { 30.00, 0.96, 21.04 },
}

local locationSlots = {}

for i = 1, 7 do
  locationSlots[i] = false
end

for _, zoneObj in pairs(locationCheckZone.getObjects()) do
  if zoneObj.tag == "Card" then
    local pos = zoneObj.getPosition()

    for i, slot in ipairs(posSlots) do
      if math.abs(pos.z - slot[3]) < 0.5 then
        locationSlots[i] = true
        break
      end
    end
  end
end

local nextFreeSlot = 0

for i = 1, 7 do
  if not locationSlots[i] then
    nextFreeSlot = i
    break
  end
end

  -- overwrite posSlot default if nextFreeSlot is determined
  local posSlot = 7
  if nextFreeSlot ~= 0 then
    posSlot = posSlots[nextFreeSlot]
  end

  -- position card to slot
  for _, zoneObj in pairs(nzCheckZone.getObjects()) do
    if zoneObj.tag == "Card" then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posSlot, false, true)
      controlledLocation = zoneObj.getName()
    end
  end

  return controlledLocation
end


function replaceTakenLocation(buttonArea, playerColor, isBot)
  -- handles the replacement of a new location after a controlled location is taken
  -- returns either replacement card object (for wrapper broadcast), or, nil

  local rotReplacement = { 0.00, 180.00, 0.00 }
  local posNZs = {
    ["Top"]    = { 0.00, 2.00, -7.00 },
    ["Middle"] = { 0.00, 2.00, -14.00 },
    ["Bottom"] = { 0.00, 2.00, -21.00 },
  }
  local posReplacement = posNZs[buttonArea]

  local deckCheckZone = getObjectbyName("Zone Advanced Locations")
  local replacementCard = nil
  for _, zoneObj in pairs(deckCheckZone.getObjects()) do
    if zoneObj.type == "Deck" then
      replacementCard = zoneObj.takeObject()
      replacementCard.setRotation(rotReplacement)
      replacementCard.setPositionSmooth(posReplacement, false, true)

    elseif zoneObj.tag == "Card" then
      replacementCard = zoneObj
      replacementCard.setRotation(rotReplacement)
      replacementCard.setPositionSmooth(posReplacement, false, false)
    end
  end
  local replacementCardName = replacementCard ~= nil and replacementCard.getName() or nil
  return replacementCardName
end
