-- contains functions related to the Neutral Zone actions


playerarea_color   = "Blue"
replace_drop_loc   = {0.00, 2.00, -7.00}
location_checkzone = getObjectFromGUID("65beaa")


function initButtonControlNZLocation(buttonObj)
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "controlNZLocation",
    function_owner = self,
    label          = "",
    position       = {0, 0.36, -0.01},
    width          = 865,
    height         = 435,
    scale          = {2.3, 2.3, 2.3},
    color          = {1, 1, 1, .3},
    hover_color    = {1, 1, 1, .6},
    tooltip        = "Clicking this button will control this location, return/dismiss away teams and ships, and replace the location if possible.\n\n[b]*[/b] It [b]does not[/b] check to make sure a control is allowed before doing so.",
  })
end


-- wrapper to handle all of the actions related to the control of a NZ location
function controlNZLocation(buttonObj, clickerColor, _)
  -- collect required info
  local playerColor = buttonObj.getGMNotes()
  local otherPlayerColor = playerColor == "Blue" and "Red" or "Blue"
  local buttonArea = (buttonObj.getName():find("Top") and "Top") or
                     (buttonObj.getName():find("Middle") and "Middle") or
                     (buttonObj.getName():find("Bottom") and "Bottom")
  local isBot = checkPlayerColorIsBot(playerColor)

  -- animate button
  animateButton(buttonObj)

  -- return playerColor away teams and ships
  returnPlayerNZObjects(buttonArea, playerColor, isBot)

  -- take controlled location, place to next free slot on playerColor location pad
  local controlledLocation = takeControlledLocation(buttonArea, playerColor, isBot)

  -- verify a controlled location was actually taken before proceeding
  if controlledLocation ~= nil then

    Wait.time(function()

      -- replace taken location
      local replacementLocation = replaceTakenLocation(buttonArea, playerColor, isBot)

      -- handle return & giving glory for otherPlayerColor ships & ATs
      returnOtherPlayerNZObjects(buttonArea, otherPlayerColor, isBot)

      -- broadcast (see what's required)

    end, 0.5)
  else
    return
  end
end


function returnPlayerNZObjects(buttonArea, playerColor, isBot)
  -- handles return of playerColor away teams and ships

  local rotReturn = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posATReturn = playerColor == "Blue" and { -28.75, 2.00, 6.30 } or { 28.75, 2.00, -6.30 }
  local checkZone = getObjectbyNameAndNotes("Zone NZ Player " .. buttonArea, playerColor)
  for _, zoneObj in pairs(checkZone.getObjects()) do
    -- return away teams
    if zoneObj.hasTag('away_' .. string.lower(playerColor)) then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posATReturn, false, true)

    -- return ships
    elseif zoneObj.hasTag('snap_ship') then
      local shipObj = zoneObj
      local cardObj = getObjectbyNameAndType(shipObj.getName(), "Card")
      dismissShip(cardObj, shipObj)
    end
  end
end


function returnOtherPlayerNZObjects(buttonArea, otherPlayerColor, isBot)
  -- handle return & giving glory for otherPlayerColor ships & ATs

  local rotReturn = otherPlayerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = otherPlayerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posATReturn = otherPlayerColor == "Blue" and { -28.75, 2.00, 6.30 } or { 28.75, 2.00, -6.30 }
  local opposeCheckZone = getObjectbyNameAndNotes("Zone NZ Player " .. buttonArea, otherPlayerColor)
  local opposeCount = 0
  for _, zoneObj in pairs(opposeCheckZone.getObjects()) do

    -- return opposing away teams
    if zoneObj.hasTag('away_' .. string.lower(otherPlayerColor)) then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posATReturn, false, true)
      opposeCount = opposeCount + 1

    -- dismiss ships
    elseif zoneObj.hasTag('snap_ship') then
      local shipObj = zoneObj
      local cardObj = getObjectbyNameAndType(shipObj.getName(), "Card")
      dismissShip(cardObj, shipObj)
      opposeCount = opposeCount + 1
    end
  end

  -- handle the glory for the return of ATs and ships
  local isCadet = checkIsCadet()
  if opposeCount > 0 and not isCadet then
    local gloryCounter = getObjectbyName("Glory Counter " .. otherPlayerColor)
    Wait.time(function()

      -- broadcast
      local playerStr = getPlayerStr(otherPlayerColor)
      local broadcastStr = string.format("%s takes %s Glory, 1 for every dismissed ship or returned away team!.", playerStr, opposeCount)
      broadcastToAll(broadcastStr, "White")

      -- get current count of glory on stardate card (above card in this mod)
      local gloryOnStardateCount = 0
      local gloryCheckZone = getObjectbyName("Zone Stardate Glory")
      for _, object in pairs(gloryCheckZone.getObjects()) do
        if object.getName() == "Glory Token" then
          gloryOnStardateCount = gloryOnStardateCount + 1
        end
      end

      if gloryOnStardateCount >= opposeCount and opposeCount > 0 then
        for i = 1, opposeCount do
          local waitTimer = 0
          if i == 2 and opposeCount > 1 then
            waitTimer = .25
          elseif i == 3 and opposeCount > 2 then
            waitTimer = .50
          elseif i == 4 and opposeCount > 3 then
            waitTimer = .75
          elseif i == 5 and opposeCount > 4 then
            waitTimer = 1.00
          elseif i == 6 and opposeCount > 5 then
            waitTimer = 1.25
          elseif i == 7 and opposeCount > 6 then
            waitTimer = 1.50
          end
          Wait.time(function()

            -- gloryCounter.call('add_glory') -- REVISIT ON COUNTERS

          end, waitTimer)
        end
      elseif gloryOnStardateCount < opposeCount then
        for i = 1, gloryOnStardateCount do
          local waitTimer = 0
          if i == 2 then
            waitTimer = .25
          elseif i == 3 then
            waitTimer = .50
          elseif i == 4 then
            waitTimer = .75
          elseif i == 5 then
            waitTimer = 1.00
          elseif i == 6 then
            waitTimer = 1.25
          elseif i == 7 then
            waitTimer = 1.50
          end
          Wait.time(function()

            -- gloryCounter.call('add_glory') -- REVISIT ON COUNTERS

            if i == gloryOnStardateCount then
              broadcastToAll("Pausing Glory Allocation to refresh Stardate Card.", "Yellow")
            end

          end, waitTimer)
        end
        local diffCount = opposeCount - gloryOnStardateCount
        Wait.time(function()

          for i = 1, diffCount do
              local waitTimer = 0
              if i == 2 then
                  waitTimer = .25
              elseif i == 3 then
                  waitTimer = .50
              elseif i == 4 then
                  waitTimer = .75
              elseif i == 5 then
                  waitTimer = 1.00
              elseif i == 6 then
                  waitTimer = 1.25
              elseif i == 7 then
                  waitTimer = 1.50
              end
              Wait.time(function()

                -- gloryCounter.call('add_glory') -- REVISIT ON COUNTERS

              end, waitTimer)
          end

        end, 3)
      end

    end, 1)
  end
end


function takeControlledLocation(buttonArea, playerColor, isBot)
  -- handles the taking of a controlled location, and the detection of the next free location slot position to place it
  -- returns either the found & placed NZ location card (for broadcast in wrapper), or, nil

  local controlledLocation = nil
  local replacementLocation = nil
  local nzCheckZone = getObjectbyName("Zone NZ Location " .. buttonArea)
  local locationCheckZone = getObjectbyNameAndNotes("Zone Deploy Location", playerColor)
  local locationSlots = { false, false, false, false, false, false, false }
  local rotReturn = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  if isBot then
    rotReturn = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
  end
  local posSlots = playerarea_color == "Blue" and {
    { -30.00, 0.96, 2.46 },
    { -30.00, 0.96, -1.46 },
    { -30.00, 0.96, -5.37 },
    { -30.00, 0.96, -9.29 },
    { -30.00, 0.96, -13.21 },
    { -30.00, 0.96, -17.13 },
    { -30.00, 0.96, -21.04 },
  } or
  {
    { 30.00, 0.96, -2.46 },
    { 30.00, 0.96, 1.46 },
    { 30.00, 0.96, 5.37 },
    { 30.00, 0.96, 9.29 },
    { 30.00, 0.96, 13.21 },
    { 30.00, 0.96, 17.13 },
    { 30.00, 0.96, 21.04 },
  }
  local posSlot = posSlots[7] -- default to last available slot if in question

  -- determine next available slot via table of positional checks
  for i = 1, 7 do
    for _, zoneObj in pairs(locationCheckZone.getObjects()) do
      if zoneObj.tag == "Card" then
        local posObj = zoneObj.getPosition()
        if (posObj.z > 1.96 and posObj.z < 2.96) or (posObj.z < -1.96 and posObj.z > -2.96) then
          locationSlots[1] = true
        elseif (posObj.z > -1.96 and posObj.z < -0.96) or (posObj.z < 1.96 and posObj.z > 0.96) then
          locationSlots[2] = true
        elseif (posObj.z > -5.87 and posObj.z < -4.87) or (posObj.z < 5.87 and posObj.z > 4.87) then
          locationSlots[3] = true
        elseif (posObj.z >  -9.79 and posObj.z < -8.79) or (posObj.z < 9.79 and posObj.z > 8.79) then
          locationSlots[4] = true
        elseif (posObj.z > -13.71 and posObj.z < -12.71) or (posObj.z < 13.71 and posObj.z > 12.71) then
          locationSlots[5] = true
        elseif (posObj.z > -17.63 and posObj.z < -16.63) or (posObj.z < 17.63 and posObj.z > 16.63) then
          locationSlots[6] = true
        elseif (posObj.z > -21.54 and posObj.z < -20.54) or (posObj.z < 21.54 and posObj.z > 20.54) then
          locationSlots[7] = true
        end
      end
    end
  end

  local nextFreeSlot = 0
  for i = 1, 7 do
    if locationSlots[i] == false then
      nextFreeSlot = i
      break
    end
  end

  -- overwrite posSlot default if nextFreeSlot is determined
  if nextFreeSlot ~= 0 then
    posSlot = posSlots[nextFreeSlot]
  end

  -- position card to slot
  for _, zoneObj in pairs(nzCheckZone.getObjects()) do
    if zoneObj.tag == "Card" then
      zoneObj.setRotation(rotReturn)
      zoneObj.setPositionSmooth(posSlot, false, true)
      controlledLocation = zoneObj.getName()
    end
  end

  return controlledLocation
end


function replaceTakenLocation(buttonArea, playerColor, isBot)
  -- handles the replacement of a new location after a controlled location is taken
  -- returns either replacement card object (for wrapper broadcast), or, nil

  local rotReplacement = { 0.00, 180.00, 0.00 }
  local posNZs = {
    ["Top"]    = { 0.00, 2.00, -7.00 },
    ["Middle"] = { 0.00, 2.00, -14.00 },
    ["Bottom"] = { 0.00, 2.00, -21.00 },
  }
  local posReplacement = posNZs[buttonArea]

  local deckCheckZone = getObjectbyName("Zone Advanced Locations")
  local replacementCard = nil
  for _, zoneObj in pairs(deckCheckZone.getObjects()) do
    if zoneObj.type == "Deck" then
      replacementCard = zoneObj.takeObject()
      replacementCard.setRotation(rotReplacement)
      replacementCard.setPositionSmooth(posReplacement, false, true)

    elseif zoneObj.tag == "Card" then
      replacementCard = zoneObj
      replacementCard.setRotation(rotReplacement)
      replacementCard.setPositionSmooth(posReplacement, false, false)
    end
  end

  return replacementCard
end
