-- contains functions related to the Market buttons & actions



function initButtonTakeIncident(buttonObj)
  local tooltip = string.format("Clicking this button will take an Incident. \n\n[b][%s]***[-][/b]\nIf vs. a solo bot, right clicking this button will take an Incident for the bot.", Color.fromString("Orange"):toHex())
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "takeIncident",
    function_owner = self,
    label          = "",
    position       = { 0, 0.36, -0.01 },
    width          = 865,
    height         = 435,
    scale          = { 2.3, 2.3, 2.3 },
    color          = { 1, 1, 1, .3 },
    hover_color    = { 1, 1, 1, .6 },
    tooltip        = tooltip,
  })
end


function initButtonJunkCard(buttonObj)
  local suit = (buttonObj.getName():find("Person") and "Person") or
               (buttonObj.getName():find("Cargo") and "Cargo") or
               (buttonObj.getName():find("Ship") and "Ship") or
               (buttonObj.getName():find("Ally") and "Ally")
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "junkCard",
    function_owner = self,
    label          = "",
    position       = { 0, 0.36, -0.01 },
    width          = 865,
    height         = 435,
    scale          = { 2.3, 2.3, 2.3 },
    color          = { 1, 1, 1, .3 },
    hover_color    = { 1, 1, 1, .6 },
    tooltip        = "Clicking this button will junk the above " .. suit .. " Market card, destroy any glory left on it, and replace it if possible.",
  })
end


function initButtonTakeCard(buttonObj)
  local suit = (buttonObj.getName():find("Person") and "Person") or
               (buttonObj.getName():find("Cargo") and "Cargo") or
               (buttonObj.getName():find("Ship") and "Ship") or
               (buttonObj.getName():find("Ally") and "Ally")
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "takeCard",
    function_owner = self,
    label          = "",
    position       = { 0, 0.36, -0.01},
    width          = 865,
    height         = 435,
    scale          = { 2.3, 2.3, 2.3 },
    color          = { 1, 1, 1, .3 },
    hover_color    = { 1, 1, 1, .6 },
    tooltip        = "Clicking this button will take the above " .. suit .. " Market card, take any glory left on it, and replace it if possible.\n\nIf performing 'Take' action for bot, instead right click 'Gain To Deck' button to perform bot 'Take' action.",
  })
end


function initButtonGainCard(buttonObj)
  local suit = (buttonObj.getName():find("Person") and "Person") or
               (buttonObj.getName():find("Cargo") and "Cargo") or
               (buttonObj.getName():find("Ship") and "Ship") or
               (buttonObj.getName():find("Ally") and "Ally")
  local buttonType = (buttonObj.getName():find("Button Deck Gain Market")) and "toDeck" or
                     (buttonObj.getName():find("Button Discard Gain Market")) and "toDiscard"
  local tooltip = (buttonType == "toDeck" and "Clicking this button will gain the above " .. suit .. " Market card to [b]Deck[/b], take any Glory or Dilithium left on it, and replace it if possible.\n\nIf vs. a solo bot, right clicking this button will perform the 'Take' operation for the bot. (same as Gain To Deck)") or
                  (buttonType == "toDiscard" and "Clicking this button will gain the above " .. suit .. " Market card to [b]Discard[/b], take any Glory or Dilithium left on it, and replace it if possible.\n\nIf vs. a solo bot, right clicking this button will perform the 'Gain' operation for the bot. (same as Gain To Discard)") or "None"
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "gainCard",
    function_owner = self,
    label          = "",
    position       = { 0, 0.36, -0.01},
    width          = 865,
    height         = 435,
    scale          = { 2.3, 2.3, 2.3 },
    color          = { 1, 1, 1, .3 },
    hover_color    = { 1, 1, 1, .6 },
    tooltip        = tooltip,
  })
end


function initButtonAddResource(buttonObj)
  buttonObj.clearButtons()
  buttonObj.createButton({
    click_function = "placeResource",
    function_owner = self,
    label          = "",
    position       = { 0, 0.46, -0.01 },
    width          = 450,
    height         = 450,
    scale          = { 2.3, 2.3, 2.3 },
    color          = { 1, 1, 1, 0 },
    hover_color    = { 1, 1, 1, .4 },
    tooltip        = "Clicking this button will take a Glory Token from the appropriate location, and then place it (or Dilithium if Burnham) on the above Market Card, and run the 'Refresh For End Of Turn' button action for the clicker's player area.\n\nMake sure to discard all unwanted cards before using this button, as it will assume all cards left in hand are intended to be held for next turn!",
  })
end



function updateCounter(playerColor, resourceType, resources, mod)
  -- handles the update and broadcast of a resource counter
  -- provides a way to visually update and broadcast a counter receiving multiple resources,
  -- while avoiding the single line item multiple broadcasts
  -- will also handle animation movement of "resources to bag"
  -- resourceTypes: "Dilithium", "Latinum", "Glory"

  if #resources < 1 then return end

  local counterObj = getObjectbyName(resourceType .. " Counter " .. playerColor)
  if counterObj == nil then return end

  local minVal = 0
  local maxVal = 999
  local oldVal = counterObj.getVar("val")
  local newVal = math.max(minVal, math.min(maxVal, oldVal + (mod * #resources)))

  -- set val variable on counter
  counterObj.setVar("val", newVal)

  -- update counter XML
  local counterObjXML = counterObj.UI.getXmlTable()
  if #counterObjXML ~= 0 then -- should be unneccessary, but just in case...
    local uiElement = (resourceType == "Dilithium" and "dilithiumCounter") or
                      (resourceType == "Latinum" and "latinumCounter") or
                      (resourceType == "Glory" and "playerGloryCounter")
    counterObj.UI.setAttribute(uiElement, "text", tostring(newVal))
    local fontSizes = {
      ["Dilithium"] = (newVal < 10 and "130") or
                      ((newVal > 9 and newVal < 100) and "120") or
                      (newVal > 99 and "110"),
      ["Latinum"]   = (newVal < 10 and "325") or
                      ((newVal > 9 and newVal < 100) and "305") or
                      (newVal > 99 and "285"),
      ["Glory"]     = (newVal < 10 and "160") or
                      ((newVal > 9 and newVal < 100) and "150") or
                      (newVal > 99 and "140"),
    }
    local fontSize = fontSizes[resourceType]
    counterObj.UI.setAttribute(uiElement, "fontSize", fontSize)
    local textColor = "#FFFFFF"
    counterObj.UI.setAttribute(uiElement, "textColor", textColor)

    -- refresh on screen XML
    onloadXML()
  end

  -- animate the resource placement to bag appearance
  local posCounter = counterObj.getPosition()
  posCounter.y = posCounter.y + 0.5
  for _, resource in pairs(resources) do
    resource.setPositionSmooth(posCounter, false, true)
    Wait.time(function()
      resource.destruct()
    end, 0.3)
  end

  -- broadcast
  Wait.time(function()

    local playerStr = getPlayerStr(playerColor)
    local broadcastStr = string.format("%s Gained %s: %d (%d > %d)", playerStr, resourceType, #resources, oldVal, newVal)
    broadcastToAll(broadcastStr, "White")

  end, 1)
end


function takeIncident(buttonObj, clickerColor, altClick)
  -- handles the Incident Take button functionality

  animateButton(buttonObj)

  if clickerColor ~= "Blue" and clickerColor ~= "Red" then
    return
  end

  local playerColor
  if not altClick then
    playerColor = clickerColor
  elseif altClick then
    playerColor = clickerColor == "Blue" and "Red" or "Blue"
  end

  local isBot = checkPlayerColorIsBot(playerColor)

  if altClick and not isBot then
    altClick = false
    playerColor = clickerColor
  end

  local locTake
  local rotTake

  if not altClick then
    locTake = playerColor == "Blue" and { -54.00, 3.00, 0.00 } or { 54.00, 3.00, 0.00 }
    rotTake = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  else
    rotTake = playerColor == "Blue" and { 0.00, 90.00, 180.00 } or { 0.00, 270.00, 180.00 }
    locTake = playerColor == "Blue" and { -44.50, 3.00, 7.00 } or { 44.50, 3.00, -7.00 }
  end

  local card = nil
  local cardFound = false
  local incidentCheckZone = getObjectbyName("Zone Incident")
  for _, zoneObj in pairs(incidentCheckZone.getObjects()) do
    if zoneObj.hasTag("suit_incident") then
      if zoneObj.tag == "Deck" then
        card = zoneObj.takeObject()
      elseif zoneObj.tag == "Card" then
        card = zoneObj
      end

      card.setRotation(rotTake)
      card.setPositionSmooth(locTake, false, true)
      cardFound = true
      break
    end
  end

  -- broadcast
  local playerStr = getPlayerStr(playerColor)
  local broadcastStr = string.format("%s has taken an Incident.", playerStr)
  broadcastToAll(broadcastStr, "White")

  if not cardFound then
    broadcastToAll("Burn initiated!", "Orange")
    return nil
  end

  Wait.time(function()

    cardFound = false

    for _, zoneObj in pairs(incidentCheckZone.getObjects()) do
      if zoneObj.hasTag("suit_incident") then
        cardFound = true
        break
      end
    end

    if not cardFound then
      broadcastToAll("Burn initiated!", "Orange")
    end

  end, 1)
end


function junkCard(buttonObj, clickerColor, _)
  -- handles functionality associated with junk market card buttons

  if clickerColor ~= "Blue" and clickerColor ~= "Red" then 
    broadcastToAll("Please be seated at the Blue or Red side before using these buttons.", "Orange")
    return
  end

  animateButton(buttonObj)

  local cardSuit = (buttonObj.getName():find("Person") and "Person") or
                   (buttonObj.getName():find("Cargo") and "Cargo") or
                   (buttonObj.getName():find("Ship") and "Ship") or
                   (buttonObj.getName():find("Ally") and "Ally")
  local cardZone = getObjectbyName("Zone Market Current " .. cardSuit)
  local foundJunkTargetCard = nil
  local gloryCount = 0
  local dilithiumCount = 0
  local latinumCount = 0

  -- get card, resource count on card, error out if no card or resources found
  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      gloryCount = gloryCount + 1
    end
    if zoneObj.getName() == "Dilithium Token" then
      dilithiumCount = dilithiumCount + 1
    end
    if zoneObj.getName() == "Latinum Token" then
      latinumCount = latinumCount + 1
    end
    if zoneObj.hasTag("suit_" .. string.lower(cardSuit)) then
      foundJunkTargetCard = zoneObj
    end
  end
  if foundJunkTargetCard == nil then
    broadcastToAll("No " .. cardSuit .. " card found to Junk.", "Orange")
    return
  end
  if gloryCount > 0 or dilithiumCount > 0 or latinumCount > 0 then
    broadcastToAll("Market cards with Resource Tokens on them may only be junked via Stardate Card.", "Orange")
    return
  end

  -- if able to junk a found card with no resources, place found card to junk pile
  local rotCard = { 0.00, 180.00, 0.00 }
  local posJunk = { -12.50, 2.00, 12.00 }
  foundJunkTargetCard.setRotation(rotCard)
  foundJunkTargetCard.setPositionSmooth(posJunk, false, true)

  -- broadcast
  local suitColors = {
    ["Person"] = "BFA42C",
    ["Cargo"]  = "4173B4",
    ["Ship"]   = "C8C8C8",
    ["Ally"]   = "CD28C3",
  }
  local suitColor = suitColors[cardSuit]
  local clickerStr = getPlayerStr(clickerColor)
  local junkTargetCardName = foundJunkTargetCard.getName()
  local broadcastStr = string.format("%s has Junked [b][%s]%s[-][/b].", clickerStr, suitColor, junkTargetCardName)
  broadcastToAll(broadcastStr, "White")

  -- check to see if card can be replaced, do so if possible
  local deckZone = getObjectbyName("Zone Market " .. cardSuit)
  local posReplacements = {
    ["Person"] = { -7.50, 1.50, 6.00 },
    ["Cargo"]  = { -2.50, 1.50, 6.00 },
    ["Ship"]   = { 2.50, 1.50, 6.00 },
    ["Ally"]   = { 7.50, 1.50, 6.00 },
  }
  local posReplace = posReplacements[cardSuit]
  local replaceCard = nil
  Wait.time(function()

    for _, zoneObj in pairs(deckZone.getObjects()) do
      if zoneObj.type == "Deck" then
        replaceCard = zoneObj.takeObject()
        break
      elseif zoneObj.type == "Card" then
        replaceCard = zoneObj
        break
      end
    end

    -- if replacement card found, place to market slot
    if replaceCard ~= nil then
      replaceCard.setRotation(rotCard)
      replaceCard.setPosition(posReplace, false, true)

      -- broadcast replacement
      local replaceCardName = replaceCard.getName()
      local followupStr = string.format("It has been replaced with [b][%s]%s[-][/b].", suitColor, replaceCardName)
      broadcastToAll(followupStr, "White")
    end

  end, 0.5)
end


function takeCard(buttonObj, clickerColor, altClick)
  -- handles functionality associated with market take buttons
  -- will "Take" market card to hand, any resources on it, and will replace if possible
  -- "Take" = position market card to clickerColor handzone

  if clickerColor ~= "Blue" and clickerColor ~= "Red" then 
    broadcastToAll("Please be seated at the Blue or Red side before using these buttons.", "Orange")
    return
  end

  animateButton(buttonObj)

  local cardSuit = (buttonObj.getName():find("Person") and "Person") or
                   (buttonObj.getName():find("Cargo") and "Cargo") or
                   (buttonObj.getName():find("Ship") and "Ship") or
                   (buttonObj.getName():find("Ally") and "Ally")
  local cardZone = getObjectbyName("Zone Market Current " .. cardSuit)

  -- this isn't a button that the bot should be using, so if right click & bot in game, handle
  local botInGame = checkIsBot()
  if botInGame and altClick then
    local errorStr = "Bot 'Take' operation places Taken card to top of bot deck instead of taking to it's non existent hand. Instead, right click the 'Gain To Deck' button to perform bot 'Take' action."
    broadcastToAll(errorStr, "Orange")
    return
  elseif not botInGame and altClick then
    altClick = false
  end

  -- bot stuff out of the way, proceed to taking & positioning card, taking resources
  local rotTake = clickerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
  local posTake = clickerColor == "Blue" and { -54.00, 3.00, 0.00 } or { 54.00, 3.00, 0.00 }
  local takeCard = nil
  local gloryGroup = {}
  local dilithiumGroup = {}
  local latinumGroup = {}

  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.hasTag("suit_" .. string.lower(cardSuit)) then
      takeCard = zoneObj
      break
    end
  end
  if takeCard == nil then
    broadcastToAll("No " .. cardSuit .. " card found to Take.", "Orange")
    return
  end

  -- place taken card
  takeCard.setRotation(rotTake)
  takeCard.setPositionSmooth(posTake, false, true)

  -- broadcast Take
  local suitColors = {
    ["Person"] = "BFA42C",
    ["Cargo"]  = "4173B4",
    ["Ship"]   = "C8C8C8",
    ["Ally"]   = "CD28C3",
  }
  local suitColor = suitColors[cardSuit]
  local clickerStr = getPlayerStr(clickerColor)
  local takeCardName = takeCard.getName()
  local broadcastStr = string.format("%s has Taken [b][%s]%s[-][/b] to hand.", clickerStr, suitColor, takeCardName)
  broadcastToAll(broadcastStr, "White")

  -- handle on card resources
  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      table.insert(gloryGroup, zoneObj)
    elseif zoneObj.getName() == "Dilithium Token" then
      table.insert(dilithiumGroup, zoneObj)
    elseif zoneObj.getName() == "Latinum Token" then
      table.insert(latinumGroup, zoneObj)
    end
  end
  if #gloryGroup > 0 then
    updateCounter(clickerColor, "Glory", gloryGroup, 1)
  end
  if #dilithiumGroup > 0 then
    updateCounter(clickerColor, "Dilithium", dilithiumGroup, 1)
  end
  if #latinumGroup > 0 then
    updateCounter(clickerColor, "Latinum", latinumGroup, 1)
  end

  -- handle market suit replacement
  Wait.time(function()

    local deckZone = getObjectbyName("Zone Market " .. cardSuit)
    local replaceCard = nil
    local rotReplace = { 0.00, 180.00, 0.00 }
    local posReplacements = {
      ["Person"] = { -7.50, 1.50, 6.00 },
      ["Cargo"]  = { -2.50, 1.50, 6.00 },
      ["Ship"]   = { 2.50, 1.50, 6.00 },
      ["Ally"]   = { 7.50, 1.50, 6.00 },
    }
    local posReplace = posReplacements[cardSuit]
    for _, zoneObj in pairs(deckZone.getObjects()) do
      if zoneObj.type == "Deck" then
        replaceCard = zoneObj.takeObject()
        break
      elseif zoneObj.type == "Card" then
        replaceCard = zoneObj
        break
      end
    end
    if replaceCard ~= nil then
      replaceCard.setRotation(rotReplace)
      replaceCard.setPositionSmooth(posReplace, false, true)
    end

    -- broadcast replacement
    local replaceCardName = replaceCard.getName()
    local followupStr = string.format("It has been replaced with [b][%s]%s[-][/b].", suitColor, replaceCardName)
    broadcastToAll(followupStr, "White")

  end, 0.5)
end


function gainCard(buttonObj, clickerColor, altClick)
  -- handles functionality associated with market gain to deck & gain to discard buttons
  -- "Gain" action will either take facedown card to deck, or, faceup card to discard

  if clickerColor ~= "Blue" and clickerColor ~= "Red" then 
    broadcastToAll("Please be seated at the Blue or Red side before using these buttons.", "Orange")
    return
  end

  animateButton(buttonObj)

  local cardSuit = (buttonObj.getName():find("Person") and "Person") or
                   (buttonObj.getName():find("Cargo") and "Cargo") or
                   (buttonObj.getName():find("Ship") and "Ship") or
                   (buttonObj.getName():find("Ally") and "Ally")
  local cardZone = getObjectbyName("Zone Market Current " .. cardSuit)
  local buttonType = (buttonObj.getName():find("Button Deck Gain Market")) and "toDeck" or
                     (buttonObj.getName():find("Button Discard Gain Market")) and "toDiscard"

  -- this is a button the bot should be using, so, unlike Take it will handle altclick & botInGame
  local botInGame = checkIsBot()
  if altClick and not botInGame then altClick = false end

  local playerColor = clickerColor
  local nonClickerColor = clickerColor == "Blue" and "Red" or "Blue"
  if altClick then
    local isBot = checkPlayerColorIsBot(nonClickerColor)
    if isBot then playerColor = nonClickerColor end
  end
  local isBot = checkPlayerColorIsBot(playerColor)

  local rotGain = playerColor == "Blue" and { 0.00, 270.00, 180.00 } or { 0.00, 90.00, 180.00 }
  if altClick and isBot then rotGain = playerColor == "Blue" and { 0.00, 90.00, 180.00 } or { 0.00, 270.00, 180.00 } end
  if buttonType == "toDiscard" then
    rotGain = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
    if altClick and isBot then rotGain = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 } end
  end
  local posGainDeck = playerColor == "Blue" and { -44.50, 1.50, 7.00 } or { 44.50, 1.50, -7.00 }
  local posGainDiscard = playerColor == "Blue" and { -44.50, 1.50, -21.00 } or { 44.50, 1.50, 21.00 }
  local posGain = (buttonType == "toDeck" and posGainDeck) or (buttonType == "toDiscard" and posGainDiscard)
  local gainCard = nil
  local gloryGroup = {}
  local dilithiumGroup = {}
  local latinumGroup = {}

  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.hasTag("suit_" .. string.lower(cardSuit)) then
      gainCard = zoneObj
      break
    end
  end
  if gainCard == nil then
    broadcastToAll("No " .. cardSuit .. " card found to Gain.", "Orange")
    return
  end

  -- place gained card
  gainCard.setRotation(rotGain)
  gainCard.setPositionSmooth(posGain, false, true)

  -- broadcast Gain
  local suitColors = {
    ["Person"] = "BFA42C",
    ["Cargo"]  = "4173B4",
    ["Ship"]   = "C8C8C8",
    ["Ally"]   = "CD28C3",
  }
  local suitColor = suitColors[cardSuit]
  local clickerStr = getPlayerStr(clickerColor)
  local gainCardName = gainCard.getName()
  local broadcastStr = string.format("%s has Gained [b][%s]%s[-][/b] to %s.", clickerStr, suitColor, gainCardName, buttonType == "toDeck" and "Deck" or "Discard")
  broadcastToAll(broadcastStr, "White")

  -- handle on card resources
  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      table.insert(gloryGroup, zoneObj)
    elseif zoneObj.getName() == "Dilithium Token" then
      table.insert(dilithiumGroup, zoneObj)
    elseif zoneObj.getName() == "Latinum Token" then
      table.insert(latinumGroup, zoneObj)
    end
  end
  if #gloryGroup > 0 then
    updateCounter(playerColor, "Glory", gloryGroup, 1)
  end
  if #dilithiumGroup > 0 then
    updateCounter(playerColor, "Dilithium", dilithiumGroup, 1)
  end
  if #latinumGroup > 0 then
    updateCounter(playerColor, "Latinum", latinumGroup, 1)
  end

  -- handle market suit replacement
  Wait.time(function()

    local deckZone = getObjectbyName("Zone Market " .. cardSuit)
    local replaceCard = nil
    local rotReplace = { 0.00, 180.00, 0.00 }
    local posReplacements = {
      ["Person"] = { -7.50, 1.50, 6.00 },
      ["Cargo"]  = { -2.50, 1.50, 6.00 },
      ["Ship"]   = { 2.50, 1.50, 6.00 },
      ["Ally"]   = { 7.50, 1.50, 6.00 },
    }
    local posReplace = posReplacements[cardSuit]
    for _, zoneObj in pairs(deckZone.getObjects()) do
      if zoneObj.type == "Deck" then
        replaceCard = zoneObj.takeObject()
        break
      elseif zoneObj.type == "Card" then
        replaceCard = zoneObj
        break
      end
    end
    if replaceCard ~= nil then
      replaceCard.setRotation(rotReplace)
      replaceCard.setPositionSmooth(posReplace, false, true)
    end

    -- broadcast replacement
    local replaceCardName = replaceCard.getName()
    local followupStr = string.format("It has been replaced with [b][%s]%s[-][/b].", suitColor, replaceCardName)
    broadcastToAll(followupStr, "White")

  end, 0.5)
end






function placeResource(buttonObj, playerColor, altClick)
  -- handles the action of placing a resource to a market card, checking for stardate cards, everything associated with ending a turn

  -- get old Turn owner from junk pad GMNotes, set to new turn owner
  local padJunk = getObjectbyName("Pad Junk")
  local oldTurn = padJunk.getGMNotes()
  if oldTurn == "None" then return end -- game hasn't started yet

  animateButton(buttonObj)

  local otherPlayerColor = playerColor == "Blue" and "Red" or "Blue"
  local buttonName = buttonObj.getName()
  local cardSuit = (buttonName:find("Person") and "Person") or
                   (buttonName:find("Cargo") and "Cargo") or
                   (buttonName:find("Ship") and "Ship") or
                   (buttonName:find("Ally") and "Ally")

  -- check for stardate card in either player's area, broadcast & return out if so
  local stardateCheckZone = getObjectbyNameAndNotes("Zone Stardate Player", otherPlayerColor)
  local botInGame = checkIsBot()
  local botColor
  local humanColor = playerColor
  if altClick and botInGame then
    botColor, humanColor = getSoloColors()
    playerColor = botColor
    otherPlayerColor = humanColor
    stardateCheckZone = getObjectbyNameAndNotes("Zone Stardate Player", botColor)
  end
  local playerStr = getPlayerStr(playerColor)
  local otherPlayerStr = getPlayerStr(otherPlayerColor)

  -- mark junk pad with turn owner playerColor
  padJunk.setGMNotes(otherPlayerColor)

  for _, zoneObj in pairs(stardateCheckZone.getObjects()) do
    if string.find(zoneObj.getName(), "Stardate") then
      broadcastToAll("There is a Stardate card in play, it must be resolved before a resource may be placed here.", "Orange")
      return
    end
  end

  -- no stardate card found! moving on with cleanup
  -- if bot in game, and altClicked, cycle on screen bot control UI buttons, refresh human? or bot? play area
  if altClick and botInGame then
    UI.hide('bot_next_action_cleanup')
    Wait.time(function() UI.show('end_player_turn') end, 1)
    refreshPlayerArea(humanColor)
  end

  -- check for captain card
  local captainName = getCaptainName(playerColor)

  -- check if burnham
  local isBurnham = captainName == "Burnham" and true or false

  -- pull logic on where to grab glory from, from player counters
  local gloryCount = 0
  local gloryToken = nil
  local gloryCheckZone = getObjectbyName("Zone Stardate Glory")
  local stardateDeckCheckZone = getObjectbyName("Zone Stardate")
  for _, zoneObj in pairs(gloryCheckZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      gloryToken = zoneObj
      gloryCount = gloryCount + 1
    end
  end

  -- take stardate for opposing player if taking last glory
  if gloryCount == 1 then
    local stardateCard
    for _, zoneObj in pairs(stardateDeckCheckZone.getObjects()) do
      if zoneObj.type == "Card" then
        stardateCard = zoneObj
        stardateTriggerEndgame()

      elseif zoneObj.tag == "Deck" then
        stardateCard = zoneObj.takeObject()
        local stardateCardName = stardateCard.getName()
        local rotStardateCard = playerColor == "Blue" and { 0.00, 90.00, 0.00 } or { 0.00, 270.00, 0.00 }
        if (altClick and botInGame) or stardateCardName:find("Cadet") then
          rotStardateCard = playerColor == "Blue" and { 0.00, 270.00, 0.00 } or { 0.00, 90.00, 0.00 }
        end
        local posStardateCard = playerColor == "Blue" and { 24.00, 1.25, -15.00 } or { -24.00, 1.25, 15.00 }
        if stardateCardName:find("Cadet") then posStardateCard = playerColor == "Blue" and { -24.00, 1.25, 15.00 } or { 24.00, 1.25, -15.00 } end
        stardateCard.setRotation(rotStardateCard)
        stardateCard.setPositionSmooth(posStardateCard, false, true)

        local broadcastStr = string.format("%s has given [%s]%s[-] to %s.", playerStr, Color.fromString("Yellow"):toHex(), stardateCardName, otherPlayerStr)
        broadcastToAll(broadcastStr, "White")
      end
    end
  end

  -- if no glory found in zone, pull one from the bag
  if gloryToken == nil then
    gloryToken = getObjectbyName("Central Glory Token Bag").takeObject()
  end

  -- place found glory token (or dilithium)
  local posGlory = {
    ["Person"] = { x=-7.50, y=2.00, z=8.00 },
    ["Cargo"]  = { x=-2.50, y=2.00, z=8.00 },
    ["Ship"]   = { x=2.50, y=2.00, z=8.00 },
    ["Ally"]   = { x=7.50, y=2.00, z=8.00 },
  }
  local posDilithium_1 = {
    ["Person"] = { x=-8.75, y=2.00, z=8.00 },
    ["Cargo"]  = { x=-3.75, y=2.00, z=8.00 },
    ["Ship"]   = { x=1.25, y=2.00, z=8.00 },
    ["Ally"]   = { x=6.25, y=2.00, z=8.00 },
  }
  local posDilithium_2 = {
    ["Person"] = { x=-6.25, y=2.00, z=8.00 },
    ["Cargo"]  = { x=-1.25, y=2.00, z=8.00 },
    ["Ship"]   = { x=3.75, y=2.00, z=8.00 },
    ["Ally"]   = { x=8.75, y=2.00, z=8.00 },
  }
  local cardGloryCount = 0
  local cardZone = getObjectbyName("Zone Market Current " .. cardSuit)

  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      cardGloryCount = cardGloryCount + 1
    end
  end

  posGlory[cardSuit].z = posGlory[cardSuit].z - (cardGloryCount * 0.75)

  -- if not burnham, place glory to detected position
  if not isBurnham then

    -- check for too much Glory to neatly auto place, broadcast to do manual & return out if so
    if posGlory[cardSuit].z < 3.50 then
      local errorStr = string.format("Too much Glory on %s Card for scripting to place - pull and place manually!", cardSuit)
      broadcastStr(errorStr, "Orange")
      return
    end

    local rotGloryToken = { 0.00, 180.00, 180.00 }
    gloryToken.setRotation(rotGloryToken)
    gloryToken.setPositionSmooth(posGlory[cardSuit])
    gloryToken.interactable = true
    gloryToken.setLock(false)

  elseif isBurnham then
    -- remove the glory from stardate card before placing dilithium
    getObjectbyName("Central Glory Token Bag").putObject(gloryToken)
    local dilithiumCount = 0
    for _, object in pairs(cardZone.getObjects()) do
      if object.getName() == "Dilithium Token" then
        dilithiumCount = dilithiumCount + 1
      end
    end

    -- place dilithium to market card
    local posDilithiumCount = math.floor(dilithiumCount / 2)
    local posDilithium_1_Copy = {x = posDilithium_1[cardSuit].x, y = posDilithium_1[cardSuit].y, z = posDilithium_1[cardSuit].z - (posDilithiumCount * 1.00)}
    local posDilithium_2_Copy = {x = posDilithium_2[cardSuit].x, y = posDilithium_2[cardSuit].y, z = posDilithium_2[cardSuit].z - (posDilithiumCount * 1.00)}

    for i = 1, 2 do
      local posDilithium = (i == 1) and posDilithium_1_Copy or posDilithium_2_Copy

      -- check for too much Glory to neatly auto place, broadcast to do manual & return out if so
      if posDilithium_1_Copy.z < 4.00 then
        local broadcastStr = string.format("Too much Dilithium on %s Card for scripting to place, pull and place manually! (Glory has already been taken from Stardate Card.)", cardSuit)
        broadcastToAll(broadcastStr , "Orange")
        return
      end

      local dilithiumToken = getObjectbyName("Central Dilithium Bag").takeObject()
      dilithiumToken.setPositionSmooth(posDilithium, false, true)
    end
  end

  -- refresh human playerarea
  Wait.time(function()

    local buttonRefresh = getObjectbyName("Button Refresh Draw Deck " .. playerColor)
    refreshDrawDeck(buttonRefresh, _, false)

  end, 1)


  -- run human player ending turn refresh actions
  if (not altClick and botInGame) or not altClick then

    -- initiate bot stuff at end of human turn if bot in game
    UI.hide('end_player_turn')
    if not altClick and botInGame then
      botControlStep()
    end

    -- refresh human player area
    refreshPlayerArea(playerColor)

    Wait.time(function()

      -- get current deck dize and max hand size, determine difference, deal back up to max hand size
      local maxHandSize = getMaxHand(playerColor, captainName)
      local currentHand = Player[playerColor].getHandObjects()
      local handCount = #currentHand
      local dealCount = math.max(0, maxHandSize - handCount)

      local deckCheckZone = getObjectbyNameAndNotes("Zone Draw Deck", playerColor)
      local drawDeck, deckCount = nil, 0
      for _, zoneObj in pairs(deckCheckZone.getObjects()) do
        if zoneObj.type == "Deck" then
          drawDeck = zoneObj
          deckCount = #(drawDeck.getObjects())
          break
        elseif zoneObj.type == "Card" then
          drawDeck = zoneObj
          deckCount = 1
          break
        end
      end

      local buttonRefresh = getObjectbyName("Button Refresh Draw Deck " .. playerColor)
      if drawDeck and deckCount >= dealCount and dealCount > 0 then
        drawDeck.deal(dealCount, playerColor)

      elseif dealCount > 0 and deckCount > 0 then
        local partial = math.min(deckCount, dealCount)
        drawDeck.deal(partial, playerColor)
        Wait.time(function()

          refreshDrawDeck(buttonRefresh, _, true, 0)

        end, 0.25)

      elseif dealCount > 0 then
        refreshDrawDeck(buttonRefresh, _, false, dealCount)
      end

    end, 2)
  end

  -- check for Cleanup tag cards, broadcast reminder if any found
  if (altClick and not botInGame) or not altClick then
    local cleanupCheckZones = {
      getObjectbyNameAndNotes("Zone Duty Officer", playerColor),
      getObjectbyNameAndNotes("Zone Deploy Location", playerColor),
      getObjectbyNameAndNotes("Zone Deploy Ship", playerColor),
      getObjectbyNameAndNotes("Zone In Play", playerColor),
      getObjectbyNameAndNotes("Zone Captain", playerColor),
    }
    local matchCards = {}
    for i = 1, 4 do
      for _, zoneObj in pairs(cleanupCheckZones[i].getObjects()) do
        if zoneObj.hasTag('cleanup') then
          zoneObj.highlightOn(playerColor)
          table.insert(matchCards, zoneObj)
          Wait.time(function() zoneObj.highlightOff() end, 5)
        end
      end
    end
    if #matchCards > 0 then
      local headlineStr = string.format("%s Reminder - Current in play Clean-Up Step Cards:", playerStr)
      broadcastToAll(broadcastStr, "White")
      Wait.time(function()

        for i = 1, #matchCards do
          local bulletStr = string.format("[b][%s]*[-][/b]", Color.fromString(playerColor):toHex())
          broadcastToAll(matchCards[i].getName(), "White")
        end

      end, 0.5)
    end
  end

  -- broadcast
  local cardName = nil
  local resourceString = "1 Glory"
  if isBurnham then resourceString = "2 Dilithium" end
  for _, zoneObj in pairs(cardZone.getObjects()) do
    if zoneObj.type == "Card" then cardName = zoneObj.getName() end
  end
  local suitColors = {
    ["Person"] = "BFA42C",
    ["Cargo"]  = "4173B4",
    ["Ship"]   = "C8C8C8",
    ["Ally"]   = "CD28C3",
  }
  local suitColor = suitColors[cardSuit]

  local broadcastStr = string.format("%s has placed %s %s.", playerStr, resourceString, cardName ~= nil and " on " .. "[b]["..suitColor.."]"..cardName.."[-][/b]" or "")
  broadcastToAll(broadcastStr, "White")

  -- if turns enabled, end and pass turn
  if Turns.enable then
    local currentColor = Turns.turn_color
    local nextColor = currentColor == "Blue" and "Red" or "Blue"
    Turns.turn_color = nextColor
  else
    return
  end
end