-- Star Trek Captain's Chair
-- code by Nonprophet, which is why it sucks

require("Helpers")
require("OnloadSupport")



function onLoad()

  -- call this for each existing object since TTS doesn't do it
  for _, obj in ipairs(getObjects()) do
    onObjectSpawn(obj)
  end

  -- enable / disable non interactable objects
  local nonInt = false
  makeNonInteractable(nonInt)

  -- manually hide/show blue bot difficulty buttons, create buttons
  local botDifficultyButtonVisibility = false
  buttonSoloDifficultyVisibility(botDifficultyButtonVisibility)

  -- manually hide/show player area captain selection UI
  local captainSelectButtonVisibility = false
  buttonSelectCaptainVisibility(captainSelectButtonVisibility)

  -- manually hide/show stardate card glory counter (will be under current Main Setup Button)
  local stardateGloryCounterVisibility = false
  gloryStardateCounterVisibility(stardateGloryCounterVisibility)

  -- show & update stardate glory counter onLoad() if game is in progress
  gloryCounterStardateInProgress()

  -- display XML UI if captain has been selected
  onloadXML()

  -- broadcast welcome message if setup button exists
  broadcastWelcome()
end -- end onLoad()


function onObjectSpawn(obj)

end







function onObjectEnterContainer(container, object)
    -- keep highlighting consistent when away teams stack
    if container.hasTag('away_blue') and object.hasTag('away_blue') then
        container.highlightOn("Blue")
    end
    if container.hasTag('away_red') and object.hasTag('away_red') then
        container.highlightOn("Red")
    end
end -- end onObjectEnterContainer()


function onPlayerTurn(player, previous_player)
    if Turns.enable then
        local current_player = player.color
        local check_zones = current_player == "Blue" and {
            getObjectFromGUID("a9ca57"),
            getObjectFromGUID("2c336e"),
            getObjectFromGUID("fc7f21"),
            getObjectFromGUID("596317"),
        } or
        {
            getObjectFromGUID("818a7e"),
            getObjectFromGUID("77d0cb"),
            getObjectFromGUID("5103b2"),
            getObjectFromGUID("bf1e62"),
        }
        local match_cards = {}
        for i = 1, 4 do
            for _, object in pairs(check_zones[i].getObjects()) do
                if object.hasTag('resupply') then
                    object.highlightOn(current_player)
                    table.insert(match_cards, object)
                    Wait.time(function() object.highlightOff() end, 5)
                end
            end
        end
        if #match_cards > 0 then
            broadcastToAll("Reminder - Current in play Resupply Step Cards for " .. current_player .. " Player.", current_player)
            for i = 1, #match_cards do
                broadcastToAll(match_cards[i].getName(), "White")
            end
        end
    end
end -- end onPlayerTurn()


function animate_button(params)
    local button      = params.button
    local down_factor = .30
    if string.find(button.getName(), "Button Market Resource") then
        down_factor   = .19
    end
    local pos         = button.getPosition()
    pos.y             = pos.y - down_factor
    button.clearButtons()
    button.setPosition(pos)
    pos.y             = pos.y + down_factor
    button.setPositionSmooth(pos, false, false)
    Wait.time(function() button.call('create_button') end, .4)
end -- end animate_button(params)




