-- Star Trek Captain's Chair
-- code by Nonprophet, which is why it sucks

require("BeamedBags")
require("Helpers")
require("OnloadSupport")
require("SetupMarket")
require("SetupSolo")



function onLoad()
  -- call this for each existing object since TTS doesn't do it
  for _, obj in ipairs(getObjects()) do
    onObjectSpawn(obj)
  end

  -- enable / disable non interactable objects
  local nonInt = false
  makeNonInteractable(nonInt)

  -- manually hide/show blue bot difficulty buttons, create buttons
  local botDifficultyButtonVisibility = false
  buttonSoloDifficultyVisibility(botDifficultyButtonVisibility, "Both")

  -- manually hide/show player area captain selection UI
  local captainSelectButtonVisibility = true
  buttonSelectCaptainVisibility(captainSelectButtonVisibility)

  -- manually hide/show stardate card glory counter (will be under current Main Setup Button)
  local stardateGloryCounterVisibility = false
  gloryStardateCounterVisibility(stardateGloryCounterVisibility)

  -- show & update stardate glory counter onLoad() if game is in progress
  gloryCounterStardateInProgress()

  -- display XML UI if captain has been selected
  onloadXML()

  -- broadcast welcome message if setup button exists
  broadcastWelcome()
end -- end onLoad()


function onObjectSpawn(obj)
  -- handles on spawn actions

  -- handle beamed bag button/counter refresh
  if obj.getName() == "Beamed Cards" then
    obj.call("updateButtons")
  end

  -- handle creation of main setup game button
  if obj.getName() == "Button Setup Game" then
    initButtonSetupGame(obj)
  end

  -- handle creation of include promo setup button
  if obj.getName() == "Button Include Promos" and obj.getGMNotes() == "enabled" then
    initButtonDisablePromo(obj)
  elseif obj.getName() == "Button Include Promos" and obj.getGMNotes() == "disabled" then
    initButtonEnablePromo(obj)
  end

  -- handle creation of include second contact setup button
  if obj.getName() == "Button Include Second Contact" and obj.getGMNotes() == "enabled" then
    initButtonDisableSecondContact(obj)
  elseif obj.getName() == "Button Include Second Contact" and obj.getGMNotes() == "disabled" then
    initButtonEnableSecondContact(obj)
  end

  -- handle creation of market selection setup buttons
  if obj.getName() == "Button Market Base Game" and obj.getGMNotes() == "enabled" then
    initButtonDisableMarketBaseGame(obj)
  elseif obj.getName() == "Button Market Base Game" and obj.getGMNotes() == "disabled" then
    initButtonEnableMarketBaseGame(obj)
  end
  if obj.getName() == "Button Market To Boldly Go" and obj.getGMNotes() == "enabled" then
    initButtonDisableMarketTBG(obj)
  elseif obj.getName() == "Button Market To Boldly Go" and obj.getGMNotes() == "disabled" then
    initButtonEnableMarketTBG(obj)
  end
  if obj.getName() == "Button Market Mixed" and obj.getGMNotes() == "enabled" then
    initButtonDisableMarketMixed(obj)
  elseif obj.getName() == "Button Market Mixed" and obj.getGMNotes() == "disabled" then
    initButtonEnableMarketMixed(obj)
  end

  -- if solo VS button in position (lifted), handle creation of solo VS buttons
  if obj.getName():find("Setup For Solo") then
    local posObj = obj.getPosition()
    if posObj.y > 0 then
      initButtonSoloVS(obj)

      -- if solo BS button is enabled, lift and init Solo Difficulty buttons for playerColor
      if obj.getGMNotes() == "enabled" then
        local playerColor = obj.getName():find("Blue") and "Blue" or "Red"
        buttonSoloDifficultyVisibility(true, playerColor)
      end
    end
  end
end







function onObjectEnterContainer(container, object)
    -- keep highlighting consistent when away teams stack
    if container.hasTag('away_blue') and object.hasTag('away_blue') then
        container.highlightOn("Blue")
    end
    if container.hasTag('away_red') and object.hasTag('away_red') then
        container.highlightOn("Red")
    end
end -- end onObjectEnterContainer()


function onPlayerTurn(player, previous_player)
    if Turns.enable then
        local current_player = player.color
        local check_zones = current_player == "Blue" and {
            getObjectFromGUID("a9ca57"),
            getObjectFromGUID("2c336e"),
            getObjectFromGUID("fc7f21"),
            getObjectFromGUID("596317"),
        } or
        {
            getObjectFromGUID("818a7e"),
            getObjectFromGUID("77d0cb"),
            getObjectFromGUID("5103b2"),
            getObjectFromGUID("bf1e62"),
        }
        local match_cards = {}
        for i = 1, 4 do
            for _, object in pairs(check_zones[i].getObjects()) do
                if object.hasTag('resupply') then
                    object.highlightOn(current_player)
                    table.insert(match_cards, object)
                    Wait.time(function() object.highlightOff() end, 5)
                end
            end
        end
        if #match_cards > 0 then
            broadcastToAll("Reminder - Current in play Resupply Step Cards for " .. current_player .. " Player.", current_player)
            for i = 1, #match_cards do
                broadcastToAll(match_cards[i].getName(), "White")
            end
        end
    end
end -- end onPlayerTurn()


function animate_button(params)
    local button      = params.button
    local down_factor = .30
    if string.find(button.getName(), "Button Market Resource") then
        down_factor   = .19
    end
    local pos         = button.getPosition()
    pos.y             = pos.y - down_factor
    button.clearButtons()
    button.setPosition(pos)
    pos.y             = pos.y + down_factor
    button.setPositionSmooth(pos, false, false)
    Wait.time(function() button.call('create_button') end, .4)
end -- end animate_button(params)




