
function getObjectbyName(objName)
  for _, object in pairs(getObjects()) do
    if object.getName() == objName then
      return object
    end
  end
  return nil
end


function getObjectbyNameAndNotes(objName, objNotes)
  for _, object in pairs(getObjects()) do
    if object.getName() == objName and object.getGMNotes() == objNotes then
      return object
    end
  end
  return nil
end


function getObjectbyNameAndTag(objName, objTag)
  for _, object in pairs(getObjects()) do
    if object.getName() == objName and object.hasTag(objTag) then
      return object
    end
  end
  return nil
end


function getObjectFromBagbyName(objName, bag, objRot, objPos, moveSmooth)
  local returnObj = nil
  for _, bagObj in pairs(bag.getObjects()) do
    if bagObj.name == objName then
      local takeObj = bag.takeObject({ guid = bagObj.guid, rotation = objRot })
      returnObj = takeObj
      if moveSmooth then
        takeObj.setPositionSmooth(objPos, false, true)
      else
        takeObj.setPosition(objPos)
      end
    end
  end
  return returnObj
end


function getObjectbyNameAndType(objName, objType)
  local returnObj = nil
  for _, object in pairs(getObjects()) do
    if object.getName() == objName and object.type == objType then  
      returnObj = object
    end
  end
  return returnObj
end


function getPlayerStr(playerColor)
  -- handles the creation of playerStr for broadcasts

  local playerColorisBot = checkPlayerColorIsBot(playerColor)
  local playerStr = (Player[playerColor].steam_name ~= nil and not playerColorisBot) and string.format("[%s]%s[-]", Color.fromString(playerColor):toHex(), Player[playerColor].steam_name) or
                    string.format("[%s]%s %s[-]", Color.fromString(playerColor):toHex(), playerColor, playerColorisBot and "Bot" or "Player")
  return playerStr
end


function getPlayerColor(cardObj)
  -- handles the detection of which side a card is currently on, returns playerColor
    local playerColor = nil
    local blueZones = {
      getObjectbyNameAndNotes("Zone Deploy Ship", "Blue"),
      getObjectbyNameAndNotes("Zone Deploy Location", "Blue"),
    }
    local redZones = {
      getObjectbyNameAndNotes("Zone Deploy Ship", "Red"),
      getObjectbyNameAndNotes("Zone Deploy Location", "Red"),
    }
    for i = 1, 2 do
      for _, zoneObj in pairs(blueZones[i].getObjects()) do
        if cardObj == zoneObj then
          playerColor = "Blue"
        end
      end
      for _, zoneObj in pairs(redZones[i].getObjects()) do
        if cardObj == zoneObj then
          playerColor = "Red"
        end
      end
    end
    return playerColor
end


function checkPlayerColorIsBot(playerColor)
  -- checks and returns if a specified playerColor is currently in solo bot mode
  -- captain board pad's gmnotes specifies enabled (this color is a bot) or disabled (this color is human)
  local playerColorisBot = false
  local padCaptain = getObjectbyName("Pad Crew Board " .. playerColor)
  if padCaptain ~= nil then
    if padCaptain.getGMNotes() == "enabled" then
      playerColorisBot = true
    end
  end

  return playerColorisBot
end


function checkisBot()
  -- checks and returns if there is currently a solo bot in play
  local isBot = false
  if checkPlayerColorIsBot("Blue") or checkPlayerColorIsBot("Red") then
    isBot = true
  end
  return isBot
end


function checkIsCadet()
  -- handles check if current game mode is Cadet bot, checks stardate pad GMNotes

  local padStardate = getObjectbyName("Pad Stardate")
  local isCadet = false
  if padStardate.getGMNotes() == "Cadet" then isCadet = true end
  return isCadet
end


function animateButton(buttonObj)
  local downFactor = .30
  if string.find(buttonObj.getName(), "Button Market Resource") then
    downFactor = .19
  end
  local pos = buttonObj.getPosition()
  pos.y = pos.y - downFactor
  buttonObj.clearButtons()
  buttonObj.setPosition(pos)
  pos.y = pos.y + downFactor
  buttonObj.setPositionSmooth(pos, false, true)
  Wait.time(function()

    if buttonObj.getName():find("Button Control Location") then
      initButtonControlNZLocation(buttonObj)

    elseif buttonObj.getName() == "Button Pull Action Token" then
      initButtonPullActionToken(buttonObj)
    end

  end, .2)
end