-- functions to support required onLoad functionality, requiring keeps Global tidy


function makeNonInteractable(nonInt)
  -- handles enable or disable of non interactable objects
  for _, object in pairs(getObjects()) do
    -- non interactable objects
    if object.hasTag('non_int') and nonInt then
      object.interactable = false
    end
  end
end


function buttonSoloDifficultyVisibility(botDifficultyButtonVisibility, playerColor)
  -- will manually show solo difficulty buttons for debug purposes
  -- playerColor will be "Blue", "Red", or "Both"

  local botDifficultyButtons = {}
  for _, object in ipairs(getObjects()) do
    local name = object.getName()
    if name:match("^Button Solo .+ Blue$") or name:match("^Button Solo .+ Red$") then
      table.insert(botDifficultyButtons, object)
    end
  end

  for _, button in ipairs(botDifficultyButtons) do
    local name = button.getName()
    local isBlue = name:match("Blue$")
    local isRed = name:match("Red$")

    if playerColor == "Both" or
       (playerColor == "Blue" and isBlue) or
       (playerColor == "Red" and isRed) then

      local posButton = button.getPosition()

      if botDifficultyButtonVisibility then
        posButton.y = 0.95
        initButtonSoloDifficulty(button)
      else
        posButton.y = -2
        button.clearButtons()
      end

      button.setPosition(posButton)
    end
  end
end


function buttonSelectCaptainVisibility(captainSelectButtonVisibility)
  -- will manually show all captain select buttons for debug purposes
  local captainSelectButtons = {}
  for _, object in ipairs(getObjects()) do
    if object.getName():match("^Button Select .+$") or
       object.getName() == "Setup Random Basic" or object.getName() == "Setup Random Advanced" or
       object.getName() == "Setup Random Basic OR Advanced" or object.getName():find("Setup For Solo") then
      table.insert(captainSelectButtons, object)
    end
  end

  -- handle captain select buttons
  for _, button in ipairs(captainSelectButtons) do
    if button ~= nil then
      local posButton = button.getPosition()
      if not captainSelectButtonVisibility then
        posButton.y = -2
        button.clearButtons()
      else
        posButton.y = 0.95
        initButtonCaptainSelect(button)
      end
      button.setPosition(posButton)
    end
  end

  -- handle basic/advanced selection buttons
  for _, object in pairs(getObjects()) do
    if object.getName():find("Button Use Basic") or object.getName():find("Button Use Advanced") then
      local posObj = object.getPosition()
      if not captainSelectButtonVisibility then
        posObj.y = -2
        object.clearButtons()
      else
        posObj.y = 0.95
        if object.getGMNotes() == "enabled" and object.getName():find("Advanced") then
          initButtonDisableAdvanced(object)
        elseif object.getGMNotes() == "disabled" and object.getName():find("Advanced") then
          initButtonEnableAdvanced(object)
        elseif object.getGMNotes() == "enabled" and object.getName():find("Basic") then
          initButtonDisableBasic(object)
        elseif object.getGMNotes() == "disabled" and object.getName():find("Basic") then
          initButtonEnableBasic(object)
        end
      end
      object.setPosition(posObj)
    end
  end
end


function gloryStardateCounterVisibility(stardateGloryCounterVisibility)
  -- will manually show stardate glory counter for debug purposes
  -- SGC will probably be under main setup button if it still exists
  local stardateGloryCounter = getObjectbyName("Glory Counter Stardate")
  local posStardateGloryCounter = stardateGloryCounter.getPosition()
  if not stardateGloryCounterVisibility then
    posStardateGloryCounter.y = -2
  else
    posStardateGloryCounter.y = .85
  end
  stardateGloryCounter.setPosition(posStardateGloryCounter)
end


function showStardateGloryCounter()
  -- this should allow for showing and creation of stardate glory counter
  local counter = getObjectbyName("Glory Counter Stardate")
  local posCounter = counter.getPosition()
  posCounter.y = .85
  counter.setPosition(posCounter)
  Wait.time(function()

    counter.call("initCounterStardateGlory", counter)

  end, 1)
end


function gloryCounterStardateInProgress()
  -- this should show and update the stardate glory counter if game is in progress
  local zoneStardate = getObjectbyName("Zone Stardate")
  local stardateType = nil
  for _, object in pairs(zoneStardate.getObjects()) do
    if object.getName():find("2-Player") then
      stardateType = "twoPlayer"
    elseif object.getName():find("Cadet") then
      stardateType = "Cadet"
    elseif object.getName():find("Ensign") or object.getName():find("Captain") then
      stardateType = "Ensign"
    elseif object.getName():find("Lieutenant") then
      stardateType = "Lieutenant"
    elseif object.getName():find("Commander") then
      stardateType = "Commander"
    elseif object.getName():find("Admiral") then
      stardateType = "Admiral"
    end
  end

  -- get glory count in zone, update counter
  local gloryCount = 0
  for _, object in pairs(getObjectbyName("Zone Stardate Glory").getObjects()) do
    if object.getName() == "Glory Token" then
      gloryCount = gloryCount + 1
    end
  end
  if stardateType ~= nil then -- game is in progress, or, stardate cards no longer in play, either or
    showStardateGloryCounter()
    getObjectbyName("Glory Counter Stardate").call('updateVal', gloryCount)
  end
end


function onLoadEnableTurns()
  -- handles enabling Turns mode & setting turn to correct player onload

  -- first, check if there is a current turn via Junk Pad GMNotes check
  local padJunk = getObjectbyName("Pad Junk")
  local currentTurnOwner = "None"
  if padJunk.getGMNotes() == "None" then
    return
  else
    currentTurnOwner = padJunk.getGMNotes()
  end

  -- if so, check if playerCount > 1 and set turn owner
  local seatedPlayers = getSeatedPlayers()
  if #seatedPlayers > 1 then
    Turns.enable = true
    Turns.turn_color = currentTurnOwner
  end
end


function onloadXML()
  -- handles required XML updates in case of a reload or rewind
  local colors = {"Blue", "Red"}
  for i = 1, 2 do
    local playerColor = colors[i]
    local isBot = checkIsBot()
    local captainName = getCaptainName(playerColor)
    if captainName == "None" then return end

    Wait.time(function()
      local dilithiumVal = getObjectbyName("Dilithium Counter " .. playerColor).getVar("val")
      local latinumVal = getObjectbyName("Latinum Counter " .. playerColor).getVar("val")
      local gloryVal = getObjectbyName("Glory Counter " .. playerColor).getVar("val")
      local influenceVal
      local militaryVal
      local researchVal
      if captainName ~= "Khan" then
        influenceVal = getObjectbyName("Influence Counter " .. playerColor).getVar("val")
        militaryVal = getObjectbyName("Military Counter " .. playerColor).getVar("val")
        researchVal = getObjectbyName("Research Counter " .. playerColor).getVar("val")
      end

      Wait.frames(function()

        if captainName == "Burnham" or captainName == "Picard" or captainName == "Sisko" or
           captainName == "Archer" or captainName == "Georgiou" or captainName == "Kirk" or
           captainName == "Freeman" or captainName == "Pike" or captainName == "Riker" then
          UI.setAttribute(playerColor == "Blue" and "blue_starfleet_panel" or "red_starfleet_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_hum_glory" or "red_hum_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_hum_latinum" or "red_hum_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_hum_dilithium" or "red_hum_dilithium", "text", dilithiumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_hum_influence" or "red_hum_influence", "text", influenceVal)
          UI.setAttribute(playerColor == "Blue" and "blue_hum_military" or "red_hum_military", "text", militaryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_hum_research" or "red_hum_research", "text", researchVal)

        elseif captainName == "Shran" then
          UI.setAttribute(playerColor == "Blue" and "blue_andorian_panel" or "red_andorian_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_and_glory" or "red_and_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_and_latinum" or "red_and_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_and_dilithium" or "red_and_dilithium", "text", dilithiumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_and_influence" or "red_and_influence", "text", influenceVal)
          UI.setAttribute(playerColor == "Blue" and "blue_and_military" or "red_and_military", "text", militaryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_and_research" or "red_and_research", "text", researchVal)

        elseif captainName == "Sela" then
          UI.setAttribute(playerColor == "Blue" and "blue_romulan_panel" or "red_romulan_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_rom_glory" or "red_rom_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_rom_latinum" or "red_rom_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_rom_dilithium" or "red_rom_dilithium", "text", dilithiumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_rom_influence" or "red_rom_influence", "text", influenceVal)
          UI.setAttribute(playerColor == "Blue" and "blue_rom_military" or "red_rom_military", "text", militaryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_rom_research" or "red_rom_research", "text", researchVal)

        elseif captainName == "Koloth" then
          UI.setAttribute(playerColor == "Blue" and "blue_klingon_panel" or "red_klingon_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_kli_glory" or "red_kli_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kli_latinum" or "red_kli_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kli_dilithium" or "red_kli_dilithium", "text", dilithiumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kli_influence" or "red_kli_influence", "text", influenceVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kli_military" or "red_kli_military", "text", militaryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kli_research" or "red_kli_research", "text", researchVal)

        elseif captainName == "Khan" then
          UI.setAttribute(playerColor == "Blue" and "blue_khan_panel" or "red_khan_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_kha_glory" or "red_kha_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kha_latinum" or "red_kha_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_kha_dilithium" or "red_kha_dilithium", "text", dilithiumVal)

        elseif captainName == "Rebner" then
          UI.setAttribute(playerColor == "Blue" and "blue_pakled_panel" or "red_pakled_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_pak_glory" or "red_pak_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_pak_latinum" or "red_pak_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_pak_dilithium" or "red_pak_dilithium", "text", dilithiumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_pak_influence" or "red_pak_influence", "text", influenceVal)
          UI.setAttribute(playerColor == "Blue" and "blue_pak_military" or "red_pak_military", "text", militaryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_pak_research" or "red_pak_research", "text", researchVal)

        elseif captainName == "Soval" then
          UI.setAttribute(playerColor == "Blue" and "blue_vulcan_panel" or "red_vulcan_panel", "active", "true")
          UI.setAttribute(playerColor == "Blue" and "blue_vul_glory" or "red_vul_glory", "text", gloryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_vul_latinum" or "red_vul_latinum", "text", latinumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_vul_dilithium" or "red_vul_dilithium", "text", dilithiumVal)
          UI.setAttribute(playerColor == "Blue" and "blue_vul_influence" or "red_vul_influence", "text", influenceVal)
          UI.setAttribute(playerColor == "Blue" and "blue_vul_military" or "red_vul_military", "text", militaryVal)
          UI.setAttribute(playerColor == "Blue" and "blue_vul_research" or "red_vul_research", "text", researchVal)
        end

        if captainName ~= nil and Player[playerColor].seated then
          UI.show(playerColor == "Blue" and "ui_hide_blue" or "ui_hide_red")
        end

      end)

    end, 0.5)

    -- show solo control buttons
    if isBot then
      UI.setAttribute("bot_controls", "active", "true")
      UI.setAttribute('bot_discard', 'active', 'true')
      UI.setAttribute('bot_discard_x3', 'active', 'true')
      UI.setAttribute('bot_log', 'active', 'true')
      UI.setAttribute('bot_incident', 'active', 'true')

      local buttonNextAction = getObjectbyName("Button Next Bot Action")
      if buttonNextAction.getGMNotes() == "Control" then
        UI.setAttribute('end_player_turn', 'active', 'true')
      elseif buttonNextAction.getGMNotes() == "Action" then
        UI.setAttribute('bot_next_action_action', 'active', 'true')
      elseif buttonNextAction.getGMNotes() == "Cleanup" then
        UI.setAttribute('bot_next_action_cleanup', 'active', 'true')
      end
    end
  end
end


function broadcastWelcome()
  -- handles broadcast of welcome message on load if main setup button still exists
  if getObjectbyName("Button Setup Game") ~= nil then
    local broadcastStr = "Welcome to Star Trek: Captain's Chair! Select Market & Promo options, then, use the 'Setup Game' button at the center of the table to get started."
    broadcastToAll(broadcastStr, "White")
  end
end