-- FROM SHIP OBJECT:
-- ship_bag = getObjectFromGUID("82424c")

-- function create_deploy_button()
--   ship_bag.call('create_deploy_button', {card=self})
-- end


-- function remove_deploy_button(params)
--   playerarea_color = params.playerarea_color
--   ship_bag.call('remove_deploy_button', {card=self, playerarea_color=playerarea_color})
-- end -- end remove_deploy_button()

-- function create_dismiss_button()
--   ship_bag.call('create_dismiss_button', {card=self})
-- end


-- function remove_dismiss_button(params)
--   playerarea_color = params.playerarea_color
--   ship_bag.call('remove_dismiss_button', {card=self, playerarea_color=playerarea_color})
-- end



-- FROM SHIP BAG


-- DO WE NEED A DEPLOY BUTTON?!

-- function createDeployButton(cardObj)
--   -- handles XML injection and button creation of Ship Card Deploy buttons

--   local playerColor = getPlayerColor(cardObj)
--   local assetURL = playerColor == "Blue"
--     and "https://steamusercontent-a.akamaihd.net/ugc/25435380746010187/614515234F3B92A1FCCF2DC3DD02A9B0D5A1E74D/"
--     or "https://steamusercontent-a.akamaihd.net/ugc/25435380746009590/4212AD86F0C701E59AA1C2BC0A4D442B5C816091/"

--   cardObj.UI.setCustomAsset({
--     {
--       name = "Deploy " .. playerColor,
--       url = assetURL
--     }
--   })

--   cardObj.UI.setXmlTable({
--     {
--       tag = "Panel",
--       attributes = {
--         id = "deploy_ship_button",
--         height = "30",
--         width = "63",
--         position = "70 -30 -25",
--         rotation = "0 0 180",
--         showAnimation = "Grow",
--         hideAnimation = "Shrink",
--         animationDuration = ".25"
--       },
--       children = {
--         {
--           tag = "Button",
--           attributes = {
--             onClick = "deploy_ship(" .. cardObj.getGUID() .. ")",
--             image = "Deploy " .. playerColor
--           }
--         }
--       }
--     }
--   })
-- end

-- function removeDeployButton(cardObj)
--   local currentXML = cardObj.UI.getXmlTable()
--   if currentXML ~= {} then
--     cardObj.UI.hide("deploy_ship_button")
--   end
-- end


function createDismissButton(cardObj)
  -- handles XML injection and button creation of Ship Card Dismiss buttons

  local playerColor = getPlayerColor(cardObj)

  local assetURL = playerColor == "Blue"
    and "https://steamusercontent-a.akamaihd.net/ugc/25437998677358449/B55638917979DF06CF735E5EC9C2908A11480C0D/"
    or "https://steamusercontent-a.akamaihd.net/ugc/25437998677358871/850E7BC0248AB1C7DF2EDF04E828862585D1CBDA/"

  cardObj.UI.setCustomAssets({
    {
      name = "Dismiss " .. playerColor,
      url = assetURL
    }
  })

  cardObj.UI.setXmlTable({
    {
      tag = "Panel",
      attributes = {
        id                = "dismiss_ship_button",
        height            = "30",
        width             = "63",
        position          = "70 -30 -25",
        rotation          = "0 0 180",
        showAnimation     = "Grow",
        hideAnimation     = "Shrink",
        animationDuration = ".25"
      },
      children = {
        {
          tag = "Button",
          attributes = {
            onClick = "Global/dismissShipFromCard(" .. cardObj.getGUID() .. ")",
            image = "Dismiss " .. playerColor
          }
        }
      }
    }
  })
end

function removeDismissButton(cardObj)
  local currentXML = cardObj.UI.getXmlTable()
  if currentXML ~= {} then
    cardObj.UI.hide("dismiss_ship_button")
  end
end


function deployShipViaPad(value)
  deployShip(_, value, _)
end

function deployShip(_, value, _)
  -- handles the deployment of Ship Figure via XML on card click
  local shipCard = getObjectFromGUID(value)
  local rotShipCard = shipCard.getRotation()
  if rotShipCard.y < 271 and rotShipCard.y > 269 then
    rotShipCard.y = 90
  elseif rotShipCard.y < 91 and rotShipCard.y > 89 then
    rotShipCard.y = 270
  end
  local posCard = shipCard.getPosition()
  local foundShip = nil
  local playerColor = getPlayerColor(shipCard)
  local isSolo = checkPlayerColorIsSolo(playerColor)
  if (playerColor == "Blue" and isSolo) or (playerColor == "Red" and isSolo) then
    posCard.x = posCard.x + (playerColor == "Blue" and -1.50 or 1.50)
  else
    posCard.x = posCard.x + (playerColor == "Blue" and 1.50 or -1.50)
  end

  local bagShipFigures = getObjectbyName("Ship Figurine Bag")
  for _, bagObj in pairs(bagShipFigures.getObjects()) do
    if bagObj.name == shipCard.getName() then
      foundShip = bagShipFigures.takeObject({ guid = bagObj.guid })
      break
    end
  end

  if foundShip == nil then
    local spaceDock = getObjectbyNameAndNotes("Space Dock", playerColor)
    for _, dockObj in pairs(spaceDock.getObjects()) do
      if dockObj.name == shipCard.getName() then
        foundShip = spaceDock.takeObject( { guid = dockObj.guid })
        break
      end
    end
  end

  if foundShip ~= nil and playerColor ~= nil then
    -- handle broadcast
    local playerStr = getPlayerStr(playerColor)
    local broadcastStr = string.format("%s has deployed %s.", playerStr, foundShip.getName())
    broadcastToAll(broadcastStr, "White")

    -- place ship figure foundShip
    foundShip.setRotation(rotShipCard)
    posCard.y = 1.25
    foundShip.setPositionSmooth(posCard, false, true)

    -- tint, highlight appropriately for playerColor or if cloaked
    if shipCard.hasTag('trait_cloak') then
      foundShip.setDescription('Cloaked')
      foundShip.highlightOn("Purple")
      foundShip.setColorTint(playerColor)

    elseif not shipCard.hasTag('trait_cloak') then
      foundShip.setDescription("")
      foundShip.highlightOn(playerColor)
      foundShip.setColorTint(playerColor)
    end
  end
end


function dismissShipFromCard(_, value, _)
  local cardObj = getObjectFromGUID(value)

  log("running dismissShipFromCard() on" .. cardObj.getName())

  local shipName = cardObj.getName()
  local shipObj = nil
  for _, object in pairs(getObjects()) do
    if object.getName() == shipName and object.hasTag('snap_ship') then
      shipObj = object
      break
    end
  end
  if shipObj ~= nil then
    dismissShip(cardObj, shipObj)
  else
    broadcastToAll("Ship is not found in play, please dismiss ship manually.", "Orange")
    return
  end
end

function dismissShip(cardObj, shipObj)
  -- handles the dismissal of a ship and any beamed cards at it's slot
  local shipName = cardObj.getName()
  local beamBagGUIDs = {
    shipBlue     = {"f3ac62", "acf736", "f8fc03", "5807b2", "d57c5c", "9d0439", "ff0165"},
    locationBlue = {"26a5c6", "ca88c0", "40b578", "eeadbe", "7a7548", "397e6d", "ce11ad"},
    shipRed      = {"95dff1", "30048e", "910a26", "9e394f", "392caa", "c32b20", "b5d6f9"},
    locationRed  = {"7f4770", "577602", "82a5c5", "4f12e8", "351f79", "efdbd0", "cf1df7"},
  }

  removeDismissButton(cardObj)

  -- get position of ship card, determine playerColor, row & slot # from it
  local posCard = cardObj.getPosition()
  local playerColor = getPlayerColor(cardObj)
  local row = nil -- "shipBlue", "locationBlue", "shipRed", "locationRed"
  local slot = nil -- 1-7
  if posCard.x > -39.50 and posCard.x < -37.50 then
    playerColor = "Blue"
    row = "shipBlue"
  elseif posCard.x > -31.00 and posCard.x < -29.00 then
    playerColor = "Blue"
    row = "locationBlue"
  elseif posCard.x < 39.50 and posCard.x > 37.50 then
    playerColor = "Red"
    row = "shipRed"
  elseif posCard.x < 31.00 and posCard.x > 29.00 then
    playerColor = "Red"
    row = "locationRed"
  end

  -- determine corresponding beam bag
  if (posCard.z > 1.47 and posCard.z < 3.47) or (posCard.z < -1.47 and posCard.z > -3.47) then
    slot = 1
  elseif (posCard.z > -2.45 and posCard.z < -0.45) or (posCard.z < 2.45 and posCard.z > 0.45) then
    slot = 2
  elseif (posCard.z > -6.36 and posCard.z < -4.36) or (posCard.z < 6.36 and posCard.z > 4.36) then
    slot = 3
  elseif (posCard.z > -10.28 and posCard.z < -8.28) or (posCard.z < 10.28 and posCard.z > 8.28) then
    slot = 4
  elseif (posCard.z > -14.20 and posCard.z < -12.20) or (posCard.z < 14.20 and posCard.z > 12.20) then
    slot = 5
  elseif (posCard.z > -18.12 and posCard.z < -16.12) or (posCard.z < 18.12 and posCard.z > 16.12) then
    slot = 6
  elseif (posCard.z > -22.00 and posCard.z < -20.00) or (posCard.z < 22.00 and posCard.z > 20.00) then
    slot = 7
  end

  -- send ship figure to space dock bag (remove this functionality when calling this in control location buttons)
  getObjectbyNameAndNotes("Space Dock", playerColor).putObject(shipObj)

  -- broadcast
  local playerStr = getPlayerStr(playerColor)
  local broadcastStr = string.format("%s has dismissed %s.", playerStr, cardObj.getName())
  broadcastToAll(broadcastStr, "White")

  -- send ship card to discard
  local rotDiscard = playerColor == "Blue" and {0.00, 270.00, 0.00} or {0.00, 90.00, 0.00}
  if checkPlayerColorIsSolo(playerColor) then
    rotDiscard = playerColor == "Blue" and {0.00, 90.00, 0.00} or {0.00, 270.00, 0.00}
  end
  local posDiscard = playerColor == "Blue" and {-44.57, 1.50, -21.00} or {44.57, 1.50, 21.00}

  cardObj.setRotation(rotDiscard)
  cardObj.setPositionSmooth(posDiscard, false, true)

  -- trigger beam bag cleanout button
  local beamBag = getObjectFromGUID(beamBagGUIDs[row][slot])
  for i = 1, #beamBag.getObjects() do
    local bagObj = beamBag.takeObject({ rotation = rotDiscard })
    bagObj.setPositionSmooth(posDiscard, false, true)
  end
end