-- handles functionality related to the Stardate & Glory area

-- is this even needed?
-- function initButtonRefreshGlory(buttonObj)
--   buttonObj.clearButtons()
--   buttonObj.createButton({
--     click_function = "refresh_glory",
--     function_owner = self,
--     label          = "",
--     position       = {0, 0.36, -0.01},
--     width          = 865,
--     height         = 435,
--     scale          = {2.3, 2.3, 2.3},
--     color          = {1, 1, 1, .3},
--     hover_color    = {1, 1, 1, .6},
--     tooltip        = "Clicking this button will refresh the glory after a new stardate card is revealed.",
--   })
-- end

-- wrapper to handle call (again, is needed if not using button??)
-- function runRefreshGlory(playerColor)
--   refreshGlory(_, playerColor, _)
-- end


function refreshGlory()
  -- handles functionality of refreshing the glory to glory area, counter etc per stardate card

  -- animate button click (is needed?)
  -- animateButton(getObjectbyName("Button Refresh Glory"))

  -- first check to make sure drop area isn't already populated
  local checkZone = getObjectbyName("Zone Stardate Glory")
  local gloryFound = false
  for _, zoneObj in pairs(checkZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      gloryFound = true
    end
  end
  if gloryFound then
    broadcastToAll("Refresh Glory Action only works while Stardate card is out of glory.", "Orange")
    return
  end

  -- determine cardName
  local cardName = nil
  for _, object in pairs(getObjectbyName("Zone Stardate").getObjects()) do
    if object.tag == "Deck" then -- if deck, get top card
      local cardsInDeck = object.getObjects()
      cardName = cardsInDeck[#cardsInDeck].name
    elseif object.tag == "Card" then
      cardName = object.getName()
    end
  end

  -- determine glory count to refresh per card name
  local cardGloryCounts = {
    ["2-Player Stardate 1"]                = 5,
    ["2-Player Stardate 2"]                = 7,
    ["2-Player Stardate 3"]                = 7,
    ["2-Player Stardate 4"]                = 6,
    ["2-Player Stardate 5"]                = 5,
    ["Solo Cadet Practice 1"]              = 5,
    ["Solo Cadet Practice 2"]              = 5,
    ["Solo vs. Ensign Bot Stardate 1"]     = 6,
    ["Solo vs. Ensign Bot Stardate 2"]     = 7,
    ["Solo vs. Ensign Bot Stardate 3"]     = 7,
    ["Solo vs. Ensign Bot Stardate 4"]     = 6,
    ["Solo vs. Ensign Bot Stardate 5"]     = 5,
    ["Solo vs. Lieutenant Bot Stardate 1"] = 5,
    ["Solo vs. Lieutenant Bot Stardate 2"] = 7,
    ["Solo vs. Lieutenant Bot Stardate 3"] = 7,
    ["Solo vs. Lieutenant Bot Stardate 4"] = 6,
    ["Solo vs. Lieutenant Bot Stardate 5"] = 5,
    ["Solo vs. Commander Bot Stardate 1"]  = 5,
    ["Solo vs. Commander Bot Stardate 2"]  = 7,
    ["Solo vs. Commander Bot Stardate 3"]  = 7,
    ["Solo vs. Commander Bot Stardate 4"]  = 6,
    ["Solo vs. Commander Bot Stardate 5"]  = 5,
    ["Solo vs. Captain Bot Stardate 1"]    = 5,
    ["Solo vs. Captain Bot Stardate 2"]    = 6,
    ["Solo vs. Captain Bot Stardate 3"]    = 7,
    ["Solo vs. Captain Bot Stardate 4"]    = 6,
    ["Solo vs. Captain Bot Stardate 5"]    = 5,
    ["Solo vs. Admiral Bot Stardate 1"]    = 5,
    ["Solo vs. Admiral Bot Stardate 2"]    = 5,
    ["Solo vs. Admiral Bot Stardate 3"]    = 6,
    ["Solo vs. Admiral Bot Stardate 4"]    = 6,
    ["Solo vs. Admiral Bot Stardate 5"]    = 5,
  }
  local gloryCount = cardGloryCounts[cardName]
  local bagGlory = getObjectbyName("Central Glory Token Bag")
  local posGlory = {
    { -11.00, 0.85, 4.00 },
    { -12.50, 0.85, 4.00 },
    { -14.00, 0.85, 4.00 },
    { -11.00, 0.85, 5.50 },
    { -12.50, 0.85, 5.50 },
    { -14.00, 0.85, 5.50 },
    { -15.50, 0.85, 4.75 },
  }
  if gloryCount then
    for i = 1, gloryCount do
      local tokenGlory = bagGlory.takeObject()
      local rotGlory = { 0.00, 180.00, 180.00 }
      tokenGlory.setRotation(rotGlory)
      tokenGlory.setPositionSmooth(posGlory[i], false, true)
      tokenGlory.interactable = false
    end
    broadcastToAll(gloryCount .. " Glory has been refreshed for: " .. cardName, "Green")
  else
    return
  end
end