-- handles functionality related to the Stardate & Glory area


function refreshGlory()
  -- handles functionality of refreshing the glory to glory area, counter etc per stardate card

  -- animate button click (is needed?)
  -- animateButton(getObjectbyName("Button Refresh Glory"))

  -- first check to make sure drop area isn't already populated
  local checkZone = getObjectbyName("Zone Stardate Glory")
  local gloryFound = false
  for _, zoneObj in pairs(checkZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      gloryFound = true
    end
  end
  if gloryFound then
    broadcastToAll("Refresh Glory Action only works while Stardate card is out of glory.", "Orange")
    return
  end

  -- determine cardName
  local cardName = nil
  for _, object in pairs(getObjectbyName("Zone Stardate").getObjects()) do
    if object.tag == "Deck" then -- if deck, get top card
      local cardsInDeck = object.getObjects()
      cardName = cardsInDeck[#cardsInDeck].name
    elseif object.tag == "Card" then
      cardName = object.getName()
    end
  end

  -- determine glory count to refresh per card name
  local cardGloryCounts = {
    ["2-Player Stardate 1"]                = 5,
    ["2-Player Stardate 2"]                = 7,
    ["2-Player Stardate 3"]                = 7,
    ["2-Player Stardate 4"]                = 6,
    ["2-Player Stardate 5"]                = 5,
    ["Solo Cadet Practice 1"]              = 5,
    ["Solo Cadet Practice 2"]              = 5,
    ["Solo vs. Ensign Bot Stardate 1"]     = 6,
    ["Solo vs. Ensign Bot Stardate 2"]     = 7,
    ["Solo vs. Ensign Bot Stardate 3"]     = 7,
    ["Solo vs. Ensign Bot Stardate 4"]     = 6,
    ["Solo vs. Ensign Bot Stardate 5"]     = 5,
    ["Solo vs. Lieutenant Bot Stardate 1"] = 5,
    ["Solo vs. Lieutenant Bot Stardate 2"] = 7,
    ["Solo vs. Lieutenant Bot Stardate 3"] = 7,
    ["Solo vs. Lieutenant Bot Stardate 4"] = 6,
    ["Solo vs. Lieutenant Bot Stardate 5"] = 5,
    ["Solo vs. Commander Bot Stardate 1"]  = 5,
    ["Solo vs. Commander Bot Stardate 2"]  = 7,
    ["Solo vs. Commander Bot Stardate 3"]  = 7,
    ["Solo vs. Commander Bot Stardate 4"]  = 6,
    ["Solo vs. Commander Bot Stardate 5"]  = 5,
    ["Solo vs. Captain Bot Stardate 1"]    = 5,
    ["Solo vs. Captain Bot Stardate 2"]    = 6,
    ["Solo vs. Captain Bot Stardate 3"]    = 7,
    ["Solo vs. Captain Bot Stardate 4"]    = 6,
    ["Solo vs. Captain Bot Stardate 5"]    = 5,
    ["Solo vs. Admiral Bot Stardate 1"]    = 5,
    ["Solo vs. Admiral Bot Stardate 2"]    = 5,
    ["Solo vs. Admiral Bot Stardate 3"]    = 6,
    ["Solo vs. Admiral Bot Stardate 4"]    = 6,
    ["Solo vs. Admiral Bot Stardate 5"]    = 5,
  }
  local gloryCount = cardGloryCounts[cardName]
  local bagGlory = getObjectbyName("Central Glory Token Bag")
  local posGlory = {
    { -11.00, 0.85, 4.00 },
    { -12.50, 0.85, 4.00 },
    { -14.00, 0.85, 4.00 },
    { -11.00, 0.85, 5.50 },
    { -12.50, 0.85, 5.50 },
    { -14.00, 0.85, 5.50 },
    { -15.50, 0.85, 4.75 },
  }
  if gloryCount then
    for i = 1, gloryCount do
      local tokenGlory = bagGlory.takeObject()
      local rotGlory = { 0.00, 180.00, 180.00 }
      tokenGlory.setRotation(rotGlory)
      tokenGlory.setPositionSmooth(posGlory[i], false, true)
      tokenGlory.interactable = false
    end
    broadcastToAll(gloryCount .. " Glory has been refreshed for: " .. cardName, "Green")
  else
    return
  end
end


function updateStardateGloryCounter()
  -- handles counter update for stardate glory counter as glory enters/leaves zone
  local stardateCheckZone = getObjectbyName("Zone Stardate Glory")
  local gloryCount = 0
  for _, zoneObj in pairs(stardateCheckZone.getObjects()) do
    if zoneObj.getName() == "Glory Token" then
      gloryCount = gloryCount + 1
    end
  end

  -- only update if stardate pad is set with a difficulty, indicating game in progress
  local buttonObj = getObjectbyName("Glory Counter Stardate")
  local padStardate = getObjectbyName("Pad Stardate")
  if padStardate.getGMNotes() ~= "None" then
    buttonObj.call("setValue", gloryCount)
  end
end


-- **** STARDATE CARD FUNCTIONS ****

-- function stardate_card_button_create(args)
--     local card          = args.card
--     local type          = args.type -- types: "Market Only", "Both", "Endgame", "Discard"
--     local color         = args.color
--     local button_color  = color == "Blue" and {31/255, 136/255, 255/255, .8} or {219/255, 26/255, 24/255, .8}
--     local hover_color   = color == "Blue" and {31/255, 136/255, 255/255, .6} or {219/255, 26/255, 24/255, .6}
--     local click_func    = nil
--     local button_pos    = nil
--     local button_width  = 920
--     local button_height = nil
--     local tooltip       = nil
--     if type            == "Market Only" then
--         click_func      = "button_stardate_market_wipe"
--         button_pos      = {0.04, 0.25, -0.24}
--         button_height   = 420
--         tooltip         = "Click this button to perform Stardate Market Wipe, and discard this card."
--     elseif type        == "Both" then
--         click_func      = "button_stardate_both_wipe"
--         button_pos      = {0.04, 0.25, -0.24}
--         button_height   = 560
--         tooltip         = "Click this button to perform Stardate Market and Location Wipe, and discard this card."
--     elseif type        == "Endgame" then
--         click_func      = "button_stardate_trigger_endgame"
--         button_pos      = {0.04, 0.25, -0.24}
--         button_height   = 260
--         tooltip         = "Click this button to trigger End Of Game."
--     elseif type        == "Discard" then
--         click_func      = "button_stardate_discard"
--         button_pos      = {0.04, 0.25, -0.24}
--         button_height   = 560
--         tooltip         = "Click this button to discard this Stardate Card."
--     end
--     if string.find(card.getName(), "Solo Cadet Practice") then
--         button_pos = {0.04, 0.25, -0.34}
--     end
--     card.createButton({
--         click_function  = click_func,
--         function_owner  = self,
--         label           = "",
--         position        = button_pos,
--         rotation        = {0, 180, 0},
--         width           = button_width,
--         height          = button_height,
--         color           = button_color,
--         hover_color     = hover_color,
--         tooltip         = tooltip,
--     })
-- end -- end stardate_card_button_create()


-- function button_stardate_both_wipe(button, _, _)
--     stardate_location_wipe()
--     stardate_market_wipe()
--     -- discard stardate card
--     getObjectFromGUID("f6e30d").putObject(button)
--     broadcastToAll("[" .. Color.fromString("Yellow"):toHex() .. "]" .. button.getName() .. "[-] has been discarded!", "White")
--     -- -- get playerarea it's clicked from
--     -- local playerarea   = nil
--     -- for _, object in pairs(getObjectFromGUID("").getObjects()) do
--     --     if object == self then
--     --         playerarea = "Blue"
--     --     end
--     -- end
--     -- for _, object in pairs
--     -- local bot_color, _ = get_colors()
--     -- if bot_color ~= nil then
--     --     if bot_color == "Blue"
--     -- end
-- end -- end stardate_both_wipe()


-- function button_stardate_discard(button, _, _)
--     -- discard stardate card
--     getObjectFromGUID("f6e30d").putObject(button)
--     broadcastToAll("[" .. Color.fromString("Yellow"):toHex() .. "]" .. button.getName() .. "[-] has been discarded!", "White")
-- end -- end button_stardate_discard()


-- function button_stardate_market_wipe(button, _, _)
--     stardate_market_wipe()
--     -- discard stardate card
--     getObjectFromGUID("f6e30d").putObject(button)
--     broadcastToAll("[" .. Color.fromString("Yellow"):toHex() .. "]" .. button.getName() .. "[-] has been discarded!", "White")
-- end -- end button_stardate_market_wipe()


-- function stardate_location_wipe()
--     -- perform stardate location wipe
--     -- will need to check all NZs for tokens present, don't wipe those
--     local checkzones_top    = {getObjectFromGUID("eaec24"), getObjectFromGUID("817308")}
--     local checkzones_middle = {getObjectFromGUID("3c477c"), getObjectFromGUID("a0256f")}
--     local checkzones_bottom = {getObjectFromGUID("ba30f9"), getObjectFromGUID("758ef4")}
--     local zone_loc_top      = getObjectFromGUID("65beaa")
--     local zone_loc_middle   = getObjectFromGUID("429b74")
--     local zone_loc_bottom   = getObjectFromGUID("8e265f")
--     local pos_top           = {0.00, 1.50, -7.00}
--     local pos_middle        = {0.00, 1.50, -14.00}
--     local pos_bottom        = {0.00, 1.50, -21.00}
--     local zone_new_locs     = getObjectFromGUID("97d9f0")
--     for i = 1, 3 do
--         if i == 1 then
--             wait_timer = 0
--         elseif i == 2 then
--             wait_timer = .5
--         elseif i == 3 then
--             wait_timer = 1
--         end
--         Wait.time(function()
--         local checkzones    = nil
--         local zone_loc      = nil
--         local position      = nil
--         local need_replace  = true
--         if i == 1 then
--             checkzones      = checkzones_top
--             zone_loc        = zone_loc_top
--             position        = pos_top
--         elseif i == 2 then
--             checkzones      = checkzones_middle
--             zone_loc        = zone_loc_middle
--             position        = pos_middle
--         elseif i == 3 then
--             checkzones      = checkzones_bottom
--             zone_loc        = zone_loc_bottom
--             position        = pos_bottom
--         end
--         for j = 1, 2 do
--             for _, object in pairs(checkzones[j].getObjects()) do
--                 if object.hasTag('snap_ship') or object.hasTag('away_blue') or object.hasTag('away_red') then
--                     need_replace = false
--                 end
--             end
--         end
--         if need_replace then
--             local outgoing_card_name = nil
--             local replace_card_name  = nil
--             local replacement_found  = false
--             -- discard outgoing_card
--             for _, object in pairs(zone_loc.getObjects()) do
--                 if object.tag == "Card" then
--                     object.setRotation({0.00, 180.00, 0.00})
--                     object.setPositionSmooth({-12.50, 1.50, 12.00}, false, false)
--                     outgoing_card_name = object.getName()
--                 end
--             end
--             -- replace if possible
--             for _, object in pairs(zone_new_locs.getObjects()) do
--                 if object.tag == "Deck" then
--                     local replace_card = object.takeObject()
--                     replace_card.setRotation({0.00, 180.00, 0.00})
--                     replace_card.setPositionSmooth(position, false, false)
--                     replace_card_name = replace_card.getName()
--                     replacement_found = true
--                     break
--                 elseif object.tag == "Card" then
--                     local replace_card = object
--                     replace_card.setRotation({0.00, 180.00, 0.00})
--                     replace_card.setPositionSmooth(position, false, false)
--                     replace_card_name = replace_card.getName()
--                     replacement_found = true
--                     break
--                 end
--             end
--             if replacement_found then
--                 broadcastToAll("[" .. Color.fromString("Green"):toHex() .. "]Location[-]: " ..outgoing_card_name .. " has been discarded via [" .. Color.fromString("Yellow"):toHex() .. "]Stardate Card[-], and replaced with " .. replace_card_name .. ".", "White")
--             else
--                 broadcastToAll("[" .. Color.fromString("Green"):toHex() .. "]Location[-]: " ..outgoing_card_name .. " has been discarded via [" .. Color.fromString("Yellow"):toHex() .. "]Stardate Card[-], there was no replacement Location.", "White")
--             end
--         end
--         end, wait_timer)
--     end
-- end -- end stardate_location_wipe()

-- function stardate_market_wipe()
--     -- perform stardate market wipe
--     local card_zones = {
--         getObjectFromGUID("7d6590"),
--         getObjectFromGUID("ac4301"),
--         getObjectFromGUID("489f00"),
--         getObjectFromGUID("2edc6f"),
--     }
--     local deck_zones = {
--         getObjectFromGUID("99a16f"),
--         getObjectFromGUID("4eadea"),
--         getObjectFromGUID("1a337a"),
--         getObjectFromGUID("68e891"),
--     }
--     -- will need to junk and replace on all 4 simultaneously,
--     for i = 1, 4 do
--         for _, object in pairs(card_zones[i].getObjects()) do
--             if object.tag == "Card" then
--                 object.setRotation({0.00, 180.00, 0.00})
--                 object.setPositionSmooth({-12.50, 1.50, 12.00})
--             end
--             if string.find(object.getName(), "Token") then
--                 object.destruct()
--             end
--         end
--         local position = {-7.50, 1.50, 6.00}
--         if i == 2 then
--             position   = {-2.50, 1.50, 6.00}
--         elseif i == 3 then
--             position   = {2.50, 1.50, 6.00}
--         elseif i == 4 then
--             position = {7.50, 1.50, 6.00}
--         end
--         for _, object in pairs(deck_zones[i].getObjects()) do
--             local replacement = nil
--             if object.tag == "Deck" then
--                 replacement = object.takeObject()
--                 replacement.setRotation({0.00, 180.00, 0.00})
--                 replacement.setPositionSmooth(position, false, false)
--                 break
--             elseif object.tag == "Card" then
--                 replacement = object
--                 replacement.setRotation({0.00, 180.00, 0.00})
--                 replacement.setPositionSmooth(position, false, false)
--                 break
--             end
--         end
--     end
--     broadcastToAll("The Market has been Wiped according to the [" .. Color.fromString("Yellow"):toHex() .. "]Stardate Card[-]. ", "White")
-- end -- end stardate_market_wipe()


-- function button_stardate_trigger_endgame(button, _, _)
--     stardate_trigger_endgame()
--     -- discard stardate card
--     getObjectFromGUID("f6e30d").putObject(button)
--     broadcastToAll("[" .. Color.fromString("Yellow"):toHex() .. "]" .. button.getName() .. "[-] has been discarded!", "White")
-- end -- end button_stardate_trigger_endgame()

-- function button_stardate_trigger_endgame_remote(args)
--     button = args.button
--     stardate_trigger_endgame()
--     -- discard stardate card
--     getObjectFromGUID("f6e30d").putObject(button)
--     broadcastToAll("[" .. Color.fromString("Yellow"):toHex() .. "]" .. button.getName() .. "[-] has been discarded!", "White")
-- end -- end button_stardate_trigger_endgame_remote()


-- function stardate_trigger_endgame()
--     -- determine if it's currently 1P's turn or 2P's turn,
--     -- to, determine how many rounds are left
--     -- broadcast that end of game has been triggered, and how many rounds are left for who
--     broadcastToAll("[" .. Color.fromString("Yellow"):toHex() .. "]Final Stardate Card and End of Game[-] have been triggered! Finish remaining rounds, and use the Calcuate Score button under Score Sheets when finished.", "White")
--     -- deploy score sheets & buttons
--     local bag = getObjectFromGUID("f6e30d")
--     local blue_sheet  = bag.takeObject({guid="276508"})
--     blue_sheet.interactable = false
--     blue_sheet.setLock(true)
--     blue_sheet.setRotation({0.00, 270.00, 0.00})
--     blue_sheet.setPosition({-38.50, 1.70, -27.80}, false, false)
--     local blue_button = bag.takeObject({guid="698936"})
--     blue_button.interactable = false
--     blue_button.setLock(true)
--     blue_button.setRotation({0.00, 270.00, 0.00})
--     blue_button.setPosition({-42.65, 1.70, -27.80}, false, false)
--     local red_sheet   = bag.takeObject({guid="6931ee"})
--     red_sheet.interactable = false
--     red_sheet.setLock(true)
--     red_sheet.setRotation({0.00, 90.00, 0.00})
--     red_sheet.setPosition({38.50, 1.70, 27.80}, false, false)
--     local red_button  = bag.takeObject({guid="3c8845"})
--     red_button.interactable = false
--     red_button.setLock(true)
--     red_button.setRotation({0.00, 90.00, 0.00})
--     red_button.setPosition({42.65, 1.70, 27.80}, false, false)
--     local counter     = getObjectFromGUID("b7d51f")
--     local counter_pos = counter.getPosition()
--     counter_pos.y     = -2
--     counter.setPosition(counter_pos)
--     counter.flip()
-- end -- end stardate_trigger_endgame()